/* Copyright 2026 Rhett Creighton - Apache License 2.0
 *
 * purpose: routes test-harness and lint-gate files to their owning test
 * group by test_<group>.c naming, the Windows-acceptance SOURCES table, and
 * string-literal name references, for zcl_native_code_route_for_path().
 */

#ifndef _POSIX_C_SOURCE
#define _POSIX_C_SOURCE 200809L
#endif

#include "controllers/agent_impact_harness.h"

#include "test_group_catalog.h"
#include "util/file_io.h"

#include <ctype.h>
#include <dirent.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

enum {
    AIH_LINE_MAX = 4096,
    AIH_TABLE_MAX = 1u << 20, /* windows_acceptance.mk is ~30 KiB */
    /* Largest real harness TU today is tests/harness/src/fixture_tx_oversize_478544.c
     * at 638,600 bytes (a generated byte-array KAT fixture); this cap clears it
     * with headroom rather than skip-and-log a file with an ERROR line on every
     * scan. */
    AIH_REFERRER_MAX = 1u << 20,
    AIH_NEEDLE_MIN = 4,
};

static const char AIH_HARNESS_DIR[] = "tests/harness/src/";
static const char AIH_WINDOWS_ACCEPTANCE_TABLE[] =
    "platform/modules/platform/tests/windows_acceptance.mk";
static const char *const AIH_REFERRER_DIRS[] = {
    "tests/harness/src", "tools/lint/lintc",
};

bool agent_impact_harness_test_group_name(
    const char *path, char out[static ZCL_AGENT_IMPACT_GROUP_MAX])
{
    if (!path || strncmp(path, AIH_HARNESS_DIR, sizeof(AIH_HARNESS_DIR) - 1) != 0)
        return false;
    const char *base = path + (sizeof(AIH_HARNESS_DIR) - 1);
    if (!base[0] || strchr(base, '/'))
        return false; /* must live directly in the harness src dir */

    size_t blen = strlen(base);
    static const char ext[] = ".c";
    size_t elen = sizeof(ext) - 1;
    if (blen <= elen || strcmp(base + blen - elen, ext) != 0)
        return false;

    char stem[ZCL_TEST_GROUP_FULL_MAX];
    size_t stem_len = blen - elen;
    if (stem_len >= sizeof(stem))
        return false;
    memcpy(stem, base, stem_len);
    stem[stem_len] = '\0';

    if (strncmp(stem, "test_", 5) != 0 && strncmp(stem, "spec_", 5) != 0)
        return false;
    if (!zcl_test_group_catalog_contains(stem))
        return false; // raw-return-ok:not-in-catalog-means-not-a-group

    (void)snprintf(out, ZCL_AGENT_IMPACT_GROUP_MAX, "%s", stem + 5);
    return true;
}

/* True when trimming trailing CR/space/tab off `line` leaves a final '\\' —
 * the Makefile continuation marker. */
static bool aih_line_continues(const char *line)
{
    size_t n = strlen(line);
    while (n > 0 && (line[n - 1] == '\r' || line[n - 1] == ' ' || line[n - 1] == '\t'))
        n--;
    return n > 0 && line[n - 1] == '\\';
}

/* Splits an already-unbackslashed logical row on whitespace and reports
 * whether any token equals `rel_path` (an exact `:=`-stripped match, never a
 * substring — a token that happens to contain the path is not the path). */
static bool aih_row_has_token(char *row, const char *rel_path)
{
    char *save = NULL;
    for (char *tok = strtok_r(row, " \t", &save); tok;
         tok = strtok_r(NULL, " \t", &save)) {
        const char *assign = strstr(tok, ":=");
        const char *candidate = assign ? assign + 2 : tok;
        if (candidate[0] && strcmp(candidate, rel_path) == 0)
            return true;
    }
    return false;
}

/* One already-terminated logical line of the table: updates *in_sources for
 * the NEXT line and reports whether THIS line (when inside a _SOURCES
 * assignment) names `rel_path`. Split out of the char-by-char scan below
 * purely to keep that scan's own branching under the complexity cap. */
static bool aih_scan_line(const char *line, bool *in_sources,
                          const char *rel_path)
{
    if (!*in_sources && strstr(line, "_SOURCES") && strstr(line, ":="))
        *in_sources = true;
    bool hit = false;
    if (*in_sources) {
        char row[AIH_LINE_MAX];
        (void)snprintf(row, sizeof(row), "%s", line);
        for (char *q = row; *q; q++)
            if (*q == '\\') *q = ' ';
        hit = aih_row_has_token(row, rel_path);
    }
    if (!aih_line_continues(line))
        *in_sources = false;
    return hit;
}

bool agent_impact_windows_acceptance_table_lists(const char *table_text,
                                                 const char *rel_path)
{
    if (!table_text || !rel_path || !rel_path[0])
        return false;

    bool in_sources = false;
    char line[AIH_LINE_MAX];
    size_t n = 0;
    for (const char *p = table_text;; p++) {
        char c = *p;
        bool eof = c == '\0';
        if (c != '\n' && !eof) {
            if (n < sizeof(line) - 1)
                line[n++] = c;
            continue;
        }
        line[n] = '\0';
        if (aih_scan_line(line, &in_sources, rel_path))
            return true;
        n = 0;
        if (eof) break;
    }
    return false;
}

static bool aih_path_in_windows_acceptance_table(const char *rel_path)
{
    char *text = NULL;
    size_t len = 0;
    if (!zcl_read_whole_file_text(AIH_WINDOWS_ACCEPTANCE_TABLE, AIH_TABLE_MAX,
                                  &text, &len, "agent_impact_harness"))
        return false;
    bool hit = agent_impact_windows_acceptance_table_lists(text, rel_path);
    free(text);
    (void)len;
    return hit;
}

bool agent_impact_apply_harness_routes(const char *path,
                                       struct agent_impact_acc *acc)
{
    if (!path || !acc)
        return false;
    if (strncmp(path, AIH_HARNESS_DIR, sizeof(AIH_HARNESS_DIR) - 1) != 0)
        return false;

    char group[ZCL_AGENT_IMPACT_GROUP_MAX];
    if (agent_impact_harness_test_group_name(path, group)) {
        agent_impact_add_group(acc, group);
        acc->shared_rule_hits++;
        return true;
    }
    if (aih_path_in_windows_acceptance_table(path)) {
        agent_impact_add_group(acc, "make_lint_gates");
        acc->shared_rule_hits++;
        return true;
    }
    return false;
}

static bool aih_span_has_needle(const char *s, size_t slen, const char *needle,
                                size_t needle_len)
{
    if (needle_len == 0 || needle_len > slen)
        return false;
    for (size_t i = 0; i + needle_len <= slen; i++)
        if (memcmp(s + i, needle, needle_len) == 0)
            return true;
    return false;
}

/* True when `c` cannot extend an identifier or a filename/extension token —
 * i.e. it is safe to treat as the edge of a WHOLE-TOKEN match (a quote,
 * space, slash, punctuation, or the start/end of the literal all count). */
static bool aih_is_token_boundary(char c)
{
    return !(isalnum((unsigned char)c) || c == '_' || c == '.' || c == '-');
}

/* Same scan as aih_span_has_needle, but a hit only counts when it is
 * bounded on both sides by aih_is_token_boundary() (or the start/end of
 * the literal): "main.c" matches inside "tools/soak/main.c" (left = '/',
 * right = end) but not inside "main.cpp" (right = 'p', an identifier char)
 * or "domain_main.c" (left = '_'). This is what keeps a common short
 * basename from fanning out into every unrelated identifier that happens
 * to contain it as a substring. */
static bool aih_span_has_bounded_needle(const char *s, size_t slen,
                                        const char *needle, size_t needle_len)
{
    if (needle_len == 0 || needle_len > slen)
        return false;
    for (size_t i = 0; i + needle_len <= slen; i++) {
        if (memcmp(s + i, needle, needle_len) != 0)
            continue;
        bool left_ok = i == 0 || aih_is_token_boundary(s[i - 1]);
        bool right_ok = i + needle_len == slen ||
                        aih_is_token_boundary(s[i + needle_len]);
        if (left_ok && right_ok)
            return true;
    }
    return false;
}

/* Walks every string literal in `text` (honoring backslash escapes) and
 * reports whether any one of them contains `needle` — bounded to a whole
 * token when `bounded` is set, an unbounded substring scan otherwise. */
static bool aih_scan_literals(const char *text, const char *needle, bool bounded)
{
    if (!text || !needle || !needle[0])
        return false;
    size_t needle_len = strlen(needle);
    bool in_str = false;
    const char *lit_start = NULL;
    for (const char *p = text;; p++) {
        char c = *p;
        if (c == '\0') {
            if (in_str) {
                size_t slen = (size_t)(p - lit_start);
                return bounded
                    ? aih_span_has_bounded_needle(lit_start, slen, needle, needle_len)
                    : aih_span_has_needle(lit_start, slen, needle, needle_len);
            }
            return false;
        }
        if (!in_str) {
            if (c == '"') { in_str = true; lit_start = p + 1; }
            continue;
        }
        if (c == '\\' && p[1]) { p++; continue; }
        if (c == '"') {
            size_t slen = (size_t)(p - lit_start);
            bool hit = bounded
                ? aih_span_has_bounded_needle(lit_start, slen, needle, needle_len)
                : aih_span_has_needle(lit_start, slen, needle, needle_len);
            if (hit)
                return true;
            in_str = false;
        }
    }
}

bool agent_impact_string_literal_contains(const char *text, const char *needle)
{
    return aih_scan_literals(text, needle, false);
}

/* Same as agent_impact_string_literal_contains(), but the match must land
 * on a whole token (see aih_is_token_boundary) — used for the single-word
 * basename form of a name reference, where an unbounded substring scan is
 * unsafe (a common short word like "main" is a substring of many unrelated
 * identifiers). */
bool agent_impact_string_literal_contains_whole_token(const char *text, const char *needle)
{
    return aih_scan_literals(text, needle, true);
}

/* `path`'s basename with the .c extension stripped; false when it does not
 * end in .c or the stem is shorter than the noise floor. */
static bool aih_basename_stem(const char *path, char out[static ZCL_AGENT_IMPACT_GROUP_MAX])
{
    const char *slash = strrchr(path, '/');
    const char *base = slash ? slash + 1 : path;
    size_t blen = strlen(base);
    static const char ext[] = ".c";
    size_t elen = sizeof(ext) - 1;
    if (blen <= elen || strcmp(base + blen - elen, ext) != 0)
        return false;
    size_t stem_len = blen - elen;
    if (stem_len < AIH_NEEDLE_MIN || stem_len >= ZCL_AGENT_IMPACT_GROUP_MAX)
        return false;
    memcpy(out, base, stem_len);
    out[stem_len] = '\0';
    return true;
}

/* `stem` with every '-' rewritten to '_'; false when nothing changed (no
 * point searching the same needle twice). */
static bool aih_underscore_variant(const char *stem, char out[static ZCL_AGENT_IMPACT_GROUP_MAX])
{
    bool changed = false;
    size_t i = 0;
    for (; stem[i]; i++) {
        out[i] = stem[i] == '-' ? '_' : stem[i];
        if (out[i] != stem[i]) changed = true;
    }
    out[i] = '\0';
    return changed;
}

/* A compound stem (has an internal '-' or '_', e.g. "zcl-rpc", "engine_unit")
 * is a distinctive project token: it is vanishingly unlikely to occur as an
 * accidental substring of an unrelated identifier or English word, so it can
 * still be matched with a plain unbounded substring scan (this is the
 * matching this file has always done, unchanged). A single-word stem
 * (e.g. "main", "test", "download") carries no such guarantee — "main" is a
 * substring of "domain", the C keyword appears bare in unrelated test
 * fixtures, and so on — so it is only matched in its extension-qualified,
 * whole-token form (see aih_scan_dir_for_reference). */
static bool aih_stem_is_compound(const char *stem)
{
    return strchr(stem, '-') != NULL || strchr(stem, '_') != NULL;
}

/* The referencing file's own group(s): rules 1/2 above, plus the shared rule
 * table it would earn on its own merits. Never rule 3 — a referencer never
 * chains into a second referencer's referencers. */
static void aih_own_groups(const char *referrer_path, struct agent_impact_acc *dst)
{
    if (!agent_impact_apply_harness_routes(referrer_path, dst))
        (void)agent_impact_apply_shared_rules(referrer_path, dst);
}

static void aih_merge_referrer_hit(const char *referrer_path,
                                   struct agent_impact_acc *acc, bool *matched)
{
    struct agent_impact_acc found = {0};
    aih_own_groups(referrer_path, &found);
    for (size_t i = 0; i < found.groups_len; i++)
        agent_impact_add_group(acc, found.groups[i]);
    if (found.groups_len > 0) {
        acc->shared_rule_hits++;
        *matched = true;
    }
}

static bool aih_referrer_hits(const char *text, const char *path,
                              const char *stem, const char *alt,
                              bool has_alt, bool compound)
{
    if (compound) {
        /* Distinctive compound token (has '-' or '_'): the plain unbounded
         * substring scan this file has always used — a hit anywhere inside
         * a longer identifier (e.g. "zcl_rpc" inside "binary_missing_zcl_rpc")
         * still counts as a deliberate name reference. */
        return agent_impact_string_literal_contains(text, stem) ||
               (has_alt && agent_impact_string_literal_contains(text, alt));
    }
    (void)alt;
    (void)has_alt;
    /* Single-word stem (e.g. "main"): a bare or even extension-qualified
     * basename ("main.c") is still ambiguous — this repo has several
     * unrelated main.c files (tools/soak/main.c, tools/lint/lintc/main.c,
     * a fixture's app/main.c), and a literal that names one of them says
     * nothing about the others. Require the query's full repo-relative
     * path as a whole-token match instead: this is what "tools/soak/main.c"
     * satisfies (bounded by the start/end of the literal or a non-identifier
     * char) while "domain_main_thing" and an unrelated "app/main.c" do not. */
    return agent_impact_string_literal_contains_whole_token(text, path);
}

static void aih_scan_dir_for_reference(const char *dir, const char *path,
                                       const char *stem, const char *alt,
                                       bool has_alt, bool compound,
                                       struct agent_impact_acc *acc,
                                       bool *matched)
{
    DIR *dh = opendir(dir);
    if (!dh) return;
    struct dirent *ent;
    while ((ent = readdir(dh)) != NULL) {
        const char *name = ent->d_name;
        size_t nlen = strlen(name);
        if (nlen < 3 || strcmp(name + nlen - 2, ".c") != 0)
            continue;
        char relp[512];
        (void)snprintf(relp, sizeof(relp), "%s/%s", dir, name);
        if (strcmp(relp, path) == 0)
            continue;

        char *text = NULL;
        size_t len = 0;
        if (!zcl_read_whole_file_text(relp, AIH_REFERRER_MAX, &text, &len,
                                      "agent_impact_name_reference"))
            continue;
        bool hit = aih_referrer_hits(text, path, stem, alt, has_alt, compound);
        free(text);
        (void)len;
        if (hit)
            aih_merge_referrer_hit(relp, acc, matched);
    }
    closedir(dh);
}

/* Scanning every tests/harness/src/ and tools/lint/lintc/ file's content is
 * only cheap enough to run unconditionally for the class of path it can
 * actually hit: a tools/-rooted translation unit builds a named binary
 * (zcl-rpc, zclassic23-package-sign, …), and THAT name — not an #include
 * edge — is what a lint-gate assertion or an acceptance harness names in a
 * string literal. A core/engine/platform/contexts source is reached through
 * compiled-source edges the shared rule table already walks, never through
 * a quoted binary name, so scanning for it here would only spend the ~1,300
 * file reads for a query that can never match — bounding this to `tools/`
 * keeps the common `code tests` call at its prior no-scan cost. */
static bool aih_path_can_be_name_referenced(const char *path)
{
    static const char prefix[] = "tools/";
    return strncmp(path, prefix, sizeof(prefix) - 1) == 0;
}

bool agent_impact_apply_name_reference_routes(const char *path,
                                              struct agent_impact_acc *acc)
{
    if (!path || !acc || !aih_path_can_be_name_referenced(path))
        return false;
    char stem[ZCL_AGENT_IMPACT_GROUP_MAX];
    if (!aih_basename_stem(path, stem))
        return false; // raw-return-ok:not-eligible-for-name-reference
    char alt[ZCL_AGENT_IMPACT_GROUP_MAX];
    bool has_alt = aih_underscore_variant(stem, alt);
    bool compound = aih_stem_is_compound(stem);

    bool matched = false;
    for (size_t d = 0; d < sizeof(AIH_REFERRER_DIRS) / sizeof(AIH_REFERRER_DIRS[0]); d++)
        aih_scan_dir_for_reference(AIH_REFERRER_DIRS[d], path, stem, alt, has_alt,
                                   compound, acc, &matched);
    return matched;
}
