/* Copyright 2026 Rhett Creighton - Apache License 2.0
 *
 * Golden-height UTXO root ladder: cross-checked SHA3 UTXO-set
 * commitments at fixed stride heights (every UTXO_ROOT_LADDER_STRIDE
 * blocks, boundary-aligned to MMR_COMMITMENT_INTERVAL) plus the one
 * zclassicd-verified SHA3 UTXO checkpoint rung (height 3,056,758).
 *
 * The blockchain is immutable history: once a stride height's
 * boundary root is folded from block bodies and cross-checked, it
 * never changes — this table is a free, permanent reproducibility
 * anchor a node can verify its own coins_kv against without
 * re-folding from genesis. See utxo_root_ladder_verify_against_store()
 * (engine/models/src/utxo_root_ladder_verify.c) for the live tripwire:
 * any mismatch between a locked rung and this node's OWN boundary-root
 * store is a named divergence at a named height, never a silent stop.
 *
 * Generated by tools/gen_utxo_root_ladder. Do not edit by hand. */

#ifndef ZCL_CHAIN_UTXO_ROOT_LADDER_H
#define ZCL_CHAIN_UTXO_ROOT_LADDER_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#define UTXO_ROOT_LADDER_STRIDE 100000

enum utxo_root_ladder_provenance {
    /* One independently-copied boundary-root store recorded this
     * value. Not yet cross-checked against a second source. */
    UTXO_ROOT_LADDER_SOURCE_SINGLE     = 0,
    /* Two independently-folded node.db copies agree bit-for-bit
     * on both the block hash and the UTXO root at this height. */
    UTXO_ROOT_LADDER_SOURCE_DUAL       = 1,
    /* The compiled SHA3 UTXO checkpoint (core/modules/chain/src/checkpoints.c),
     * independently verified bit-for-bit against zclassicd. */
    UTXO_ROOT_LADDER_SOURCE_CHECKPOINT = 2,
};

struct utxo_root_ladder_entry {
    int32_t height;
    uint8_t block_hash[32];
    uint8_t utxo_root[32];
    uint8_t provenance;  /* enum utxo_root_ladder_provenance */
};

extern const struct utxo_root_ladder_entry g_utxo_root_ladder[];
extern const size_t g_utxo_root_ladder_count;

/* Dense layer (optional; height==-1 means absent): mmb_root(),
 * recomputed from the raw leaf-hash pipeline up to and including
 * `g_utxo_root_ladder_dense_height`, locked as one constant. */
extern const int32_t g_utxo_root_ladder_dense_height;
extern const uint8_t g_utxo_root_ladder_dense_mmb_root[32];

/* Returns the entry at exactly `height`, or NULL — not every height
 * is a rung, only stride multiples of UTXO_ROOT_LADDER_STRIDE plus
 * the one checkpoint-anchored rung. O(count), count is tiny. */
const struct utxo_root_ladder_entry *utxo_root_ladder_lookup(int32_t height);

size_t utxo_root_ladder_count(void);

#endif /* ZCL_CHAIN_UTXO_ROOT_LADDER_H */
