#!/usr/bin/env bash
# Copyright 2026 Rhett Creighton - Apache License 2.0
#
# Regenerate lib/hotswap/include/hotswap/core_seal_root.h from the ROOT line of
# core/MANIFEST.sha3. Invoked by `make core-seal` right after the manifest is
# rewritten, so the mirror can never lag the seal by more than one command.
#
#   tools/scripts/gen_core_seal_root.sh          write the header
#   tools/scripts/gen_core_seal_root.sh --check  exit 1 if it would change
#   tools/scripts/gen_core_seal_root.sh --selftest prove exact ROOT validation
#
# The header is committed on purpose. Baking the value through a -D flag would
# mean every build profile, every module recipe and the standalone verifier each
# had to remember to pass it, and a single miss would silently disarm the pin.
# Carrying it in a header means the value travels with the source: whatever
# compiles hotswap_activate.c and whatever compiles a module see the same
# constant with no flag plumbing at all.
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT_DIR"

MANIFEST="core/MANIFEST.sha3"
OUT="lib/hotswap/include/hotswap/core_seal_root.h"

# The repository's single exact 64-lowercase-hex predicate.
. "$ROOT_DIR/tools/scripts/source_identity_lib.sh"

if [ "${1:-}" = "--selftest" ]; then
    # `! cmd` is EXEMPT from set -e — bash does not exit for a command "whose
    # return value is being inverted with !", and the ERR trap is exempt for
    # the same reason. All three negative controls below used to be written
    # that way, so this selftest printed PASS whatever zcl_is_sha256 said
    # about a non-hex, a short, or an uppercase digest. refute() exits for
    # itself and names the assertion that was violated.
    refute() {
        if "$@"; then
            printf 'core_seal_root: selftest FAILED — expected non-zero from: %s\n' \
                "$*" >&2
            exit 1
        fi
    }
    zcl_is_sha256 "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
    refute zcl_is_sha256 "aaaaaaaaZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ"
    refute zcl_is_sha256 "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
    refute zcl_is_sha256 "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    echo "core_seal_root: selftest PASS — exact 64-character lowercase hex validation"
    exit 0
fi

[ -r "$MANIFEST" ] || {
    echo "gen_core_seal_root: $MANIFEST is not readable" >&2
    exit 2
}

root="$(awk '$1 == "ROOT" { print $2; exit }' "$MANIFEST")"
zcl_is_sha256 "$root" || root=""
[ -n "$root" ] || {
    echo "gen_core_seal_root: $MANIFEST has no 64-hex ROOT line" >&2
    echo "  Run 'make core-seal' first — a missing ROOT would disarm the pin." >&2
    exit 2
}


emit_header() {
cat <<EOF
/* Copyright 2026 Rhett Creighton - Apache License 2.0
 *
 * ZCL_CORE_SEAL_ROOT — the sealed consensus core's identity, as a compile-time
 * string. AUTO-GENERATED by \`make core-seal\`
 * (tools/scripts/gen_core_seal_root.sh). Do not edit by hand.
 *
 * WHY THIS FILE IS NOT UNDER core/. It mirrors the ROOT line of
 * core/MANIFEST.sha3, and the manifest digests every tracked file under core/.
 * A mirror living inside the sealed set would be part of its own input: writing
 * it would change the ROOT it had just recorded, forever. So it lives beside
 * the consumer instead, and tools/lint/check_core_seal_root_mirror.sh proves
 * the two agree — a forgotten regeneration fails \`make lint\`, it does not ship.
 *
 * WHAT IT IS FOR. A Tier-2 hot-swap module is compiled from ONE shape-leaf TU
 * and mounts into a resident node that supplies everything else, so the two
 * halves have to agree about the consensus layer they share. Nothing checked
 * that they did: hotswap_module_admit() verifies abi_version, fields, capacity,
 * the allowlist row, duplicates and the probe leaf — six stages, none of them
 * about consensus. (Tier-1's manifest path does compare a whole-tree build
 * identity, hotswap_loader.c; the real module ABI had no equivalent.)
 *
 * The gap is not theoretical. Sealed headers ship static inline bodies —
 * consensus_last_founders_reward_height() and
 * consensus_subsidy_slow_start_shift() among them — and every module that
 * includes one compiles a PRIVATE COPY of that body into its .so. Re-cut the
 * seal, rebuild the node, and a module built before the change still mounts,
 * still passes all six stages, and still runs its stale copy of the consensus
 * arithmetic. That is the cloned-ledger shape the architecture exists to
 * prevent, reached through a dlopen.
 *
 * Pinning the SEAL ROOT rather than a whole-tree build id is what keeps the
 * fast loop fast: editing a controller does not move this value, so the module
 * just built still mounts. Editing consensus does move it, and then every
 * module compiled against the old core is refused before leaf publication.
 *
 * SCOPE OF THE GUARANTEE. This is a generated, checked-in mirror, and nothing
 * in the BUILD forces it to be current: the hotswap-module-so recipe does not
 * depend on the core-seal target, so between a core/ edit and the next
 * 'make lint' the node and the module stamp the same STALE root and the pin
 * passes without meaning anything. check_core_seal_root_mirror.sh is the only
 * thing that catches that drift. The pin is therefore exactly as strong as
 * lint having run -- which is the intended design, lint being the backstop,
 * but it is the reason a seal re-cut must be followed by 'make core-seal' and
 * not merely by a successful build.
 *
 */

#ifndef ZCL_HOTSWAP_CORE_SEAL_ROOT_H
#define ZCL_HOTSWAP_CORE_SEAL_ROOT_H

/* SHA3-256 ROOT of core/MANIFEST.sha3 at generation time. */
#define ZCL_CORE_SEAL_ROOT \\
    "$root"

#endif /* ZCL_HOTSWAP_CORE_SEAL_ROOT_H */
EOF
}

# WHERE THE TEMP FILE GOES, AND WHY IT MATTERS.
#
# --check is run by check_core_seal_root_mirror.sh on EVERY `make lint`. If it
# mktemps beside $OUT, every lint run briefly creates an untracked file inside
# lib/hotswap/include/hotswap/. tools/dev/source-identity.sh inventories
# untracked files and fails closed with "source mutated during identity
# capture" when the tree changes under it, so that temp file randomly reds
# whichever gate happens to be capturing at the time (observed as
# check-zcode-package-registry: "empty package or monolith source projection",
# which names the symptom and not the cause). --check never renames anything,
# so it has no reason to be on the output's filesystem at all: it compares
# from a pipe-free process substitution and touches the repo zero times.
#
# The WRITE path still needs a temp beside $OUT — same filesystem is what
# makes the final mv atomic — but that path runs only from an explicit
# `make core-seal`, not from lint.
if [ "${1:-}" = "--check" ]; then
    if [ -r "$OUT" ] && cmp -s <(emit_header) "$OUT"; then
        echo "core_seal_root: OK — mirror matches $MANIFEST ROOT $root"
        exit 0
    fi
    echo "core_seal_root: DRIFT — $OUT does not match $MANIFEST" >&2
    echo "  manifest ROOT: $root" >&2
    echo "  Regenerate with 'make core-seal' (or tools/scripts/gen_core_seal_root.sh)." >&2
    exit 1
fi

tmp="$(mktemp "${OUT}.XXXXXX")"
trap 'rm -f "$tmp"' EXIT HUP INT TERM
emit_header > "$tmp"

if [ -r "$OUT" ] && cmp -s "$tmp" "$OUT"; then
    rm -f "$tmp"
    trap - EXIT HUP INT TERM
    echo "core_seal_root: unchanged ($root)"
    exit 0
fi
mv -f "$tmp" "$OUT"
trap - EXIT HUP INT TERM
echo "core_seal_root: wrote $OUT ($root)"
