# Derive a hot-swap module's sealed-core SECTION declaration from its own
# compile closure. NOT hand-maintained: the inputs are the depfile the module
# compile already writes (-MM) and core/MANIFEST.sha3, so adding an #include of
# a sealed header changes the declaration on the very next build.
#
#   awk -v depfile=<module.d> -f this core/MANIFEST.sha3 > <module>.sections.h
#
# A dependency that is a sealed FILE in the manifest contributes the DEEPEST
# SECTION containing it — never that section's ancestors, whose N-ary node
# digests also cover sibling directories the module never saw.
#
# When the closure touches no sealed file at all the header declares the FULL
# sealed section set. That is the conservative direction (it pins everything);
# declaring nothing is not representable, because admission refuses a module
# that declares zero sections.
BEGIN {
    if (depfile == "") {
        print "hotswap_module_sections: -v depfile=<path> is required" > "/dev/stderr"
        bad = 1
        exit 2
    }
    n = 0
    while ((getline line < depfile) > 0) {
        sub(/\\[ \t]*$/, "", line)
        sub(/^[^:]*:/, "", line)          # drop the "target:" prefix, if present
        cnt = split(line, tok, /[ \t]+/)
        for (i = 1; i <= cnt; i++) {
            p = tok[i]
            if (p == "" || p == "\\") continue
            sub(/^\.\//, "", p)
            deps[p] = 1
        }
    }
    close(depfile)
}
# Per-file line: "<64 hex>  <path>"
/^[0-9a-f][0-9a-f]*[ \t][ \t]/ {
    if (length($1) == 64) {
        idx = index($0, $1)
        rest = substr($0, idx + 64)
        sub(/^[ \t]+/, "", rest)
        sealed[rest] = 1
    }
    next
}
/^SECTION[ \t]/ {
    hex = $4; plen = $3 + 0
    idx = index($0, $4); rest = substr($0, idx + length($4))
    sub(/^[ \t]+/, "", rest)
    sec[substr(rest, 1, plen)] = hex
    next
}
END {
    if (bad) exit 2
    for (p in deps) {
        q = p
        if (cwd != "" && index(q, cwd "/") == 1)
            q = substr(q, length(cwd) + 2)
        if (!(q in sealed)) continue
        slash = 0
        for (k = length(q); k > 0; k--)
            if (substr(q, k, 1) == "/") { slash = k; break }
        if (slash == 0) continue
        dir = substr(q, 1, slash - 1)
        if (!(dir in sec)) continue
        if (!(dir in chosen)) { chosen[dir] = sec[dir]; order[n++] = dir }
    }
    print "/* AUTO-GENERATED by the hotswap-module-so recipe. Do not edit."
    print " * The sealed-core SECTIONs reached by this module's compile closure,"
    print " * derived from its own depfile + core/MANIFEST.sha3. */"
    print "#ifndef ZCL_HOTSWAP_MODULE_SECTION_ROWS"
    if (n == 0) {
        print "/* This module's compile closure reached NO sealed file. Declare the"
        print " * whole sealed set — the conservative direction. */"
        print "#define ZCL_HOTSWAP_MODULE_SECTION_ROWS ZCL_CORE_SEAL_SECTION_ROWS"
        print "#endif"
        exit 0
    }
    # strcmp order, so the emitted table is stable across builds.
    for (i = 0; i < n; i++)
        for (j = i + 1; j < n; j++)
            if (order[j] < order[i]) { t = order[i]; order[i] = order[j]; order[j] = t }
    printf "/* %d of the sealed set's SECTIONs. */\n", n
    print "#define ZCL_HOTSWAP_MODULE_SECTION_ROWS \\"
    for (i = 0; i < n; i++)
        printf "    ZCL_HOTSWAP_SECTION_ROW(\"%s\", \\\n        \"%s\")%s\n",
               order[i], chosen[order[i]], (i + 1 < n) ? " \\" : ""
    print "#endif"
}
