#!/usr/bin/env bash
# Copyright 2026 Rhett Creighton - Apache License 2.0
#
# agent-velocity.sh — what a lane actually cost and produced, computed instead
# of remembered.
#
# ── WHY THIS EXISTS ────────────────────────────────────────────────────────
# The owner asks the same eleven questions of every lane: capability landed,
# unique authored lines, manually touched files, assignment-to-green
# iterations, agent wall-clock, compiler child launches, focused/full test
# time, merge conflicts, verifier-found defects, post-integration fixes. Most
# of them are sitting in git and in the gate receipts. None was computed.
#
# ── THE RULE THIS FILE FOLLOWS ─────────────────────────────────────────────
# Every metric is either DERIVED or printed as an explicit NOT-DERIVABLE line
# naming what the orchestrator must supply. Nothing is silently omitted: a
# missing metric that looks like a zero is worse than a stated gap, because a
# zero gets averaged into a summary and a gap gets asked about.
#
# ── USAGE ──────────────────────────────────────────────────────────────────
#   make agent-velocity BASE=b82b40e77 HEAD=HEAD
#   tools/agent/agent-velocity.sh --base b82b40e77 --head HEAD \
#       --receipts .cache/agent-receipts
#   ... --against main        # merge-conflict surface vs an integration branch
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="$(cd "$SCRIPT_DIR/../.." && pwd)"
# shellcheck source=tools/scripts/sh_str.sh
. "$REPO/tools/scripts/sh_str.sh"
cd "$REPO"

BASE="${BASE:-}"
HEADREF="${HEAD:-HEAD}"
RECEIPTS="${ZCL_RECEIPT_DIR:-$REPO/.cache/agent-receipts}"
AGAINST="main"

die() { echo "agent-velocity: $*" >&2; exit 2; }

while [ "$#" -gt 0 ]; do
    case "$1" in
        --base)     [ "$#" -ge 2 ] || die "--base needs a value"; BASE="$2"; shift 2 ;;
        --head)     [ "$#" -ge 2 ] || die "--head needs a value"; HEADREF="$2"; shift 2 ;;
        --receipts) [ "$#" -ge 2 ] || die "--receipts needs a value"; RECEIPTS="$2"; shift 2 ;;
        --against)  [ "$#" -ge 2 ] || die "--against needs a value"; AGAINST="$2"; shift 2 ;;
        -h|--help)  sed -n '2,30p' "$0"; exit 0 ;;
        *)          die "unknown option '$1'" ;;
    esac
done

if [ -z "$BASE" ]; then
    BASE="$(git merge-base "$HEADREF" "$AGAINST" 2>/dev/null || true)"
    [ -n "$BASE" ] || die "no --base given and no merge-base with '$AGAINST'"
fi
base_sha="$(git rev-parse --verify "$BASE^{commit}" 2>/dev/null || true)"
head_sha="$(git rev-parse --verify "$HEADREF^{commit}" 2>/dev/null || true)"
[ -n "$base_sha" ] || die "--base '$BASE' is not a commit"
[ -n "$head_sha" ] || die "--head '$HEADREF' is not a commit"

echo "velocity_schema=zcl.agent_velocity.v1"
echo "repo_root=$REPO"
echo "base_sha=$base_sha"
echo "head_sha=$head_sha"
echo "range=${base_sha:0:9}..${head_sha:0:9}"
echo "branch=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo UNKNOWN)"

# ── commits ───────────────────────────────────────────────────────────────
echo "commits=$(git rev-list --count "$base_sha..$head_sha")"
echo "commits_merge=$(git rev-list --count --merges "$base_sha..$head_sha")"
if [ -n "$(git status --porcelain 2>/dev/null)" ]; then
    echo "uncommitted_files=$(git status --porcelain | wc -l | tr -d ' ')"
    echo "NOTE=the working tree is DIRTY; everything below describes committed work only"
else
    echo "uncommitted_files=0"
fi

# ── files touched, split hand-authored vs generated ───────────────────────
# "Generated" is not guessed. Source 1 is the repo's OWN declaration —
# .gitattributes `linguist-generated`, read through `git check-attr`, which is
# the same answer GitHub uses. Source 2 is an in-file DO-NOT-EDIT / generated-by
# marker, for the generated .c/.h that carry no attribute. A file matching
# either is generated; everything else counts as hand-authored, which is the
# conservative direction (it can overstate hand-authored work, never
# understate it).
mapfile -t touched < <(git diff --name-only "$base_sha..$head_sha")
echo "files_touched=${#touched[@]}"

is_generated() {
    local f="$1" attr marker
    attr="$(git check-attr linguist-generated -- "$f" 2>/dev/null | sed 's/.*: //')"
    [ "$attr" = "set" ] && return 0
    if git show "$head_sha:$f" >/dev/null 2>&1; then
        marker="$(git show "$head_sha:$f" 2>/dev/null | head -40 \
                  | grep -cE 'GENERATED FILE|Generated by|DO NOT EDIT|generated by' || true)"
        [ "${marker:-0}" -gt 0 ] && return 0
    fi
    return 1
}

hand_files=(); gen_files=()
for f in ${touched[@]+"${touched[@]}"}; do
    if is_generated "$f"; then gen_files+=("$f"); else hand_files+=("$f"); fi
done
echo "files_touched_hand=${#hand_files[@]}"
echo "files_touched_generated=${#gen_files[@]}"

sum_diff() { # <pathspec...> -> "added removed"
    if [ "$#" -eq 0 ]; then echo "0 0"; return; fi
    git diff --numstat -M -C "$base_sha..$head_sha" -- "$@" \
        | awk '{ if ($1 ~ /^[0-9]+$/) a += $1; if ($2 ~ /^[0-9]+$/) r += $2 }
               END { printf "%d %d\n", a + 0, r + 0 }'
}
read -r add_all rem_all <<< "$(sum_diff ${touched[@]+"${touched[@]}"})"
read -r add_hand rem_hand <<< "$(sum_diff ${hand_files[@]+"${hand_files[@]}"})"
read -r add_gen rem_gen <<< "$(sum_diff ${gen_files[@]+"${gen_files[@]}"})"
echo "lines_added=$add_all"
echo "lines_removed=$rem_all"
echo "lines_added_hand=$add_hand"
echo "lines_removed_hand=$rem_hand"
echo "lines_added_generated=$add_gen"
echo "lines_removed_generated=$rem_gen"
# -M -C makes renamed and copied content NOT count as authored lines, which is
# what "unique authored" is meant to exclude. It is still an upper bound: a
# hand-retyped copy of an existing file is indistinguishable from new work.
echo "unique_authored_lines=$add_hand"
echo "unique_authored_lines_basis=git diff --numstat -M -C over hand-authored files (renames/copies excluded; a retyped copy is NOT detectable)"

# ── shared-registry surface (the merge-conflict surface) ──────────────────
# These are the files every lane edits, so two lanes touching one is where
# conflicts come from. The list is by SHAPE, not by name, so a new .def or a
# new lint baseline is covered without editing this script.
REGISTRY_RE='^(Makefile|.*\.mk|tests/harness/src/test_parallel\.c|engine/composition/commands/.*\.def|engine/controllers/include/controllers/diagnostics_dumpers.*\.def|tools/lint/.*baseline.*\.txt|core/MANIFEST\.sha3|docs/DEFENSIVE_CODING\.md|docs/CODEBASE_MAP\.md|CLAUDE\.md|\.gitattributes|\.gitignore)$'
shared=()
for f in ${touched[@]+"${touched[@]}"}; do
    # NOT `printf … | grep -qE …`: grep -q writes nothing, so its exit status
    # IS the decision, and under pipefail a MATCH can surface printf's SIGPIPE
    # 141 instead of grep's 0. (This file had exactly that shape and
    # check-pipefail-status-pipe refused it. A one-path haystack could not
    # actually invert — but that is how the shape survives to be copied
    # somewhere it can.) Keep grep's ERE, take the match as a VALUE.
    hit="$(printf '%s\n' "$f" | grep -E "$REGISTRY_RE" || true)"
    [ -n "$hit" ] && shared+=("$f")
done
echo "shared_registry_files_touched=${#shared[@]}"
for f in ${shared[@]+"${shared[@]}"}; do echo "shared_registry_file=$f"; done

# ── merge-conflict surface against the integration branch ─────────────────
# A real trial merge, not a guess. `git merge-tree --write-tree` reports
# conflicts without touching the worktree, the index, or any branch.
against_sha="$(git rev-parse --verify "$AGAINST^{commit}" 2>/dev/null || true)"
if [ -z "$against_sha" ]; then
    echo "merge_conflicts=NOT-DERIVABLE (no such ref: $AGAINST)"
else
    echo "merge_against=$AGAINST(${against_sha:0:9})"
    mt_out="$(git merge-tree --write-tree --name-only "$head_sha" "$against_sha" 2>/dev/null || true)"
    if [ -z "$mt_out" ]; then
        echo "merge_conflicts=UNKNOWN (git merge-tree produced no output)"
    else
        # Output is: <tree-oid> then, if it did not merge cleanly, the
        # conflicted paths, then an informational block.
        conflicted="$(printf '%s\n' "$mt_out" | tail -n +2 | sed '/^$/,$d')"
        if [ -z "$conflicted" ]; then
            echo "merge_conflicts=0"
        else
            echo "merge_conflicts=$(printf '%s\n' "$conflicted" | wc -l | tr -d ' ')"
            while IFS= read -r c; do
                [ -n "$c" ] && echo "merge_conflict_file=$c"
            done <<< "$conflicted"
        fi
    fi
fi

# ── gate receipts: wall time and iterations to green ──────────────────────
if [ ! -d "$RECEIPTS" ]; then
    echo "gate_receipts=0"
    echo "NOT-DERIVABLE=gate wall-time and pass/fail iterations — no receipt directory at $RECEIPTS. Run gates as: tools/agent/gate-receipt.sh --gate <slug> -- make <slug>"
else
    mapfile -t rfiles < <(ls -1 "$RECEIPTS"/*.receipt 2>/dev/null | sort || true)
    echo "gate_receipts=${#rfiles[@]}"
    if [ "${#rfiles[@]}" -eq 0 ]; then
        echo "NOT-DERIVABLE=gate wall-time and pass/fail iterations — the receipt directory is empty"
    else
        declare -A G_RUNS=() G_FAILS=() G_LASTWALL=() G_TOTWALL=() G_TOTCPU=() G_LASTVERDICT=()
        for r in "${rfiles[@]}"; do
            g="$(sed -n 's/^gate=//p' "$r" | tail -n1)"
            v="$(sed -n 's/^verdict=//p' "$r" | tail -n1)"
            w="$(sed -n 's/^wall_ms=//p' "$r" | tail -n1)"
            c="$(sed -n 's/^child_cpu_ms=//p' "$r" | tail -n1)"
            case "$w" in ''|*[!0-9]*) w=0 ;; esac
            case "$c" in ''|*[!0-9]*) c=0 ;; esac
            [ -n "$g" ] || continue
            G_RUNS["$g"]=$(( ${G_RUNS[$g]:-0} + 1 ))
            [ "$v" = "PASS" ] || G_FAILS["$g"]=$(( ${G_FAILS[$g]:-0} + 1 ))
            G_LASTWALL["$g"]="$w"
            G_LASTVERDICT["$g"]="$v"
            G_TOTWALL["$g"]=$(( ${G_TOTWALL[$g]:-0} + w ))
            G_TOTCPU["$g"]=$(( ${G_TOTCPU[$g]:-0} + c ))
        done
        for g in $(printf '%s\n' "${!G_RUNS[@]}" | sort); do
            echo "gate.$g.runs=${G_RUNS[$g]}"
            echo "gate.$g.failed_runs=${G_FAILS[$g]:-0}"
            echo "gate.$g.iterations_to_green=$( [ "${G_LASTVERDICT[$g]}" = PASS ] && echo "${G_RUNS[$g]}" || echo "NOT-GREEN" )"
            echo "gate.$g.last_wall_ms=${G_LASTWALL[$g]}"
            echo "gate.$g.total_wall_ms=${G_TOTWALL[$g]}"
            echo "gate.$g.total_child_cpu_ms=${G_TOTCPU[$g]}"
        done
        echo "gate_total_wall_ms=$(for g in "${!G_TOTWALL[@]}"; do echo "${G_TOTWALL[$g]}"; done | awk '{s+=$1} END {print s+0}')"
    fi
fi

# ── the honest gaps ───────────────────────────────────────────────────────
# Named, never omitted, and each says what would make it derivable.
echo "NOT-DERIVABLE=capability_landed — a judgement about what the lane is FOR. Orchestrator must state it in one sentence."
echo "NOT-DERIVABLE=agent_wall_clock_s — lives in the dispatcher, not in git. Orchestrator must supply dispatch and return timestamps."
echo "NOT-DERIVABLE=opus_tokens_in/out — API accounting. Orchestrator must supply from its own usage records."
echo "NOT-DERIVABLE=verifier_found_defects — the verifier's report is prose. Orchestrator must supply a count, or run the verifier under gate-receipt.sh so at least its verdict is receipted."
echo "NOT-DERIVABLE=post_integration_fixes — needs the merge commit AND a decision about which later commits are fixes to THIS lane. Re-run with --base <merge-sha> --head <later-sha> once that is known."
echo "NOT-DERIVABLE=compiler_child_launches — not in git and not in a receipt. Would need the build wrapped and \$(CC) counted; \`make -n build-only | grep -c '^cc '\` is the closest cheap proxy and is NOT run here because it costs a Makefile parse."
if [ -d "$RECEIPTS" ] && [ -n "$(ls -1 "$RECEIPTS"/*.receipt 2>/dev/null || true)" ]; then
    :
else
    echo "NOT-DERIVABLE=focused_test_time / full_test_time — derived from receipts named t-fast / test-parallel; none present."
fi
