/* Copyright 2026 Rhett Creighton - Apache License 2.0
 *
 * ACCEPTANCE BAR for dev.agent.queue (tools/command/native_devagent_queue.c).
 *
 * This file is the contract that one single-file unit must satisfy by editing
 * tools/command/native_devagent_queue.c (plus its registration row, type
 * rules, prototype, and catalog entry) and nothing else. It is written
 * against an isolated XDG_STATE_HOME, never against the operator's real
 * state dir, so it proves behavior rather than the state of this machine.
 * Do not edit this file to make the implementation pass.
 *
 * It calls the bound handler DIRECTLY: dev.agent.queue is a dev-lane leaf
 * and an in-process call is exactly what the CLI does after input
 * validation, so the input keys are additionally validated through the real
 * registry. No case here touches the network or a model: post appends a
 * row, next launches a fake harness binary found on PATH, reap reads the
 * fake's receipt, status reads the files. The leaf itself never sleeps and
 * never waits for a run; the bounded poll below is the TEST waiting for an
 * async fake, not the leaf waiting for anything.
 */

#include "test/test_core.h"

#include "command/native_command.h"
#include "config/command_catalog.h"
#include "json/json.h"
#include "kernel/command_registry.h"
#include "platform/state_root.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#if !defined(_WIN32)
#include <errno.h>
#include <fcntl.h>
#include <sys/file.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <unistd.h>
#endif

#define DVX_PATH "dev.agent.queue"

/* ── isolated state root (this group owns its own rig) ─────────────────── */

static char g_dvx_state[1024];
static char g_dvx_saved_xdg[4096];
static bool g_dvx_had_xdg;
static char g_dvx_saved_path[8192];
static char g_dvx_saved_direct[16];
static bool g_dvx_had_direct;
static char g_dvx_saved_ratelimit[16];
static bool g_dvx_had_ratelimit;

static void dvx_isolate(const char *tag)
{
    char base[512];
    test_make_tmpdir(base, sizeof(base), "devagent_queue", tag);
    (void)snprintf(g_dvx_state, sizeof(g_dvx_state), "%s/state", base);
    g_dvx_had_xdg = getenv("XDG_STATE_HOME") != NULL;
    if (g_dvx_had_xdg)
        (void)snprintf(g_dvx_saved_xdg, sizeof(g_dvx_saved_xdg), "%s",
                       getenv("XDG_STATE_HOME"));
    setenv("XDG_STATE_HOME", g_dvx_state, 1);
    /* Direct (double-fork) launches: deterministic under test, no user bus
     * needed. The systemd-run branch is a deployment choice, not a test
     * input. */
    g_dvx_had_direct = getenv("ZCL_QUEUE_DIRECT") != NULL;
    if (g_dvx_had_direct)
        (void)snprintf(g_dvx_saved_direct, sizeof(g_dvx_saved_direct), "%s",
                       getenv("ZCL_QUEUE_DIRECT"));
    setenv("ZCL_QUEUE_DIRECT", "1", 1);
    g_dvx_had_ratelimit = getenv("RATELIMIT") != NULL;
    if (g_dvx_had_ratelimit)
        (void)snprintf(g_dvx_saved_ratelimit, sizeof(g_dvx_saved_ratelimit),
                       "%s", getenv("RATELIMIT"));
    unsetenv("RATELIMIT");
    (void)snprintf(g_dvx_saved_path, sizeof(g_dvx_saved_path), "%s",
                   getenv("PATH") ? getenv("PATH") : "");
}

static void dvx_restore(void)
{
    if (g_dvx_had_xdg)
        setenv("XDG_STATE_HOME", g_dvx_saved_xdg, 1);
    else
        unsetenv("XDG_STATE_HOME");
    if (g_dvx_had_direct)
        setenv("ZCL_QUEUE_DIRECT", g_dvx_saved_direct, 1);
    else
        unsetenv("ZCL_QUEUE_DIRECT");
    if (g_dvx_had_ratelimit)
        setenv("RATELIMIT", g_dvx_saved_ratelimit, 1);
    else
        unsetenv("RATELIMIT");
    setenv("PATH", g_dvx_saved_path, 1);
}

static void dvx_queuedir(char *out, size_t cap)
{
    (void)snprintf(out, cap, "%s/z23/dev/queue", g_dvx_state);
}

/* ── one in-process invocation ─────────────────────────────────────────── */

struct dvx_call {
    struct json_value input;
    struct zcl_command_request request;
    struct zcl_command_reply reply;
};

static void dvx_begin(struct dvx_call *c)
{
    json_init(&c->input);
    json_set_object(&c->input);
    memset(&c->request, 0, sizeof(c->request));
    c->request.input = &c->input;
    c->request.spec =
        zcl_command_registry_find(zcl_command_catalog(), DVX_PATH, NULL);
    zcl_command_reply_init(&c->reply, "zcl.agent_queue.v1");
}

/* Validate through the REAL registry first, so a key the .def never declared
 * is caught here rather than passing in-process and failing from a shell. */
static bool dvx_run(struct dvx_call *c)
{
    char why[256];
    if (c->request.spec &&
        !zcl_command_registry_input_validate(c->request.spec, &c->input, why,
                                             sizeof(why))) {
        printf("[input rejected: %s] ", why);
        return false;
    }
    zcl_native_handle_dev_agent_queue(&c->request, &c->reply);
    return true;
}

static void dvx_end(struct dvx_call *c)
{
    zcl_command_reply_free(&c->reply);
    json_free(&c->input);
}

static bool dvx_ok(const struct dvx_call *c)
{
    return c->reply.status == ZCL_COMMAND_STATUS_PASSED;
}

static const char *dvx_str(const struct dvx_call *c, const char *key)
{
    const struct json_value *v = json_get(&c->reply.data, key);
    return v && v->type == JSON_STR && json_get_str(v) ? json_get_str(v) : "";
}

static int64_t dvx_int(const struct dvx_call *c, const char *key)
{
    const struct json_value *v = json_get(&c->reply.data, key);
    return v && v->type == JSON_INT ? json_get_int(v) : -1;
}

static const struct json_value *dvx_arr(const struct dvx_call *c,
                                        const char *key)
{
    const struct json_value *v = json_get(&c->reply.data, key);
    return v && v->type == JSON_ARR ? v : NULL;
}

static void dvx_post(struct dvx_call *c, const char *kind, const char *name,
                     const char *group, const char *path, const char *brief,
                     const char *model, int64_t attempt)
{
    dvx_begin(c);
    (void)json_push_kv_str(&c->input, "action", "post");
    if (kind)
        (void)json_push_kv_str(&c->input, "kind", kind);
    if (name)
        (void)json_push_kv_str(&c->input, "name", name);
    if (group)
        (void)json_push_kv_str(&c->input, "group", group);
    if (path)
        (void)json_push_kv_str(&c->input, "path", path);
    if (brief)
        (void)json_push_kv_str(&c->input, "brief", brief);
    if (model)
        (void)json_push_kv_str(&c->input, "model", model);
    if (attempt >= 0)
        (void)json_push_kv_int(&c->input, "attempt", attempt);
}

static void dvx_verb(struct dvx_call *c, const char *action, bool json)
{
    dvx_begin(c);
    (void)json_push_kv_str(&c->input, "action", action);
    if (json)
        (void)json_push_kv_bool(&c->input, "json", true);
}

/* Run `status --json` and hand back its pool object, or NULL when the call
 * failed. The caller owns `c` and ends it, so several states can be probed in
 * one TEST without repeating the four lines each probe needs. */
static const struct json_value *dvx_pool_obj(struct dvx_call *c)
{
    dvx_verb(c, "status", true);
    if (!dvx_run(c) || !dvx_ok(c))
        return NULL;
    return json_get(&c->reply.data, "pool");
}

/* ── fixture files (runtime-only, under the isolated state root) ───────── */

static bool dvx_write(const char *path, const char *text)
{
    FILE *f = fopen(path, "wb");
    size_t len;
    bool wrote;
    if (!f)
        return false;
    len = strlen(text);
    wrote = fwrite(text, 1, len, f) == len;
    return fclose(f) == 0 && wrote;
}

static int64_t dvx_queued_count(const char *name)
{
    struct dvx_call c;
    const struct json_value *rows;
    int64_t found = -1;
    dvx_verb(&c, "status", true);
    if (!dvx_run(&c) || !dvx_ok(&c)) {
        dvx_end(&c);
        return -1;
    }
    rows = dvx_arr(&c, "queued");
    if (rows) {
        found = 0;
        for (size_t i = 0; i < rows->num_children; i++) {
            const char *n =
                json_get_str(json_get(&rows->children[i], "name"));
            if (n && name && strcmp(n, name) == 0)
                found++;
        }
    }
    dvx_end(&c);
    return found;
}

static int64_t dvx_queued_attempt(const char *name)
{
    struct dvx_call c;
    const struct json_value *rows;
    int64_t attempt = -1;
    dvx_verb(&c, "status", true);
    if (!dvx_run(&c) || !dvx_ok(&c)) {
        dvx_end(&c);
        return -1;
    }
    rows = dvx_arr(&c, "queued");
    if (rows) {
        for (size_t i = 0; i < rows->num_children; i++) {
            const char *n =
                json_get_str(json_get(&rows->children[i], "name"));
            const struct json_value *a =
                json_get(&rows->children[i], "attempt");
            if (n && name && strcmp(n, name) == 0 && a &&
                a->type == JSON_INT)
                attempt = json_get_int(a);
        }
    }
    dvx_end(&c);
    return attempt;
}

/* A name is one path segment under engine/: a refused name must leave
 * neither a queue row nor any run dir. fopen is the portable existence
 * probe here, so this check works on every host the group runs on. */
static bool dvx_file_absent(const char *path)
{
    FILE *f = fopen(path, "rb");
    if (f)
        (void)fclose(f);
    return f == NULL;
}

#if !defined(_WIN32)
/* A fake zclassic23-engine-unit: parses --state-dir, writes a receipt.json
 * there, and prints lines the reap step reads (rc= plus, in rate-limit
 * mode, a vendor refusal). It runs detached, exactly like the real one. */
static const char k_dvx_fake[] =
    "#!/bin/sh\n"
    "st=\"\"\n"
    "prev=\"\"\n"
    "for a in \"$@\"; do\n"
    "  case \"$a\" in\n"
    "    --state-dir=*) st=\"${a#--state-dir=}\";;\n"
    "    --state-dir) prev=\"want\";;\n"
    "    *) if [ \"$prev\" = \"want\" ]; then st=\"$a\"; prev=\"\"; fi;;\n"
    "  esac\n"
    "done\n"
    "[ -n \"$st\" ] || exit 2\n"
    "printf '%s\\n' \"$@\" > \"$st/argv.log\"\n"
    "if [ \"${RATELIMIT:-0}\" = \"1\" ]; then\n"
    "  printf '{\"verdict\":\"FAIL\",\"tokens\":31,\"wall_ms\":47,"
    "\"reason\":\"refused\"}\\n' "
    "> \"$st/receipt.tmp\"\n"
    "  mv \"$st/receipt.tmp\" \"$st/receipt.json\"\n"
    "  echo \"dispatching $st\"\n"
    "  echo \"response_refused: rate_limited by vendor\"\n"
    "  echo \"rc=1\"\n"
    "else\n"
    "  printf 'queue candidate\\n' > \"$st/candidate.diff\"\n"
    "  printf '{\"verdict\":\"PASS\",\"candidate\":\"candidate.diff\","
    "\"tokens\":17,\"wall_ms\":23}\\n' > \"$st/receipt.tmp\"\n"
    "  mv \"$st/receipt.tmp\" \"$st/receipt.json\"\n"
    "  echo \"dispatching $st\"\n"
    "  echo \"rc=0\"\n"
    "fi\n"
    "exit 0\n";

static bool dvx_fake_on_path(const char *tag, char *bindir, size_t cap)
{
    char base[512], prog[1024], path[9000];
    test_make_tmpdir(base, sizeof(base), "devagent_queue", tag);
    (void)snprintf(bindir, cap, "%s/bin", base);
    (void)snprintf(prog, sizeof(prog), "%s/zclassic23-engine-unit", bindir);
    if (mkdir(bindir, 0700) != 0)
        return false;
    if (!dvx_write(prog, k_dvx_fake))
        return false;
    if (chmod(prog, 0755) != 0)
        return false;
    (void)snprintf(path, sizeof(path), "%s:%s", bindir, g_dvx_saved_path);
    setenv("PATH", path, 1);
    return true;
}

/* One warm pool entry: a directory with .eu-warm, listed in pool.txt.
 * NOTE: tag must differ from every other fixture tag in the same TEST:
 * test_make_tmpdir wipes and recreates its path, so a shared tag deletes
 * a sibling fixture (e.g. the fake harness binary). */
static bool dvx_pool(const char *tag, char *wt, size_t cap)
{
    char base[512], warm[1024], pool[1200], line[1100];
    char qd[1100];
    FILE *f;
    test_make_tmpdir(base, sizeof(base), "devagent_queue", tag);
    (void)snprintf(wt, cap, "%s/wt", base);
    if (mkdir(wt, 0700) != 0)
        return false;
    (void)snprintf(warm, sizeof(warm), "%s/.eu-warm", wt);
    if (!dvx_write(warm, "warm\n"))
        return false;
    (void)snprintf(warm, sizeof(warm), "%s/.eu-lock", wt);
    if (!dvx_write(warm, "")) return false;
    dvx_queuedir(qd, sizeof(qd));
    /* mkdir -p the queue dir: no post has run yet in this state root. */
    {
        char acc[1100];
        size_t i, n = strlen(qd);
        if (n >= sizeof(acc))
            return false;
        for (i = 1; i <= n; i++) {
            if (qd[i] != '/' && qd[i] != '\0')
                continue;
            memcpy(acc, qd, i);
            acc[i] = '\0';
            if (mkdir(acc, 0700) != 0 && errno != EEXIST)
                return false;
        }
    }
    (void)snprintf(pool, sizeof(pool), "%s/pool.txt", qd);
    (void)snprintf(line, sizeof(line), "%s\n", wt);
    f = fopen(pool, "wb");
    if (!f)
        return false;
    if (fwrite(line, 1, strlen(line), f) != strlen(line)) {
        (void)fclose(f);
        return false;
    }
    return fclose(f) == 0;
}

/* The TEST waiting for an async fake: bounded, local, no model involved. */
static bool dvx_poll(const char *path, int tries)
{
    for (int i = 0; i < tries; i++) {
        struct timespec req;
        if (access(path, R_OK) == 0)
            return true;
        req.tv_sec = 0;
        req.tv_nsec = 100000000L;
        (void)nanosleep(&req, NULL);
    }
    return access(path, R_OK) == 0;
}
#endif /* !defined(_WIN32) */

/* The pool-census cases, in their own function so the suite entry stays
 * under the complexity gate. Returns the failure count. */
static int dvx_pool_cases(void)
{
    int failures = 0;
    /* ── the five states a pool can be in, and one reason each ────────────
     *
     * "no free worktree" used to be one word for five different facts, and
     * status reported a fabricated 0 for the one where nothing was measured
     * at all. Each state is asserted here WITH its machine-readable blocked
     * reason, because the counts alone do not discriminate: an unmeasured
     * pool and an empty one both have zero warm entries, and only `known`
     * plus `blocked` tell them apart.
     *
     * The states are asserted as a SET in one test on purpose. A test that
     * checked the absent case alone would still pass if the leaf answered
     * "unmeasured" for a pool it had really measured, which is the opposite
     * defect and just as wrong. */
    TEST("queue: the five pool states each carry their own blocked reason") {
        struct dvx_call c;
        const struct json_value *pool;
        char qd[1100], pl[1200], wt[600], warm[700], lockp[700], line[1400];
        int held;
        dvx_isolate("poolfivestates");
        dvx_queuedir(qd, sizeof(qd));
        ASSERT((size_t)snprintf(pl, sizeof(pl), "%s/pool.txt", qd) <
               sizeof(pl));
        dvx_post(&c, "leaf", "u1", NULL, NULL, NULL, NULL, -1);
        ASSERT(dvx_run(&c));
        ASSERT(dvx_ok(&c));
        dvx_end(&c);

        /* (1) INVENTORY MISSING — unmeasured, every count null, not zero. */
        pool = dvx_pool_obj(&c);
        ASSERT(pool != NULL);
        ASSERT(json_get_bool(json_get(pool, "known")) == false);
        ASSERT(json_is_null(json_get(pool, "total")));
        ASSERT(json_is_null(json_get(pool, "warm")));
        ASSERT(json_is_null(json_get(pool, "free")));
        ASSERT(json_is_null(json_get(pool, "claimed")));
        ASSERT(json_is_null(json_get(pool, "missing")));
        ASSERT(json_is_null(json_get(pool, "not_warm")));
        ASSERT_STR_EQ(json_get_str(json_get(pool, "blocked")),
                      "pool-unmeasured");
        ASSERT(json_get_str(json_get(pool, "reason"))[0] != '\0');
        dvx_end(&c);

        /* (2) VALID INVENTORY, ZERO ENTRIES — measured, and really zero. */
        ASSERT(dvx_write(pl, ""));
        pool = dvx_pool_obj(&c);
        ASSERT(pool != NULL);
        ASSERT(json_get_bool(json_get(pool, "known")) == true);
        ASSERT_EQ(json_get_int(json_get(pool, "total")), 0);
        ASSERT_STR_EQ(json_get_str(json_get(pool, "blocked")), "pool-empty");
        ASSERT_STR_EQ(json_get_str(json_get(pool, "reason")), "");
        dvx_end(&c);

        /* (3) WARM ENTRY AVAILABLE — dispatch is possible, so no reason. */
        ASSERT(dvx_pool("poolfivewt", wt, sizeof(wt)));
        (void)snprintf(lockp, sizeof(lockp), "%s/.eu-lock", wt);
        ASSERT(unlink(lockp) == 0);
        pool = dvx_pool_obj(&c);
        ASSERT(pool != NULL);
        ASSERT(!json_get_bool(json_get(pool, "known")));
        ASSERT_STR_EQ(json_get_str(json_get(pool, "reason")), "pool-lock-unreadable");
        ASSERT(access(lockp, F_OK) != 0 && errno == ENOENT);
        dvx_end(&c);
        ASSERT(dvx_write(lockp, ""));
        pool = dvx_pool_obj(&c);
        ASSERT(pool != NULL);
        ASSERT_EQ(json_get_int(json_get(pool, "total")), 1);
        ASSERT_EQ(json_get_int(json_get(pool, "warm")), 1);
        ASSERT_EQ(json_get_int(json_get(pool, "free")), 1);
        ASSERT_EQ(json_get_int(json_get(pool, "claimed")), 0);
        ASSERT_STR_EQ(json_get_str(json_get(pool, "blocked")), "");
        dvx_end(&c);

        /* (4a) A LISTED ENTRY THAT IS GONE is a stale inventory, counted
         * apart from an unprepared one: the operator's list is wrong, which
         * "not warm" would hide. */
        ASSERT((size_t)snprintf(line, sizeof(line), "%s\n%s/definitely-gone\n",
                                wt, qd) < sizeof(line));
        ASSERT(dvx_write(pl, line));
        pool = dvx_pool_obj(&c);
        ASSERT(pool != NULL);
        ASSERT_EQ(json_get_int(json_get(pool, "total")), 2);
        ASSERT_EQ(json_get_int(json_get(pool, "missing")), 1);
        ASSERT_EQ(json_get_int(json_get(pool, "not_warm")), 0);
        ASSERT_EQ(json_get_int(json_get(pool, "warm")), 1);
        dvx_end(&c);

        /* (4b) A LISTED ENTRY PRESENT BUT NOT WARM — prepared-ness, not a
         * missing directory. Dispatch is impossible with only these. */
        ASSERT((size_t)snprintf(line, sizeof(line), "%s/cold\n", qd) <
               sizeof(line));
        {
            char cold[1200];
            ASSERT((size_t)snprintf(cold, sizeof(cold), "%s/cold", qd) <
                   sizeof(cold));
            ASSERT(mkdir(cold, 0700) == 0);
        }
        ASSERT(dvx_write(pl, line));
        pool = dvx_pool_obj(&c);
        ASSERT(pool != NULL);
        ASSERT_EQ(json_get_int(json_get(pool, "total")), 1);
        ASSERT_EQ(json_get_int(json_get(pool, "not_warm")), 1);
        ASSERT_EQ(json_get_int(json_get(pool, "missing")), 0);
        ASSERT_EQ(json_get_int(json_get(pool, "warm")), 0);
        ASSERT_STR_EQ(json_get_str(json_get(pool, "blocked")),
                      "pool-no-warm-entry");
        dvx_end(&c);

        /* (5) THE LAST WARM ENTRY IS CLAIMED — warm, but taken right now.
         * This is the state that must never read as idle. */
        ASSERT((size_t)snprintf(line, sizeof(line), "%s\n", wt) <
               sizeof(line));
        ASSERT(dvx_write(pl, line));
        ASSERT((size_t)snprintf(lockp, sizeof(lockp), "%s/.eu-lock", wt) <
               sizeof(lockp));
        held = open(lockp, O_RDWR | O_CREAT, 0600);
        ASSERT(held >= 0);
        ASSERT(flock(held, LOCK_EX) == 0);
        pool = dvx_pool_obj(&c);
        ASSERT(pool != NULL);
        ASSERT_EQ(json_get_int(json_get(pool, "warm")), 1);
        ASSERT_EQ(json_get_int(json_get(pool, "free")), 0);
        ASSERT_EQ(json_get_int(json_get(pool, "claimed")), 1);
        ASSERT_STR_EQ(json_get_str(json_get(pool, "blocked")),
                      "pool-all-claimed");
        /* warm == free + claimed lets a reader check the census against
         * itself rather than trusting three independent numbers. */
        ASSERT_EQ(json_get_int(json_get(pool, "warm")),
                  json_get_int(json_get(pool, "free")) +
                      json_get_int(json_get(pool, "claimed")));
        dvx_end(&c);
        (void)flock(held, LOCK_UN);
        (void)close(held);

        /* Releasing the lock returns it to free, so `claimed` tracks the
         * live holder and is not a sticky flag. */
        pool = dvx_pool_obj(&c);
        ASSERT(pool != NULL);
        ASSERT_EQ(json_get_int(json_get(pool, "free")), 1);
        ASSERT_EQ(json_get_int(json_get(pool, "claimed")), 0);
        ASSERT_STR_EQ(json_get_str(json_get(pool, "blocked")), "");
        dvx_end(&c);
        (void)warm;
        dvx_restore();
        PASS();
    }

    /* next's no_free_worktree branch names WHICH of the five it hit, so an
     * operator is never told "no free worktree" about a pool nobody listed. */
    TEST("queue: no_free_worktree names the pool state that blocked it") {
        struct dvx_call c;
        dvx_isolate("poolnextblocked");
        dvx_post(&c, "leaf", "u2", NULL, NULL, NULL, NULL, -1);
        ASSERT(dvx_run(&c));
        ASSERT(dvx_ok(&c));
        dvx_end(&c);
        dvx_verb(&c, "next", false);
        ASSERT(dvx_run(&c));
        ASSERT(dvx_ok(&c));
        ASSERT_STR_EQ(dvx_str(&c, "state"), "no_free_worktree");
        ASSERT(json_get_bool(json_get(&c.reply.data, "pool_known")) == false);
        ASSERT(json_is_null(json_get(&c.reply.data, "pool_total")));
        ASSERT(json_is_null(json_get(&c.reply.data, "pool_warm")));
        ASSERT(json_is_null(json_get(&c.reply.data, "pool_free")));
        ASSERT(json_is_null(json_get(&c.reply.data, "pool_claimed")));
        ASSERT_STR_EQ(dvx_str(&c, "pool_blocked"), "pool-unmeasured");
        ASSERT(dvx_str(&c, "pool_reason")[0] != '\0');
        dvx_end(&c);
        /* The queued row is untouched by a blocked dispatch. */
        ASSERT_EQ(dvx_queued_count("u2"), 1);
        dvx_restore();
        PASS();
    }

    /* TWO SIMULTANEOUS DISPATCH ATTEMPTS, ONE WARM ENTRY. Exactly one may
     * take it. Both children run `next` concurrently against one pool of
     * one; the worktree flock is what decides, so the assertion is on the
     * OUTCOME PAIR — one running, one no_free_worktree — and on the queue
     * holding exactly one row per name afterwards. Two winners would be
     * duplicate ownership of one worktree; two losers would be a lost
     * dispatch. */
    TEST("queue: two concurrent next calls consume one warm entry once") {
        struct dvx_call c;
        char bindir[512], wt[600];
        char path[9000];
        int fds[2];
        pid_t a, b;
        int sa = 0, sb = 0;
        char verdicts[2] = {0, 0};
        dvx_isolate("poolracenext");
        ASSERT(dvx_fake_on_path("poolracebin", bindir, sizeof(bindir)));
        ASSERT(dvx_pool("poolracewt", wt, sizeof(wt)));
        (void)snprintf(path, sizeof(path), "%s:%s", bindir, g_dvx_saved_path);
        setenv("PATH", path, 1);
        dvx_post(&c, "leaf", "race-a", NULL, NULL, NULL, NULL, -1);
        ASSERT(dvx_run(&c));
        ASSERT(dvx_ok(&c));
        dvx_end(&c);
        dvx_post(&c, "leaf", "race-b", NULL, NULL, NULL, NULL, -1);
        ASSERT(dvx_run(&c));
        ASSERT(dvx_ok(&c));
        dvx_end(&c);
        ASSERT(pipe(fds) == 0);
        /* 'r' = this child took the worktree, 'n' = it was refused. */
        a = fork();
        ASSERT(a >= 0);
        if (a == 0) {
            struct dvx_call k;
            char v;
            (void)close(fds[0]);
            dvx_verb(&k, "next", false);
            (void)dvx_run(&k);
            v = dvx_ok(&k) && strcmp(dvx_str(&k, "state"), "running") == 0
                    ? 'r'
                    : 'n';
            (void)write(fds[1], &v, 1);
            _exit(dvx_ok(&k) ? 0 : 1);
        }
        b = fork();
        ASSERT(b >= 0);
        if (b == 0) {
            struct dvx_call k;
            char v;
            (void)close(fds[0]);
            dvx_verb(&k, "next", false);
            (void)dvx_run(&k);
            v = dvx_ok(&k) && strcmp(dvx_str(&k, "state"), "running") == 0
                    ? 'r'
                    : 'n';
            (void)write(fds[1], &v, 1);
            _exit(dvx_ok(&k) ? 0 : 1);
        }
        (void)close(fds[1]);
        while (waitpid(a, &sa, 0) < 0)
            ;
        while (waitpid(b, &sb, 0) < 0)
            ;
        ASSERT(read(fds[0], &verdicts[0], 1) == 1);
        ASSERT(read(fds[0], &verdicts[1], 1) == 1);
        (void)close(fds[0]);
        /* Both calls must SUCCEED as commands; refusal is a state, not an
         * error, so a crash cannot be mistaken for losing the race. */
        ASSERT(WIFEXITED(sa) && WEXITSTATUS(sa) == 0);
        ASSERT(WIFEXITED(sb) && WEXITSTATUS(sb) == 0);
        /* EXACTLY ONE winner. */
        ASSERT_EQ((long long)((verdicts[0] == 'r') + (verdicts[1] == 'r')), 1);
        ASSERT_EQ((long long)((verdicts[0] == 'n') + (verdicts[1] == 'n')), 1);
        /* And no name was doubled: one row each, never two runs of one. */
        ASSERT(dvx_queued_count("race-a") + dvx_queued_count("race-b") <= 2);
        dvx_restore();
        PASS();
    }
_test_next:;
    return failures;
}

/* Historical cost and artifact identity remain separate observations. */
static int dvx_historical_root_case(void)
{
    int failures = 0;
    TEST("queue: historical outcome without artifact roots keeps its cost") {
        struct dvx_call c;
        const struct json_value *rows, *row;
        char qd[1100], outcomes[1200];
        dvx_isolate("historicalroots");
        dvx_post(&c, "leaf", "pending", NULL, NULL, NULL, NULL, -1);
        ASSERT(dvx_run(&c));
        ASSERT(dvx_ok(&c));
        dvx_end(&c);
        dvx_queuedir(qd, sizeof(qd));
        (void)snprintf(outcomes, sizeof(outcomes), "%s/outcomes.jsonl", qd);
        ASSERT(dvx_write(outcomes,
                         "{\"ts\":\"2026-09-25T00:00:00Z\",\"name\":\"legacy\","
                         "\"attempt\":1,\"verdict\":\"FAIL\",\"rc\":1,"
                         "\"tokens_used\":7,\"wall_ms\":11}\n"));
        dvx_verb(&c, "status", true);
        ASSERT(dvx_run(&c));
        ASSERT(dvx_ok(&c));
        rows = dvx_arr(&c, "outcomes");
        ASSERT(rows != NULL && rows->num_children == 1);
        row = &rows->children[0];
        ASSERT(json_get(row, "receipt_sha256") != NULL &&
               json_get(row, "receipt_sha256")->type == JSON_NULL);
        ASSERT(json_get(row, "candidate_sha256") != NULL &&
               json_get(row, "candidate_sha256")->type == JSON_NULL);
        ASSERT(json_get(row, "seq") != NULL &&
               json_get(row, "seq")->type == JSON_NULL);
        ASSERT(json_get(row, "queued_ts") != NULL &&
               json_get(row, "queued_ts")->type == JSON_NULL);
        ASSERT(json_get(row, "started_unix") != NULL &&
               json_get(row, "started_unix")->type == JSON_NULL);
        ASSERT_EQ(json_get_int(json_get(row, "tokens_used")), 7);
        ASSERT_EQ(json_get_int(json_get(row, "wall_ms")), 11);
        dvx_end(&c);
        dvx_restore();
        PASS();
    }
_test_next:;
    dvx_restore();
    return failures;
}

#if !defined(_WIN32)
static int dvx_receipt_root_cases(void)
{
    int failures = 0;
    TEST("queue: ambiguous receipt bytes cannot name candidate bytes") {
        struct dvx_call c, r;
        char bindir[512], wt[512], qd[1100], receipt[1300], path[9000];
        const struct json_value *rows, *row;
        const char *names[] = {"duplicate", "escaped", "overflow",
                               "conflict", "leadingzero", "rawnewline",
                               "verdictunicode"};
        const char *bodies[] = {
            "{\"verdict\":\"PASS\",\"candidate\":\"candidate.diff\","
            "\"candidate\":\"other.diff\",\"tokens\":17}\n",
            "{\"verdict\":\"PASS\",\"candidate\":\"candidate.diff\","
            "\"cand\\u0069date\":\"other.diff\",\"tokens\":17}\n",
            "{\"verdict\":\"PASS\",\"candidate\":\"candidate.diff\","
            "\"tokens\":99999999999999999999999999999999}\n",
            "{\"verdict\":\"PASS\",\"candidate\":\"candidate.diff\","
            "\"tokens\":17,\"tokens_used\":18}\n",
            "{\"verdict\":\"PASS\",\"candidate\":\"candidate.diff\","
            "\"tokens\":01}\n",
            "{\"verdict\":\"PA\nSS\",\"candidate\":\"candidate.diff\"}\n",
            "{\"verdict\":\"P\\u0041SS\",\"candidate\":\"candidate.diff\"}\n"
        };
        dvx_isolate("ambiguous-receipt");
        ASSERT(dvx_fake_on_path("ambiguousbin", bindir, sizeof(bindir)));
        ASSERT(dvx_pool("ambiguouswt", wt, sizeof(wt)));
        (void)snprintf(path, sizeof(path), "%s:%s", bindir, g_dvx_saved_path);
        setenv("PATH", path, 1);
        dvx_queuedir(qd, sizeof(qd));
        for (size_t i = 0; i < sizeof(names) / sizeof(names[0]); i++) {
            dvx_post(&c, "leaf", names[i], NULL, NULL, NULL, NULL, -1);
            ASSERT(dvx_run(&c));
            ASSERT(dvx_ok(&c));
            dvx_end(&c);
            dvx_verb(&c, "next", false);
            ASSERT(dvx_run(&c));
            ASSERT(dvx_ok(&c));
            dvx_end(&c);
            (void)snprintf(receipt, sizeof(receipt),
                           "%s/../engine/%s/a1/receipt.json", qd, names[i]);
            ASSERT(dvx_poll(receipt, 150));
            ASSERT(dvx_write(receipt, bodies[i]));
            dvx_verb(&r, "reap", false);
            ASSERT(dvx_run(&r));
            ASSERT(dvx_ok(&r));
            rows = dvx_arr(&r, "outcomes");
            ASSERT(rows && rows->num_children == 1);
            row = &rows->children[0];
            ASSERT_STR_EQ(json_get_str(json_get(row, "verdict")), "unknown");
            ASSERT(json_get(row, "receipt_sha256")->type == JSON_NULL);
            ASSERT(json_get(row, "candidate_sha256")->type == JSON_NULL);
            dvx_end(&r);
        }
        dvx_restore();
        PASS();
    }

    TEST("queue: escaped worker provenance keeps exact artifact roots") {
        struct dvx_call c, r;
        char bindir[512], wt[512], qd[1100], receipt[1300], path[9000];
        const struct json_value *rows, *row, *root;
        dvx_isolate("escaped-provenance");
        ASSERT(dvx_fake_on_path("provenancebin", bindir, sizeof(bindir)));
        ASSERT(dvx_pool("provenancewt", wt, sizeof(wt)));
        (void)snprintf(path, sizeof(path), "%s:%s", bindir, g_dvx_saved_path);
        setenv("PATH", path, 1);
        dvx_post(&c, "leaf", "provenance", NULL, NULL, NULL, NULL, -1);
        ASSERT(dvx_run(&c));
        ASSERT(dvx_ok(&c));
        dvx_end(&c);
        dvx_verb(&c, "next", false);
        ASSERT(dvx_run(&c));
        ASSERT(dvx_ok(&c));
        dvx_end(&c);
        dvx_queuedir(qd, sizeof(qd));
        (void)snprintf(receipt, sizeof(receipt),
                       "%s/../engine/provenance/a1/receipt.json", qd);
        ASSERT(dvx_poll(receipt, 150));
        ASSERT(dvx_write(receipt,
                         "{\"verdict\":\"PASS\",\"candidate\":\"candidate.diff\","
                         "\"tokens\":17,\"wall_ms\":23,"
                         "\"source\":\"line\\u000d literal \\\\u\"}\n"));
        dvx_verb(&r, "reap", false);
        ASSERT(dvx_run(&r));
        ASSERT(dvx_ok(&r));
        rows = dvx_arr(&r, "outcomes");
        ASSERT(rows && rows->num_children == 1);
        row = &rows->children[0];
        ASSERT_STR_EQ(json_get_str(json_get(row, "verdict")), "PASS");
        root = json_get(row, "receipt_sha256");
        ASSERT(root && root->type == JSON_STR && strlen(root->val.s) == 64);
        ASSERT_STR_EQ(json_get_str(json_get(row, "candidate_sha256")),
                      "57cb3c681d8e20b291dbd7eec190205f7b2dcb2d200017ede904832666bd36b8");
        dvx_end(&r);
        dvx_restore();
        PASS();
    }

    TEST("queue: symlinked attempt directory cannot supply artifact roots") {
        struct dvx_call c, r;
        char bindir[512], wt[512], qd[1100], receipt[1300], attempt[1300];
        char moved[1300], path[9000];
        const struct json_value *rows, *row;
        dvx_isolate("linked-attempt");
        ASSERT(dvx_fake_on_path("linkedbin", bindir, sizeof(bindir)));
        ASSERT(dvx_pool("linkedwt", wt, sizeof(wt)));
        (void)snprintf(path, sizeof(path), "%s:%s", bindir, g_dvx_saved_path);
        setenv("PATH", path, 1);
        dvx_post(&c, "leaf", "linked", NULL, NULL, NULL, NULL, -1);
        ASSERT(dvx_run(&c));
        ASSERT(dvx_ok(&c));
        dvx_end(&c);
        dvx_verb(&c, "next", false);
        ASSERT(dvx_run(&c));
        ASSERT(dvx_ok(&c));
        dvx_end(&c);
        dvx_queuedir(qd, sizeof(qd));
        (void)snprintf(attempt, sizeof(attempt),
                       "%s/../engine/linked/a1", qd);
        (void)snprintf(moved, sizeof(moved),
                       "%s/../engine/linked/a1-moved", qd);
        (void)snprintf(receipt, sizeof(receipt), "%s/receipt.json", attempt);
        ASSERT(dvx_poll(receipt, 150));
        ASSERT(rename(attempt, moved) == 0);
        ASSERT(symlink("a1-moved", attempt) == 0);
        dvx_verb(&r, "reap", false);
        ASSERT(dvx_run(&r));
        ASSERT(dvx_ok(&r));
        rows = dvx_arr(&r, "outcomes");
        ASSERT(rows && rows->num_children == 1);
        row = &rows->children[0];
        ASSERT_STR_EQ(json_get_str(json_get(row, "verdict")), "unknown");
        ASSERT(json_get(row, "receipt_sha256")->type == JSON_NULL);
        ASSERT(json_get(row, "candidate_sha256")->type == JSON_NULL);
        dvx_end(&r);
        dvx_restore();
        PASS();
    }
_test_next:;
    dvx_restore();
    return failures;
}

static int dvx_unresolved_candidate_root_case(void)
{
    int failures = 0;
    TEST("queue: escaped candidate path retains verdict without a false root") {
        struct dvx_call c, r;
        char bindir[512], wt[512], qd[1100], receipt[1300], path[9000];
        const struct json_value *rows, *row, *root;
        dvx_isolate("escaped-candidate");
        ASSERT(dvx_fake_on_path("escapecandbin", bindir, sizeof(bindir)));
        ASSERT(dvx_pool("escapecandwt", wt, sizeof(wt)));
        (void)snprintf(path, sizeof(path), "%s:%s", bindir, g_dvx_saved_path);
        setenv("PATH", path, 1);
        dvx_post(&c, "leaf", "escapecand", NULL, NULL, NULL, NULL, -1);
        ASSERT(dvx_run(&c) && dvx_ok(&c));
        dvx_end(&c);
        dvx_verb(&c, "next", false);
        ASSERT(dvx_run(&c) && dvx_ok(&c));
        dvx_end(&c);
        dvx_queuedir(qd, sizeof(qd));
        (void)snprintf(receipt, sizeof(receipt),
                       "%s/../engine/escapecand/a1/receipt.json", qd);
        ASSERT(dvx_poll(receipt, 150));
        ASSERT(dvx_write(receipt,
                         "{\"verdict\":\"PASS\",\"candidate\":"
                         "\"candidate\\u002ediff\",\"tokens\":17}\n"));
        dvx_verb(&r, "reap", false);
        ASSERT(dvx_run(&r) && dvx_ok(&r));
        rows = dvx_arr(&r, "outcomes");
        ASSERT(rows && rows->num_children == 1);
        row = &rows->children[0];
        ASSERT_STR_EQ(json_get_str(json_get(row, "verdict")), "PASS");
        root = json_get(row, "receipt_sha256");
        ASSERT(root && root->type == JSON_STR && strlen(root->val.s) == 64);
        root = json_get(row, "candidate_sha256");
        ASSERT(root && root->type == JSON_NULL);
        dvx_end(&r);
        dvx_restore();
        PASS();
    }
_test_next:;
    dvx_restore();
    return failures;
}
#endif /* !defined(_WIN32) */

#if !defined(_WIN32)
static int dvx_receipt_cost_cases(void)
{
    int failures = 0;
    TEST("queue: next launches the fake, reap records its PASS") {
        struct dvx_call c, r;
        char bindir[512], wt[512], qd[1100], receipt[1300];
        const struct json_value *rows;
        char path[9000];
        dvx_isolate("launch");
        ASSERT(dvx_fake_on_path("launchbin", bindir, sizeof(bindir)));
        ASSERT(dvx_pool("launchwt", wt, sizeof(wt)));
        (void)snprintf(path, sizeof(path), "%s:%s", bindir,
                       g_dvx_saved_path);
        setenv("PATH", path, 1);
        dvx_post(&c, "leaf", "launched", NULL, NULL, NULL, NULL, -1);
        ASSERT(dvx_run(&c));
        ASSERT(dvx_ok(&c));
        dvx_end(&c);
        dvx_verb(&c, "next", false);
        ASSERT(dvx_run(&c));
        ASSERT(dvx_ok(&c));
        ASSERT_STR_EQ(dvx_str(&c, "state"), "running");
        ASSERT_STR_EQ(dvx_str(&c, "name"), "launched");
        ASSERT_STR_EQ(dvx_str(&c, "worktree"), wt);
        ASSERT(dvx_str(&c, "pid_or_unit")[0] != '\0');
        dvx_end(&c);
        dvx_queuedir(qd, sizeof(qd));
        (void)snprintf(receipt, sizeof(receipt), "%s/../engine/launched/a1/"
                                                 "receipt.json",
                       qd);
        ASSERT(dvx_poll(receipt, 150));
        /* The dispatch pins the shell's argv: group, territory, consent,
         * and a composed task file the run can read. */
        {
            char argvlog[1300], taskfile[1300], argv[4096], task[256];
            FILE *f;
            (void)snprintf(argvlog, sizeof(argvlog),
                           "%s/../engine/launched/a1/argv.log", qd);
            (void)snprintf(taskfile, sizeof(taskfile),
                           "%s/../engine/launched/a1/task.txt", qd);
            f = fopen(argvlog, "r");
            ASSERT(f != NULL);
            if (f) {
                size_t n = fread(argv, 1, sizeof(argv) - 1, f);
                argv[n] = '\0';
                (void)fclose(f);
                ASSERT(strstr(argv, "--yes-dispatch") != NULL);
                ASSERT(strstr(argv, "--group") != NULL);
                ASSERT(strstr(argv, "devagent_launched") != NULL);
                ASSERT(strstr(argv, "--territory") != NULL);
            }
            f = fopen(taskfile, "r");
            ASSERT(f != NULL);
            if (f) {
                size_t n = fread(task, 1, sizeof(task) - 1, f);
                task[n] = '\0';
                (void)fclose(f);
                ASSERT(strstr(task, "kind: fix-gate") != NULL);
            }
        }
        dvx_verb(&r, "reap", false);
        ASSERT(dvx_run(&r));
        ASSERT(dvx_ok(&r));
        rows = dvx_arr(&r, "outcomes");
        ASSERT(rows != NULL);
        ASSERT_EQ((long long)rows->num_children, 1);
        ASSERT_STR_EQ(json_get_str(json_get(&rows->children[0], "name")),
                      "launched");
        ASSERT_STR_EQ(json_get_str(json_get(&rows->children[0], "verdict")),
                      "PASS");
        ASSERT_STR_EQ(json_get_str(json_get(&rows->children[0],
                                            "receipt_sha256")),
                      "e2e65de83072530e02b0a7d58d37a03eb9a075a31ae6f8815d6eaf5fd38e1395");
        ASSERT_STR_EQ(json_get_str(json_get(&rows->children[0],
                                            "candidate_sha256")),
                      "57cb3c681d8e20b291dbd7eec190205f7b2dcb2d200017ede904832666bd36b8");
        ASSERT(json_get_int(json_get(&rows->children[0], "seq")) > 0);
        ASSERT(strlen(json_get_str(json_get(&rows->children[0],
                                             "queued_ts"))) == 20);
        ASSERT(json_get_int(json_get(&rows->children[0],
                                     "started_unix")) > 0);
        ASSERT_EQ(json_get_int(json_get(&rows->children[0], "tokens_used")),
                  17);
        ASSERT_EQ(json_get_int(json_get(&rows->children[0], "wall_ms")), 23);
        dvx_end(&r);
        dvx_verb(&r, "status", true);
        ASSERT(dvx_run(&r));
        ASSERT(dvx_ok(&r));
        rows = dvx_arr(&r, "outcomes");
        ASSERT(rows != NULL && rows->num_children == 1);
        ASSERT_STR_EQ(json_get_str(json_get(&rows->children[0],
                                            "receipt_sha256")),
                      "e2e65de83072530e02b0a7d58d37a03eb9a075a31ae6f8815d6eaf5fd38e1395");
        ASSERT_STR_EQ(json_get_str(json_get(&rows->children[0],
                                            "candidate_sha256")),
                      "57cb3c681d8e20b291dbd7eec190205f7b2dcb2d200017ede904832666bd36b8");
        ASSERT(json_get_int(json_get(&rows->children[0], "seq")) > 0);
        ASSERT(strlen(json_get_str(json_get(&rows->children[0],
                                             "queued_ts"))) == 20);
        ASSERT(json_get_int(json_get(&rows->children[0],
                                     "started_unix")) > 0);
        dvx_end(&r);
        ASSERT_EQ(dvx_queued_count("launched"), 0);
        dvx_restore();
        PASS();
    }

    TEST("queue: a rate-limit run.out requeues with attempt 2") {
        struct dvx_call c, r;
        char bindir[512], wt[512], qd[1100], receipt[1300];
        const struct json_value *rows;
        int64_t found = 0;
        dvx_isolate("ratelimit");
        ASSERT(dvx_fake_on_path("ratelimitbin", bindir, sizeof(bindir)));
        ASSERT(dvx_pool("ratelimitwt", wt, sizeof(wt)));
        {
            char path[9000];
            (void)snprintf(path, sizeof(path), "%s:%s", bindir,
                           g_dvx_saved_path);
            setenv("PATH", path, 1);
        }
        setenv("RATELIMIT", "1", 1);
        dvx_post(&c, "leaf", "throttled", NULL, NULL, NULL, NULL, -1);
        ASSERT(dvx_run(&c));
        ASSERT(dvx_ok(&c));
        dvx_end(&c);
        dvx_verb(&c, "next", false);
        ASSERT(dvx_run(&c));
        ASSERT(dvx_ok(&c));
        ASSERT_STR_EQ(dvx_str(&c, "state"), "running");
        dvx_end(&c);
        unsetenv("RATELIMIT");
        dvx_queuedir(qd, sizeof(qd));
        (void)snprintf(receipt, sizeof(receipt), "%s/../engine/throttled/a1/"
                                                 "receipt.json",
                       qd);
        ASSERT(dvx_poll(receipt, 150));
        dvx_verb(&r, "reap", false);
        ASSERT(dvx_run(&r));
        ASSERT(dvx_ok(&r));
        rows = dvx_arr(&r, "outcomes");
        ASSERT(rows != NULL);
        ASSERT_EQ((long long)rows->num_children, 1);
        ASSERT_STR_EQ(json_get_str(json_get(&rows->children[0], "name")),
                      "throttled");
        ASSERT_STR_EQ(json_get_str(json_get(&rows->children[0],
                                            "receipt_sha256")),
                      "79a20e4be564bfa7862f9bc76bdd8727167b835ca03d2dcd5a3aa189673e5614");
        ASSERT(json_get(&rows->children[0], "candidate_sha256") != NULL &&
               json_get(&rows->children[0], "candidate_sha256")->type ==
                   JSON_NULL);
        ASSERT_EQ(json_get_int(json_get(&rows->children[0], "tokens_used")),
                  31);
        ASSERT_EQ(json_get_int(json_get(&rows->children[0], "wall_ms")), 47);
        for (size_t i = 0; i < rows->num_children; i++) {
            const struct json_value *a =
                json_get(&rows->children[i], "attempt");
            if (a && a->type == JSON_INT && json_get_int(a) == 1)
                found++;
        }
        ASSERT_EQ(found, 1);
        dvx_end(&r);
        dvx_verb(&r, "status", true);
        ASSERT(dvx_run(&r));
        ASSERT(dvx_ok(&r));
        rows = dvx_arr(&r, "outcomes");
        ASSERT(rows != NULL && rows->num_children == 1);
        ASSERT_STR_EQ(json_get_str(json_get(&rows->children[0],
                                            "receipt_sha256")),
                      "79a20e4be564bfa7862f9bc76bdd8727167b835ca03d2dcd5a3aa189673e5614");
        ASSERT(json_get(&rows->children[0], "candidate_sha256") != NULL &&
               json_get(&rows->children[0], "candidate_sha256")->type ==
                   JSON_NULL);
        ASSERT_EQ(json_get_int(json_get(&rows->children[0], "tokens_used")),
                  31);
        ASSERT_EQ(json_get_int(json_get(&rows->children[0], "wall_ms")), 47);
        dvx_end(&r);
        /* The refusal is back in line as attempt 2. */
        ASSERT_EQ(dvx_queued_count("throttled"), 1);
        ASSERT_EQ(dvx_queued_attempt("throttled"), 2);
        dvx_restore();
        PASS();
    }
_test_next:;
    dvx_restore();
    return failures;
}
#endif /* !defined(_WIN32) */


int test_devagent_queue(void);
int test_devagent_queue(void)
{
    int failures = 0;

    TEST("queue: the leaf is registered with its verb and row keys") {
        const struct zcl_command_spec *spec =
            zcl_command_registry_find(zcl_command_catalog(), DVX_PATH, NULL);
        ASSERT(spec != NULL);
        /* A DEV_COMMAND leaf binds its handler only in a dev build (the
         * test binary calls zcl_native_handle_dev_agent_queue directly,
         * exactly as the CLI does after input validation), so only the
         * declared keys are pinned here. */
        ASSERT(spec->input_keys && strstr(spec->input_keys, "action") != NULL);
        ASSERT(spec->input_keys && strstr(spec->input_keys, "kind") != NULL);
        ASSERT(spec->input_keys && strstr(spec->input_keys, "name") != NULL);
        ASSERT(spec->input_keys && strstr(spec->input_keys, "group") != NULL);
        ASSERT(spec->input_keys && strstr(spec->input_keys, "path") != NULL);
        ASSERT(spec->input_keys && strstr(spec->input_keys, "brief") != NULL);
        ASSERT(spec->input_keys && strstr(spec->input_keys, "model") != NULL);
        ASSERT(spec->input_keys && strstr(spec->input_keys, "attempt") != NULL);
        ASSERT(spec->input_keys && strstr(spec->input_keys, "json") != NULL);
        ASSERT(spec->positional_keys &&
               strstr(spec->positional_keys, "action") != NULL);
        PASS();
    }

    TEST("queue: bad posts are refused and store nothing") {
        struct dvx_call c;
        dvx_isolate("refuse");
        /* Unknown verb. */
        dvx_verb(&c, "launch", false);
        ASSERT(dvx_run(&c));
        ASSERT(!dvx_ok(&c));
        dvx_end(&c);
        /* Leaf post without a name. */
        dvx_post(&c, "leaf", NULL, NULL, NULL, NULL, NULL, -1);
        ASSERT(dvx_run(&c));
        ASSERT(!dvx_ok(&c));
        dvx_end(&c);
        /* Unknown kind. */
        dvx_post(&c, "parcel", "n1", NULL, NULL, NULL, NULL, -1);
        ASSERT(dvx_run(&c));
        ASSERT(!dvx_ok(&c));
        dvx_end(&c);
        /* Names outside [A-Za-z0-9_.-]{1,64}. */
        dvx_post(&c, "leaf", "../evil", NULL, NULL, NULL, NULL, -1);
        ASSERT(dvx_run(&c));
        ASSERT(!dvx_ok(&c));
        dvx_end(&c);
        dvx_post(&c, "leaf", "a/b", NULL, NULL, NULL, NULL, -1);
        ASSERT(dvx_run(&c));
        ASSERT(!dvx_ok(&c));
        dvx_end(&c);
        /* A file unit without its group. */
        dvx_post(&c, "file", "n2", NULL, "rel/out.md", NULL, NULL, -1);
        ASSERT(dvx_run(&c));
        ASSERT(!dvx_ok(&c));
        dvx_end(&c);
        /* A doc unit without its brief. */
        dvx_post(&c, "doc", "n3", NULL, "rel/out.md", NULL, NULL, -1);
        ASSERT(dvx_run(&c));
        ASSERT(!dvx_ok(&c));
        dvx_end(&c);
        /* An absolute path is never a unit relpath. */
        dvx_post(&c, "doc", "n4", NULL, "/proc/queue-test/x", NULL, NULL,
                 -1);
        ASSERT(dvx_run(&c));
        ASSERT(!dvx_ok(&c));
        dvx_end(&c);
        ASSERT_EQ(dvx_queued_count("n1"), 0);
        ASSERT_EQ(dvx_queued_count("n2"), 0);
        ASSERT_EQ(dvx_queued_count("n3"), 0);
        ASSERT_EQ(dvx_queued_count("n4"), 0);
        dvx_restore();
        PASS();
    }

    TEST("queue: a name of \"..\" is refused and stores nothing") {
        struct dvx_call c;
        char qd[1100], engine[1200], qf[1200];
        dvx_isolate("dotdotname");
        dvx_post(&c, "leaf", "..", NULL, NULL, NULL, NULL, -1);
        ASSERT(dvx_run(&c));
        ASSERT(!dvx_ok(&c));
        /* The typed error row still carries the leaf, never a bare 500. */
        ASSERT_STR_EQ(dvx_str(&c, "leaf"), DVX_PATH);
        dvx_end(&c);
        /* A ".." name would have resolved one level above engine/: prove
         * nothing was created under the state root at all. */
        dvx_queuedir(qd, sizeof(qd));
        (void)snprintf(engine, sizeof(engine), "%s/../engine", qd);
        (void)snprintf(qf, sizeof(qf), "%s/queue.jsonl", qd);
        ASSERT(dvx_file_absent(qf));
        ASSERT(dvx_file_absent(engine));
        dvx_verb(&c, "status", true);
        ASSERT(dvx_run(&c));
        ASSERT(!dvx_ok(&c));
        ASSERT_STR_EQ(c.reply.error.code, "STATE_DIR_FAILED");
        dvx_end(&c);
        ASSERT(dvx_file_absent(engine));
        ASSERT(platform_state_root(qf, sizeof(qf)));
        ASSERT_EQ(dvx_queued_count(".."), 0);
        ASSERT(dvx_file_absent(engine));
        dvx_restore();
        PASS();
    }

    TEST("queue: a name of \".\" is refused") {
        struct dvx_call c;
        char root[4096];
        dvx_isolate("dotname");
        ASSERT(platform_state_root(root, sizeof(root)));
        dvx_post(&c, "leaf", ".", NULL, NULL, NULL, NULL, -1);
        ASSERT(dvx_run(&c));
        ASSERT(!dvx_ok(&c));
        ASSERT_STR_EQ(dvx_str(&c, "leaf"), DVX_PATH);
        dvx_end(&c);
        ASSERT_EQ(dvx_queued_count("."), 0);
        dvx_restore();
        PASS();
    }

    TEST("queue: dots inside a name are still accepted") {
        struct dvx_call c;
        dvx_isolate("dotsinside");
        dvx_post(&c, "leaf", "a..b", NULL, NULL, NULL, NULL, -1);
        ASSERT(dvx_run(&c));
        ASSERT(dvx_ok(&c));
        ASSERT_STR_EQ(dvx_str(&c, "name"), "a..b");
        ASSERT_STR_EQ(dvx_str(&c, "state"), "queued");
        dvx_end(&c);
        ASSERT_EQ(dvx_queued_count("a..b"), 1);
        dvx_restore();
        PASS();
    }

    TEST("queue: post then status lists it queued") {
        struct dvx_call c;
        const struct json_value *rows;
        dvx_isolate("queued");
        dvx_post(&c, "leaf", "situation", NULL, NULL, NULL, NULL, -1);
        ASSERT(dvx_run(&c));
        ASSERT(dvx_ok(&c));
        ASSERT_STR_EQ(dvx_str(&c, "leaf"), DVX_PATH);
        ASSERT_STR_EQ(dvx_str(&c, "name"), "situation");
        ASSERT_STR_EQ(dvx_str(&c, "state"), "queued");
        ASSERT(dvx_int(&c, "seq") >= 1);
        dvx_end(&c);
        dvx_verb(&c, "status", false);
        ASSERT(dvx_run(&c));
        ASSERT(dvx_ok(&c));
        rows = dvx_arr(&c, "queued");
        ASSERT(rows != NULL);
        ASSERT_EQ((long long)rows->num_children, 1);
        ASSERT_STR_EQ(json_get_str(json_get(&rows->children[0], "name")),
                      "situation");
        ASSERT(dvx_arr(&c, "running") != NULL);
        ASSERT(dvx_arr(&c, "outcomes") != NULL);
        ASSERT(json_get(&c.reply.data, "pool") != NULL);
        ASSERT(dvx_str(&c, "screen")[0] != '\0');
        dvx_end(&c);
        /* The machine shape carries the same keys without the screen. */
        dvx_verb(&c, "status", true);
        ASSERT(dvx_run(&c));
        ASSERT(dvx_ok(&c));
        ASSERT(dvx_arr(&c, "queued") != NULL);
        ASSERT(dvx_str(&c, "screen")[0] == '\0');
        dvx_end(&c);
        dvx_restore();
        PASS();
    }

    failures += dvx_pool_cases();

    TEST("queue: next with no pool returns no_free_worktree, row stays") {
        struct dvx_call c, p;
        dvx_isolate("nopolitely");
        dvx_post(&c, "leaf", "lonely", NULL, NULL, NULL, NULL, -1);
        ASSERT(dvx_run(&c));
        ASSERT(dvx_ok(&c));
        dvx_end(&c);
        /* No pool.txt at all: nothing warm, nothing launched. */
        dvx_verb(&c, "next", false);
        ASSERT(dvx_run(&c));
        ASSERT(dvx_ok(&c));
        ASSERT_STR_EQ(dvx_str(&c, "state"), "no_free_worktree");
        dvx_end(&c);
        ASSERT_EQ(dvx_queued_count("lonely"), 1);
        dvx_verb(&p, "status", true);
        ASSERT(dvx_run(&p));
        ASSERT(dvx_ok(&p));
        ASSERT(dvx_arr(&p, "running") != NULL &&
               dvx_arr(&p, "running")->num_children == 0);
        dvx_end(&p);
        dvx_restore();
        PASS();
    }

    failures += dvx_historical_root_case();

#if !defined(_WIN32)
    failures += dvx_receipt_cost_cases();

    failures += dvx_receipt_root_cases();
    failures += dvx_unresolved_candidate_root_case();

    TEST("queue: the oldest queued row launches first") {
        struct dvx_call c;
        char bindir[512], wt[512];
        char path[9000];
        dvx_isolate("fifo");
        ASSERT(dvx_fake_on_path("fifobin", bindir, sizeof(bindir)));
        ASSERT(dvx_pool("fifowt", wt, sizeof(wt)));
        (void)snprintf(path, sizeof(path), "%s:%s", bindir,
                       g_dvx_saved_path);
        setenv("PATH", path, 1);
        dvx_post(&c, "leaf", "first-a", NULL, NULL, NULL, NULL, -1);
        ASSERT(dvx_run(&c));
        ASSERT(dvx_ok(&c));
        dvx_end(&c);
        dvx_post(&c, "leaf", "first-b", NULL, NULL, NULL, NULL, -1);
        ASSERT(dvx_run(&c));
        ASSERT(dvx_ok(&c));
        dvx_end(&c);
        dvx_verb(&c, "next", false);
        ASSERT(dvx_run(&c));
        ASSERT(dvx_ok(&c));
        ASSERT_STR_EQ(dvx_str(&c, "state"), "running");
        ASSERT_STR_EQ(dvx_str(&c, "name"), "first-a");
        dvx_end(&c);
        ASSERT_EQ(dvx_queued_count("first-a"), 0);
        ASSERT_EQ(dvx_queued_count("first-b"), 1);
        dvx_restore();
        PASS();
    }

    TEST("queue: a busy worktree reads busy, then free") {
        struct dvx_call c;
        char bindir[512], wt[512];
        char path[9000], lockp[1024];
        int held = -1;
        dvx_isolate("busy");
        ASSERT(dvx_fake_on_path("busybin", bindir, sizeof(bindir)));
        ASSERT(dvx_pool("busywty", wt, sizeof(wt)));
        (void)snprintf(path, sizeof(path), "%s:%s", bindir,
                       g_dvx_saved_path);
        setenv("PATH", path, 1);
        /* Hold the worktree lock the way a running unit would. */
        (void)snprintf(lockp, sizeof(lockp), "%s/.eu-lock", wt);
        held = open(lockp, O_RDWR | O_CREAT, 0600);
        ASSERT(held >= 0);
        ASSERT(flock(held, LOCK_EX) == 0);
        dvx_post(&c, "leaf", "waits", NULL, NULL, NULL, NULL, -1);
        ASSERT(dvx_run(&c));
        ASSERT(dvx_ok(&c));
        dvx_end(&c);
        dvx_verb(&c, "next", false);
        ASSERT(dvx_run(&c));
        ASSERT(dvx_ok(&c));
        ASSERT_STR_EQ(dvx_str(&c, "state"), "no_free_worktree");
        dvx_end(&c);
        ASSERT_EQ(dvx_queued_count("waits"), 1);
        (void)flock(held, LOCK_UN);
        (void)close(held);
        dvx_verb(&c, "next", false);
        ASSERT(dvx_run(&c));
        ASSERT(dvx_ok(&c));
        ASSERT_STR_EQ(dvx_str(&c, "state"), "running");
        ASSERT_STR_EQ(dvx_str(&c, "name"), "waits");
        dvx_end(&c);
        dvx_restore();
        PASS();
    }

    TEST("queue: two processes posting at once never interleave rows") {
        char qd[1100], qf[1200];
        pid_t a, b;
        int sa = 0, sb = 0;
        FILE *f;
        char line[8192];
        int nlines = 0;
        dvx_isolate("fork");
        a = fork();
        ASSERT(a >= 0);
        if (a == 0) {
            struct dvx_call c;
            dvx_post(&c, "leaf", "proc-a", NULL, NULL, NULL, NULL, -1);
            (void)dvx_run(&c);
            /* _exit with the handler's verdict: a failure here must fail
             * the parent even though output is captured per process. */
            _exit(dvx_ok(&c) ? 0 : 1);
        }
        b = fork();
        ASSERT(b >= 0);
        if (b == 0) {
            struct dvx_call c;
            dvx_post(&c, "leaf", "proc-b", NULL, NULL, NULL, NULL, -1);
            (void)dvx_run(&c);
            _exit(dvx_ok(&c) ? 0 : 1);
        }
        while (waitpid(a, &sa, 0) < 0)
            ;
        while (waitpid(b, &sb, 0) < 0)
            ;
        ASSERT(WIFEXITED(sa) && WEXITSTATUS(sa) == 0);
        ASSERT(WIFEXITED(sb) && WEXITSTATUS(sb) == 0);
        /* Byte-level proof: every line of the queue is one complete,
         * parseable row. An interleaved write would leave a line that
         * fails to parse or a row split across lines. */
        dvx_queuedir(qd, sizeof(qd));
        (void)snprintf(qf, sizeof(qf), "%s/queue.jsonl", qd);
        f = fopen(qf, "r");
        ASSERT(f != NULL);
        if (f) {
            while (fgets(line, sizeof(line), f)) {
                struct json_value v;
                size_t len = strlen(line);
                while (len > 0 &&
                       (line[len - 1] == '\n' || line[len - 1] == '\r'))
                    line[--len] = '\0';
                if (len == 0)
                    continue;
                nlines++;
                json_init(&v);
                ASSERT(json_read(&v, line, len) && v.type == JSON_OBJ);
                json_free(&v);
            }
            (void)fclose(f);
        }
        ASSERT_EQ((long long)nlines, 2);
        ASSERT_EQ(dvx_queued_count("proc-a"), 1);
        ASSERT_EQ(dvx_queued_count("proc-b"), 1);
        dvx_restore();
        PASS();
    }
#endif /* !defined(_WIN32) */

_test_next:;
    dvx_restore();
    if (failures == 0)
        printf("test_devagent_queue: all passed\n");
    else
        printf("test_devagent_queue: %d FAILED\n", failures);
    return failures;
}
