/* Copyright 2026 Rhett Creighton - Apache License 2.0
 *
 * ACCEPTANCE BAR for dev.ci (tools/command/native_dev_ci_command.c).
 *
 * The one read-only screen over this host's CI and landing state. Every fact
 * it shows is read from dev.land, dev.agent.queue and dev.proof.status called
 * in-process, so these cases build the SIBLINGS' own state under an isolated
 * state root and then assert what the leaf renders from it.
 *
 * The group exists for one property: absent evidence never reads as a pass or
 * as an idle zero. A worker that wrote no claim is unknown, not healthy. A
 * claim older than the staleness threshold is stale, not healthy. A sibling
 * that refused is unknown, not empty. A commit with no receipt reports no
 * receipt, not a verdict. A landing failure whose remote base cannot be
 * resolved emits no retry command rather than a guessed one. And the two
 * mutating views NAME the sibling command without running it: those cases
 * re-read the sibling state afterwards to prove nothing moved.
 *
 * No case touches the network, sleeps, polls, or writes outside its own
 * temporary directory. Do not edit this file to make the implementation pass.
 */

#include "test/test_core.h"

#include "command/native_command.h"
#include "config/command_catalog.h"
#include "json/json.h"
#include "kernel/command_registry.h"
#include "platform/private_directory.h"
#include "platform/os_proc.h"
#include "platform/state_root.h"
#include "platform/time_compat.h"

#include <limits.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#if defined(_WIN32)
#ifndef WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
#endif
#include <windows.h>
#endif

#define DCX_PATH "dev.ci"
#define DCX_SCHEMA "zcl.dev_ci.v1"
#define DCX_BUF 2048

/* Commit ids the fixtures record, plus one nothing ever records. */
#define DCX_TIP "1111111111111111111111111111111111111111"
#define DCX_BASE "2222222222222222222222222222222222222222"
#define DCX_LANDED "3333333333333333333333333333333333333333"
#define DCX_FAILED "4444444444444444444444444444444444444444"
#define DCX_STRANGER "9999999999999999999999999999999999999999"

/* ── isolated state root (this group owns its own rig) ─────────────────── */

static char g_dcx_state[1024];
static char g_dcx_root[1024];
static char g_dcx_checkout[1024];
static bool g_dcx_had_saved;
static bool g_dcx_isolated;
#if defined(_WIN32)
static wchar_t g_dcx_saved[32768];
#else
static char g_dcx_saved[4096];
#endif

static void dcx_fail(const char *context)
{
    fprintf(stderr, "dev_ci fixture: %s\n", context);
    abort();
}

#if defined(_WIN32)
static void dcx_isolate_env(const char *state)
{
    wchar_t wide[1024];
    DWORD length, error;
    g_dcx_saved[0] = L'\0';
    SetLastError(ERROR_SUCCESS);
    length = GetEnvironmentVariableW(L"ZCL_STATE_ROOT", g_dcx_saved, 32768);
    error = GetLastError();
    if (length >= 32768 || (length == 0 && error != ERROR_SUCCESS &&
                            error != ERROR_ENVVAR_NOT_FOUND))
        dcx_fail("could not preserve ZCL_STATE_ROOT");
    g_dcx_had_saved = length > 0 || error == ERROR_SUCCESS;
    if (MultiByteToWideChar(CP_UTF8, MB_ERR_INVALID_CHARS, state, -1, wide,
                            1024) <= 0 ||
        !SetEnvironmentVariableW(L"ZCL_STATE_ROOT", wide))
        dcx_fail("could not isolate ZCL_STATE_ROOT");
}

static void dcx_restore_env(void)
{
    if (!SetEnvironmentVariableW(L"ZCL_STATE_ROOT",
                                 g_dcx_had_saved ? g_dcx_saved : NULL))
        dcx_fail("could not restore ZCL_STATE_ROOT");
}
#else
static void dcx_isolate_env(const char *state)
{
    const char *original = getenv("XDG_STATE_HOME");
    g_dcx_had_saved = original != NULL;
    if (original &&
        (size_t)snprintf(g_dcx_saved, sizeof(g_dcx_saved), "%s", original) >=
            sizeof(g_dcx_saved))
        dcx_fail("could not preserve XDG_STATE_HOME");
    if (setenv("XDG_STATE_HOME", state, 1) != 0)
        dcx_fail("could not isolate XDG_STATE_HOME");
}

static void dcx_restore_env(void)
{
    if (g_dcx_had_saved) {
        if (setenv("XDG_STATE_HOME", g_dcx_saved, 1) != 0)
            dcx_fail("could not restore XDG_STATE_HOME");
    } else if (unsetenv("XDG_STATE_HOME") != 0) {
        dcx_fail("could not clear XDG_STATE_HOME");
    }
}
#endif

static void dcx_isolate(const char *tag)
{
    char base[512];
    if (g_dcx_isolated)
        dcx_fail("previous state root has not been restored");
    test_make_tmpdir(base, sizeof(base), "dev_ci", tag);
    if ((size_t)snprintf(g_dcx_state, sizeof(g_dcx_state), "%s/state", base) >=
            sizeof(g_dcx_state) ||
        (size_t)snprintf(g_dcx_checkout, sizeof(g_dcx_checkout), "%s/checkout",
                         base) >= sizeof(g_dcx_checkout) ||
        !platform_private_directory_ensure(g_dcx_state) ||
        !platform_private_directory_ensure(g_dcx_checkout))
        dcx_fail("could not create the isolated fixture directories");
    dcx_isolate_env(g_dcx_state);
    g_dcx_isolated = true;
    if (!platform_state_root(g_dcx_root, sizeof(g_dcx_root)))
        dcx_fail("could not resolve the isolated state root");
}

static void dcx_restore(void)
{
    if (!g_dcx_isolated)
        return;
    dcx_restore_env();
    g_dcx_isolated = false;
}

/* ── fixture writers (the siblings' own files, never dev.ci's) ─────────── */

static void dcx_join(char *out, size_t cap, const char *a, const char *b)
{
    int n = snprintf(out, cap, "%s/%s", a, b);
    if (n < 0 || (size_t)n >= cap)
        dcx_fail("fixture path does not fit");
}

static void dcx_dir(const char *parent, const char *leaf, char *out,
                    size_t cap)
{
    dcx_join(out, cap, parent, leaf);
    if (!platform_private_directory_ensure(out))
        dcx_fail("could not create a fixture directory");
}

static void dcx_write(const char *path, const char *text)
{
    FILE *f = fopen(path, "wb");
    if (!f)
        dcx_fail("could not open a fixture file");
    if (fputs(text, f) == EOF || fclose(f) != 0)
        dcx_fail("could not write a fixture file");
}

/* Whole small file, or an empty string when it is not there. */
static void dcx_slurp(const char *path, char *out, size_t cap)
{
    FILE *f = fopen(path, "rb");
    size_t n;
    out[0] = '\0';
    if (!f)
        return;
    n = fread(out, 1, cap - 1, f);
    out[n] = '\0';
    (void)fclose(f);
}

static bool dcx_exists(const char *path)
{
    FILE *f = fopen(path, "rb");
    if (!f)
        return false;
    (void)fclose(f);
    return true;
}

static long long dcx_now(void)
{
    return (long long)platform_time_wall_unix();
}

/* One dev.land queue row in exactly the schema dl_parse_row accepts. An
 * empty worktree is the "origin only" case its own parser allows. */
static void dcx_land_row(char *out, size_t cap, long long seq, const char *tip,
                         const char *state, const char *phase,
                         long long started, const char *base)
{
    int n = snprintf(out, cap,
        "{\"seq\":%lld,\"ts\":\"2026-09-19T00:00:00Z\",\"tip\":\"%s\","
        "\"worktree\":\"\",\"note\":\"lane %lld\",\"state\":\"%s\","
        "\"phase\":\"%s\",\"attempt\":1,\"started\":%lld,\"base\":\"%s\","
        "\"local\":\"\",\"tip_pushed\":\"\",\"dimension\":\"\","
        "\"log_path\":\"\",\"detail\":\"\"}\n",
        seq, tip, seq, state, phase, started, base);
    if (n < 0 || (size_t)n >= cap)
        dcx_fail("land row does not fit");
}

static void dcx_seed_land(void)
{
    char dir[DCX_BUF], path[DCX_BUF], queued[DCX_BUF], flight[DCX_BUF];
    char both[DCX_BUF * 2];
    dcx_dir(g_dcx_root, "land", dir, sizeof(dir));
    dcx_land_row(queued, sizeof(queued), 1, DCX_TIP, "queued", "", 0, "");
    dcx_land_row(flight, sizeof(flight), 2, DCX_TIP, "inflight", "prove",
                 dcx_now() - 60, DCX_BASE);
    if ((size_t)snprintf(both, sizeof(both), "%s%s", queued, flight) >=
        sizeof(both))
        dcx_fail("land queue does not fit");
    dcx_join(path, sizeof(path), dir, "queue.jsonl");
    dcx_write(path, both);
    /* Outcomes oldest-first, exactly as dev.land appends them: one landed,
     * then one failed naming its dimension and log. */
    dcx_join(path, sizeof(path), dir, "outcomes.jsonl");
    dcx_write(path,
        "{\"seq\":3,\"ts\":\"2026-09-19T01:00:00Z\",\"tip\":\"" DCX_LANDED
        "\",\"worktree\":\"\",\"note\":\"\",\"state\":\"landed\","
        "\"phase\":\"\",\"attempt\":1,\"started\":0,\"base\":\"\","
        "\"local\":\"\",\"tip_pushed\":\"" DCX_BASE "\",\"dimension\":\"\","
        "\"log_path\":\"\",\"detail\":\"\"}\n"
        "{\"seq\":4,\"ts\":\"2026-09-19T02:00:00Z\",\"tip\":\"" DCX_FAILED
        "\",\"worktree\":\"\",\"note\":\"\",\"state\":\"failed\","
        "\"phase\":\"\",\"attempt\":1,\"started\":0,\"base\":\"\","
        "\"local\":\"\",\"tip_pushed\":\"\",\"dimension\":\"TEST\","
        "\"log_path\":\"/logs/a4.log\",\"detail\":\"gate red\"}\n");
}

/* One dev.agent.queue row in exactly the schema dvq_parse_row accepts. */
static void dcx_unit_row(char *out, size_t cap, long long seq,
                         const char *name, const char *state,
                         long long started, long long owner_pid,
                         long long owner_start)
{
    int n = snprintf(out, cap,
        "{\"seq\":%lld,\"ts\":\"2026-09-19T00:00:00Z\",\"kind\":\"leaf\","
        "\"name\":\"%s\",\"group\":\"\",\"path\":\"\",\"brief\":\"b\","
        "\"model\":\"\",\"attempt\":1,\"state\":\"%s\",\"worktree\":\"\","
        "\"pid_or_unit\":\"\",\"started\":%lld,"
        "\"owner_pid\":%lld,\"owner_start\":%lld}\n",
        seq, name, state, started, owner_pid, owner_start);
    if (n < 0 || (size_t)n >= cap)
        dcx_fail("unit row does not fit");
}

/* with_claim=false writes no claim.json, which is the "a claim that names no
 * worker" case the leaf must report as unknown rather than healthy. */
static void dcx_seed_units_owner(long long running_age_s, bool with_claim,
                                 long long owner_start)
{
    char dir[DCX_BUF], engine[DCX_BUF], path[DCX_BUF];
    char one[DCX_BUF], two[DCX_BUF], both[DCX_BUF * 2];
    dcx_dir(g_dcx_root, "queue", dir, sizeof(dir));
    dcx_dir(g_dcx_root, "engine", engine, sizeof(engine));
    uint64_t pid = os_proc_current_pid();
    if (pid > (uint64_t)LLONG_MAX)
        dcx_fail("owner PID does not fit");
    dcx_unit_row(one, sizeof(one), 1, "unit-alpha", "queued", 0, 0, 0);
    dcx_unit_row(two, sizeof(two), 2, "unit-bravo", "running",
                 dcx_now() - running_age_s, (long long)pid, owner_start);
    if ((size_t)snprintf(both, sizeof(both), "%s%s", one, two) >= sizeof(both))
        dcx_fail("unit queue does not fit");
    dcx_join(path, sizeof(path), dir, "queue.jsonl");
    dcx_write(path, both);
    dcx_join(path, sizeof(path), dir, "outcomes.jsonl");
    dcx_write(path,
        "{\"seq\":1,\"ts\":\"2026-09-19T01:00:00Z\",\"name\":\"unit-alpha\","
        "\"attempt\":1,\"verdict\":\"pass\",\"rc\":0}\n"
        "{\"seq\":2,\"ts\":\"2026-09-19T02:00:00Z\",\"name\":\"unit-bravo\","
        "\"attempt\":1,\"verdict\":\"gate-refused\",\"rc\":1}\n");
    if (!with_claim)
        return;
    dcx_dir(engine, "unit-bravo", one, sizeof(one));
    dcx_dir(one, "a1", two, sizeof(two));
    dcx_join(path, sizeof(path), two, "claim.json");
    dcx_write(path, "{\"worker\":\"worker-1\",\"submitted\":true}\n");
}

static void dcx_seed_units(long long running_age_s, bool with_claim)
{
    uint64_t token = 0;
    if (!os_proc_pid_start_token(os_proc_current_pid(), &token) ||
        token > (uint64_t)LLONG_MAX)
        dcx_fail("owner start token unavailable");
    dcx_seed_units_owner(running_age_s, with_claim, (long long)token);
}

/* The proof cache's own receipt directory. The bytes never matter here: this
 * fixture proves DISCOVERY by name, and the verdict still comes from
 * dev.proof.status. */
static void dcx_seed_receipt(const char *local, const char *base)
{
    char cache[DCX_BUF], proof[DCX_BUF], receipts[DCX_BUF], path[DCX_BUF];
    char name[128];
    dcx_dir(g_dcx_checkout, ".cache", cache, sizeof(cache));
    dcx_dir(cache, "zcl-dev-proof", proof, sizeof(proof));
    dcx_dir(proof, "receipts", receipts, sizeof(receipts));
    if ((size_t)snprintf(name, sizeof(name), "%s-%s.receipt", local, base) >=
        sizeof(name))
        dcx_fail("receipt name does not fit");
    dcx_join(path, sizeof(path), receipts, name);
    dcx_write(path, "not-a-real-receipt");
}

/* ── the leaf under test ─────────────────────────────────────────────── */

struct dcx_call {
    struct json_value input;
    struct zcl_command_request request;
    struct zcl_command_reply reply;
};

static void dcx_begin(struct dcx_call *c, const char *input_json)
{
    json_init(&c->input);
    json_set_object(&c->input);
    if (input_json && !json_read(&c->input, input_json, strlen(input_json)))
        dcx_fail("fixture input does not parse");
    memset(&c->request, 0, sizeof(c->request));
    c->request.input = &c->input;
    c->request.spec =
        zcl_command_registry_find(zcl_command_catalog(), DCX_PATH, NULL);
    c->request.view = "normal";
    zcl_command_reply_init(&c->reply, DCX_SCHEMA);
}

static bool dcx_run(struct dcx_call *c)
{
    char why[256];
    if (c->request.spec &&
        !zcl_command_registry_input_validate(c->request.spec, &c->input, why,
                                             sizeof(why))) {
        printf("[input rejected: %s] ", why);
        return false;
    }
    zcl_native_handle_dev_ci(&c->request, &c->reply);
    return true;
}

static void dcx_end(struct dcx_call *c)
{
    zcl_command_reply_free(&c->reply);
    json_free(&c->input);
}

static bool dcx_ok(const struct dcx_call *c)
{
    return c->reply.status == ZCL_COMMAND_STATUS_PASSED;
}

static const char *dcx_str(const struct json_value *obj, const char *key)
{
    const struct json_value *v = obj ? json_get(obj, key) : NULL;
    return (v && v->type == JSON_STR) ? json_get_str(v) : "";
}

static long long dcx_int(const struct json_value *obj, const char *key)
{
    const struct json_value *v = obj ? json_get(obj, key) : NULL;
    return (v && v->type == JSON_INT) ? (long long)json_get_int(v) : -1;
}

static bool dcx_bool(const struct json_value *obj, const char *key)
{
    const struct json_value *v = obj ? json_get(obj, key) : NULL;
    return v && v->type == JSON_BOOL && json_get_bool(v);
}

static const struct json_value *dcx_arr(const struct dcx_call *c,
                                        const char *key)
{
    const struct json_value *v = json_get(&c->reply.data, key);
    return (v && v->type == JSON_ARR) ? v : NULL;
}

static const struct json_value *dcx_obj(const struct dcx_call *c,
                                        const char *key)
{
    const struct json_value *v = json_get(&c->reply.data, key);
    return (v && v->type == JSON_OBJ) ? v : NULL;
}

static const char *dcx_screen(const struct dcx_call *c)
{
    return dcx_str(&c->reply.data, "screen");
}

/* True when any row of an array has `key` equal to `want`. */
static bool dcx_any(const struct json_value *arr, const char *key,
                    const char *want)
{
    size_t n = arr ? json_size(arr) : 0;
    for (size_t i = 0; i < n; i++) {
        if (strcmp(dcx_str(json_at(arr, i), key), want) == 0)
            return true;
    }
    return false;
}

/* Whether the named sibling is recorded as having answered. */
static bool dcx_answered(const struct dcx_call *c, const char *leaf)
{
    const struct json_value *arr = dcx_arr(c, "sources");
    size_t n = arr ? json_size(arr) : 0;
    for (size_t i = 0; i < n; i++) {
        const struct json_value *row = json_at(arr, i);
        if (strcmp(dcx_str(row, "leaf"), leaf) == 0)
            return dcx_bool(row, "answered");
    }
    return false;
}

/* ── the nine views ──────────────────────────────────────────────────── */

static int dcx_t_registered(void)
{
    int failures = 0;

    TEST("ci: the leaf is registered as a read with its declared keys") {
        const struct zcl_command_spec *spec =
            zcl_command_registry_find(zcl_command_catalog(), DCX_PATH, NULL);
        ASSERT(spec != NULL);
        ASSERT(spec->effect == ZCL_COMMAND_EFFECT_READ);
        ASSERT(spec->risk == ZCL_COMMAND_RISK_READ);
        ASSERT(spec->input_keys && strstr(spec->input_keys, "topic") != NULL);
        /* `view` is the kernel projection key; this leaf must not claim it. */
        ASSERT(strstr(spec->input_keys, "view") == NULL);
        ASSERT(strstr(spec->input_keys, "sha") != NULL);
        ASSERT(strstr(spec->input_keys, "root") != NULL);
        ASSERT(strstr(spec->input_keys, "json") != NULL);
        ASSERT(spec->positional_keys &&
               strcmp(spec->positional_keys, "topic") == 0);
        ASSERT(spec->output_schema &&
               strcmp(spec->output_schema, DCX_SCHEMA) == 0);
        PASS();
    }

_test_next:;
    return failures;
}

static int dcx_t_status(void)
{
    int failures = 0;

    TEST("ci: status composes both siblings and names every view") {
        struct dcx_call c;
        dcx_isolate("status");
        dcx_seed_land();
        dcx_seed_units(30, true);
        dcx_begin(&c, "{}");
        ASSERT(dcx_run(&c));
        ASSERT(dcx_ok(&c));
        ASSERT(strcmp(dcx_str(&c.reply.data, "leaf"), "dev.ci") == 0);
        ASSERT(strcmp(dcx_str(&c.reply.data, "view"), "status") == 0);
        ASSERT(dcx_answered(&c, "dev.land"));
        ASSERT(dcx_answered(&c, "dev.agent.queue"));
        ASSERT(dcx_int(&c.reply.data, "land_queued") == 1);
        ASSERT(dcx_bool(&c.reply.data, "land_in_flight"));
        ASSERT(dcx_int(&c.reply.data, "unit_queued") == 1);
        ASSERT(dcx_int(&c.reply.data, "unit_running") == 1);
        /* The screen is the operator's actual answer, and it advertises the
         * other eight views so one command really is enough. */
        ASSERT(strstr(dcx_screen(&c), "1 in flight") != NULL);
        ASSERT(strstr(dcx_screen(&c), "last_pass") != NULL);
        ASSERT(strstr(dcx_screen(&c), "receipt") != NULL);
        dcx_end(&c);
        PASS();
    }

_test_next:;
    dcx_restore();
    return failures;
}

static int dcx_t_queue(void)
{
    int failures = 0;

    TEST("ci: queue lists both waiting queues from their owners") {
        struct dcx_call c;
        dcx_isolate("queue");
        dcx_seed_land();
        dcx_seed_units(30, true);
        dcx_begin(&c, "{\"topic\":\"queue\"}");
        ASSERT(dcx_run(&c));
        ASSERT(dcx_ok(&c));
        ASSERT(dcx_arr(&c, "land_queued") != NULL);
        ASSERT(json_size(dcx_arr(&c, "land_queued")) == 1);
        ASSERT(dcx_any(dcx_arr(&c, "land_queued"), "tip", DCX_TIP));
        ASSERT(dcx_any(dcx_arr(&c, "unit_queued"), "name", "unit-alpha"));
        /* A running unit is not a waiting one. */
        ASSERT(!dcx_any(dcx_arr(&c, "unit_queued"), "name", "unit-bravo"));
        dcx_end(&c);
        PASS();
    }

_test_next:;
    dcx_restore();
    return failures;
}

static int dcx_t_jobs(void)
{
    int failures = 0;

    TEST("ci: jobs shows the in-flight landing and the running units") {
        struct dcx_call c;
        dcx_isolate("jobs");
        dcx_seed_land();
        dcx_seed_units(30, true);
        dcx_begin(&c, "{\"topic\":\"jobs\"}");
        ASSERT(dcx_run(&c));
        ASSERT(dcx_ok(&c));
        ASSERT(dcx_obj(&c, "land_in_flight") != NULL);
        ASSERT(strcmp(dcx_str(dcx_obj(&c, "land_in_flight"), "phase"),
                      "prove") == 0);
        ASSERT(dcx_any(dcx_arr(&c, "unit_running"), "name", "unit-bravo"));
        ASSERT(strstr(dcx_screen(&c), "worker-1") != NULL);
        dcx_end(&c);
        PASS();
    }

_test_next:;
    dcx_restore();
    return failures;
}

static int dcx_t_last_pass(void)
{
    int failures = 0;

    TEST("ci: last_pass names the landed tip and the passing unit") {
        struct dcx_call c;
        dcx_isolate("last_pass");
        dcx_seed_land();
        dcx_seed_units(30, true);
        dcx_begin(&c, "{\"topic\":\"last_pass\"}");
        ASSERT(dcx_run(&c));
        ASSERT(dcx_ok(&c));
        ASSERT(dcx_obj(&c, "land") != NULL);
        ASSERT(strcmp(dcx_str(dcx_obj(&c, "land"), "tip"), DCX_LANDED) == 0);
        ASSERT(strcmp(dcx_str(dcx_obj(&c, "land"), "state"), "landed") == 0);
        ASSERT(strcmp(dcx_str(dcx_obj(&c, "unit"), "name"), "unit-alpha") == 0);
        dcx_end(&c);
        PASS();
    }

_test_next:;
    dcx_restore();
    return failures;
}

static int dcx_t_last_fail(void)
{
    int failures = 0;

    TEST("ci: last_fail names the failing dimension and its log") {
        struct dcx_call c;
        dcx_isolate("last_fail");
        dcx_seed_land();
        dcx_seed_units(30, true);
        dcx_begin(&c, "{\"topic\":\"last_fail\"}");
        ASSERT(dcx_run(&c));
        ASSERT(dcx_ok(&c));
        ASSERT(strcmp(dcx_str(dcx_obj(&c, "land"), "tip"), DCX_FAILED) == 0);
        ASSERT(strcmp(dcx_str(dcx_obj(&c, "land"), "dimension"), "TEST") == 0);
        ASSERT(strcmp(dcx_str(dcx_obj(&c, "land"), "log_path"),
                      "/logs/a4.log") == 0);
        ASSERT(strcmp(dcx_str(dcx_obj(&c, "unit"), "name"), "unit-bravo") == 0);
        ASSERT(strstr(dcx_screen(&c), "/logs/a4.log") != NULL);
        dcx_end(&c);
        PASS();
    }

_test_next:;
    dcx_restore();
    return failures;
}

/* ── worker health: the fail-closed core ─────────────────────────────── */

static int dcx_t_worker_active(void)
{
    int failures = 0;

    TEST("ci: a fresh named claim is the only thing that reads executing") {
        struct dcx_call c;
        const struct json_value *w;
        dcx_isolate("worker_active");
        dcx_seed_land();
        dcx_seed_units(30, true);
        dcx_begin(&c, "{\"topic\":\"worker\"}");
        ASSERT(dcx_run(&c));
        ASSERT(dcx_ok(&c));
        w = dcx_obj(&c, "worker");
        ASSERT(w != NULL);
        ASSERT(strcmp(dcx_str(w, "state"), "executing") == 0);
        ASSERT(dcx_bool(w, "measured"));
        ASSERT(dcx_int(w, "claims") == 1);
        ASSERT(dcx_int(w, "named_claims") == 1);
        ASSERT(dcx_int(w, "live_claims") == 1);
        ASSERT(dcx_int(w, "dead_claims") == 0);
        ASSERT(dcx_int(w, "stale_claims") == 0);
        dcx_end(&c);
        PASS();
    }

_test_next:;
    dcx_restore();
    return failures;
}

static int dcx_t_worker_owner_reused(void)
{
    int failures = 0;

    TEST("ci: a reused owner PID leaves the fresh claim blocked") {
        struct dcx_call c;
        const struct json_value *w;
        uint64_t token = 0;
        dcx_isolate("worker_owner_reused");
        dcx_seed_land();
        ASSERT(os_proc_pid_start_token(os_proc_current_pid(), &token));
        ASSERT(token < (uint64_t)LLONG_MAX);
        dcx_seed_units_owner(30, true, (long long)(token + 1));
        dcx_begin(&c, "{\"topic\":\"worker\"}");
        ASSERT(dcx_run(&c));
        ASSERT(dcx_ok(&c));
        w = dcx_obj(&c, "worker");
        ASSERT(strcmp(dcx_str(w, "state"), "blocked") == 0);
        ASSERT(strcmp(dcx_str(w, "reason"),
                      "owner_exited_before_reap") == 0);
        ASSERT(dcx_int(w, "dead_claims") == 1);
        dcx_end(&c);
        PASS();
    }

_test_next:;
    dcx_restore();
    return failures;
}

static int dcx_t_worker_owner_unverified(void)
{
    int failures = 0;

    TEST("ci: a named claim without a birth token is unknown") {
        struct dcx_call c;
        const struct json_value *w;
        dcx_isolate("worker_owner_unverified");
        dcx_seed_land();
        dcx_seed_units_owner(30, true, 0);
        dcx_begin(&c, "{\"topic\":\"worker\"}");
        ASSERT(dcx_run(&c));
        ASSERT(dcx_ok(&c));
        w = dcx_obj(&c, "worker");
        ASSERT(strcmp(dcx_str(w, "state"), "unknown") == 0);
        ASSERT(strcmp(dcx_str(w, "reason"),
                      "owner_liveness_unverified") == 0);
        ASSERT(dcx_int(w, "unverified_claims") == 1);
        dcx_end(&c);
        PASS();
    }

_test_next:;
    dcx_restore();
    return failures;
}

static int dcx_t_worker_stale(void)
{
    int failures = 0;

    TEST("ci: a claim older than the threshold reads stale, never healthy") {
        struct dcx_call c;
        const struct json_value *w;
        dcx_isolate("worker_stale");
        dcx_seed_land();
        dcx_seed_units(7200, true);
        dcx_begin(&c, "{\"topic\":\"worker\"}");
        ASSERT(dcx_run(&c));
        ASSERT(dcx_ok(&c));
        w = dcx_obj(&c, "worker");
        ASSERT(strcmp(dcx_str(w, "state"), "stale") == 0);
        ASSERT(strcmp(dcx_str(w, "state"), "active") != 0);
        ASSERT(dcx_int(w, "stale_claims") == 1);
        ASSERT(dcx_int(w, "oldest_claim_s") >= 7200);
        dcx_end(&c);
        PASS();
    }

_test_next:;
    dcx_restore();
    return failures;
}

static int dcx_t_worker_unnamed(void)
{
    int failures = 0;

    TEST("ci: a claim naming no worker reads unknown, never healthy") {
        struct dcx_call c;
        const struct json_value *w;
        dcx_isolate("worker_unnamed");
        dcx_seed_land();
        dcx_seed_units(30, false);
        dcx_begin(&c, "{\"topic\":\"worker\"}");
        ASSERT(dcx_run(&c));
        ASSERT(dcx_ok(&c));
        w = dcx_obj(&c, "worker");
        ASSERT(strcmp(dcx_str(w, "state"), "unknown") == 0);
        ASSERT(strcmp(dcx_str(w, "reason"), "claim_names_no_worker") == 0);
        ASSERT(dcx_int(w, "claims") == 1);
        ASSERT(dcx_int(w, "named_claims") == 0);
        dcx_end(&c);
        PASS();
    }

_test_next:;
    dcx_restore();
    return failures;
}

static int dcx_t_worker_no_claim(void)
{
    int failures = 0;

    TEST("ci: no claim at all is unknown, not an idle healthy worker") {
        struct dcx_call c;
        const struct json_value *w;
        dcx_isolate("worker_no_claim");
        dcx_seed_land();
        dcx_begin(&c, "{\"topic\":\"worker\"}");
        ASSERT(dcx_run(&c));
        ASSERT(dcx_ok(&c));
        w = dcx_obj(&c, "worker");
        ASSERT(strcmp(dcx_str(w, "state"), "unknown") == 0);
        ASSERT(strcmp(dcx_str(w, "reason"), "no_worker_claim_observed") == 0);
        /* The queue itself DID answer, so the zero is a measured number. */
        ASSERT(dcx_bool(w, "measured"));
        ASSERT(dcx_int(w, "claims") == 0);
        dcx_end(&c);
        PASS();
    }

_test_next:;
    dcx_restore();
    return failures;
}

static int dcx_t_worker_unmeasured(void)
{
    int failures = 0;

    TEST("ci: an unreadable queue reports unknown with no counts at all") {
        struct dcx_call c;
        const struct json_value *w;
        char path[DCX_BUF];
        dcx_isolate("worker_unmeasured");
        dcx_seed_land();
        /* A regular file where the queue directory belongs: dev.agent.queue
         * refuses, so nothing about a worker was measured here. */
        dcx_join(path, sizeof(path), g_dcx_root, "queue");
        dcx_write(path, "not a directory\n");
        dcx_begin(&c, "{\"topic\":\"worker\"}");
        ASSERT(dcx_run(&c));
        ASSERT(dcx_ok(&c));
        ASSERT(!dcx_answered(&c, "dev.agent.queue"));
        w = dcx_obj(&c, "worker");
        ASSERT(strcmp(dcx_str(w, "state"), "unknown") == 0);
        ASSERT(strcmp(dcx_str(w, "reason"),
                      "dev.agent.queue_unreadable") == 0);
        ASSERT(!dcx_bool(w, "measured"));
        /* Never a zero that reads like an idle host. */
        ASSERT(json_get(w, "claims") == NULL);
        ASSERT(json_get(w, "named_claims") == NULL);
        ASSERT(strstr(dcx_screen(&c), "unknown") != NULL);
        dcx_end(&c);
        PASS();
    }

_test_next:;
    dcx_restore();
    return failures;
}

static int dcx_t_land_unreadable(void)
{
    int failures = 0;

    TEST("ci: an unreadable landing queue is unknown, never an empty queue") {
        struct dcx_call c;
        char path[DCX_BUF];
        dcx_isolate("land_unreadable");
        dcx_join(path, sizeof(path), g_dcx_root, "land");
        dcx_write(path, "not a directory\n");
        dcx_seed_units(30, true);
        dcx_begin(&c, "{\"topic\":\"status\"}");
        ASSERT(dcx_run(&c));
        ASSERT(dcx_ok(&c));
        ASSERT(!dcx_answered(&c, "dev.land"));
        ASSERT(strcmp(dcx_str(&c.reply.data, "land"), "unknown") == 0);
        ASSERT(json_get(&c.reply.data, "land_queued") == NULL);
        ASSERT(strstr(dcx_screen(&c), "land: UNKNOWN") != NULL);
        dcx_end(&c);
        PASS();
    }

_test_next:;
    dcx_restore();
    return failures;
}

/* ── receipt for a SHA ───────────────────────────────────────────────── */

static int dcx_t_receipt_found(void)
{
    int failures = 0;

    TEST("ci: a commit prefix resolves its base and asks proof for a verdict") {
        struct dcx_call c;
        const struct json_value *row;
        char input[DCX_BUF];
        dcx_isolate("receipt_found");
        dcx_seed_land();
        dcx_seed_receipt(DCX_FAILED, DCX_BASE);
        if ((size_t)snprintf(input, sizeof(input),
                "{\"topic\":\"receipt\",\"sha\":\"4444444\",\"root\":\"%s\"}",
                g_dcx_checkout) >= sizeof(input))
            dcx_fail("receipt input does not fit");
        dcx_begin(&c, input);
        ASSERT(dcx_run(&c));
        ASSERT(dcx_ok(&c));
        ASSERT(dcx_int(&c.reply.data, "found") == 1);
        row = json_at(dcx_arr(&c, "receipts"), 0);
        ASSERT(strcmp(dcx_str(row, "local_commit"), DCX_FAILED) == 0);
        ASSERT(strcmp(dcx_str(row, "remote_base"), DCX_BASE) == 0);
        ASSERT(strcmp(dcx_str(row, "found_via"), "receipt_cache") == 0);
        /* The verdict is dev.proof.status's word, never this leaf's. A
         * fixture receipt is not a pass under any circumstance. */
        ASSERT(strcmp(dcx_str(row, "verdict"), "passed") != 0);
        /* And the exact retry command for that exact pair is named. */
        ASSERT(strstr(dcx_str(row, "retry_command"),
                      "dev proof retry --local_commit=" DCX_FAILED) != NULL);
        ASSERT(strstr(dcx_str(row, "retry_command"),
                      "--remote_base=" DCX_BASE) != NULL);
        dcx_end(&c);
        PASS();
    }

_test_next:;
    dcx_restore();
    return failures;
}

static int dcx_t_receipt_unknown(void)
{
    int failures = 0;

    TEST("ci: a commit with no receipt reports no receipt, never a pass") {
        struct dcx_call c;
        char input[DCX_BUF];
        dcx_isolate("receipt_unknown");
        dcx_seed_land();
        dcx_seed_receipt(DCX_FAILED, DCX_BASE);
        if ((size_t)snprintf(input, sizeof(input),
                "{\"topic\":\"receipt\",\"sha\":\"" DCX_STRANGER
                "\",\"root\":\"%s\"}", g_dcx_checkout) >= sizeof(input))
            dcx_fail("receipt input does not fit");
        dcx_begin(&c, input);
        ASSERT(dcx_run(&c));
        ASSERT(dcx_ok(&c));
        ASSERT(dcx_int(&c.reply.data, "found") == 0);
        ASSERT(json_size(dcx_arr(&c, "receipts")) == 0);
        ASSERT(strcmp(dcx_str(&c.reply.data, "reason"),
                      "no_receipt_for_commit") == 0);
        ASSERT(strstr(dcx_screen(&c), "UNKNOWN") != NULL);
        ASSERT(strstr(dcx_screen(&c), "pass") == NULL);
        dcx_end(&c);
        PASS();
    }

_test_next:;
    dcx_restore();
    return failures;
}

static int dcx_t_receipt_refusals(void)
{
    int failures = 0;

    TEST("ci: the receipt view refuses without a commit, and so does a bad view") {
        struct dcx_call c;
        dcx_isolate("receipt_refusals");
        dcx_begin(&c, "{\"topic\":\"receipt\"}");
        ASSERT(dcx_run(&c));
        ASSERT(!dcx_ok(&c));
        ASSERT(strcmp(c.reply.error.code, "SHA_REQUIRED") == 0);
        dcx_end(&c);
        dcx_begin(&c, "{\"topic\":\"receipt\",\"sha\":\"nothex!\"}");
        ASSERT(dcx_run(&c));
        ASSERT(!dcx_ok(&c));
        ASSERT(strcmp(c.reply.error.code, "SHA_INVALID") == 0);
        dcx_end(&c);
        dcx_begin(&c, "{\"topic\":\"whatever\"}");
        ASSERT(dcx_run(&c));
        ASSERT(!dcx_ok(&c));
        ASSERT(strcmp(c.reply.error.code, "VIEW_UNKNOWN") == 0);
        dcx_end(&c);
        PASS();
    }

_test_next:;
    dcx_restore();
    return failures;
}

/* ── cancel and retry: named, never run ──────────────────────────────── */

static int dcx_t_cancel(void)
{
    int failures = 0;

    TEST("ci: cancel names the sibling command and moves nothing") {
        struct dcx_call c;
        const struct json_value *arr;
        char qpath[DCX_BUF], dir[DCX_BUF], before[DCX_BUF * 4];
        char after[DCX_BUF * 4];
        dcx_isolate("cancel");
        dcx_seed_land();
        dcx_seed_units(30, true);
        dcx_join(dir, sizeof(dir), g_dcx_root, "land");
        dcx_join(qpath, sizeof(qpath), dir, "queue.jsonl");
        dcx_slurp(qpath, before, sizeof(before));
        dcx_begin(&c, "{\"topic\":\"cancel\"}");
        ASSERT(dcx_run(&c));
        ASSERT(dcx_ok(&c));
        ASSERT(dcx_bool(&c.reply.data, "read_only"));
        arr = dcx_arr(&c, "cancellable");
        ASSERT(arr != NULL);
        ASSERT(dcx_any(arr, "command", "dev land cancel --seq=1"));
        ASSERT(dcx_any(arr, "command", "dev land cancel --seq=2"));
        ASSERT(dcx_any(arr, "command",
                       "dev agent queue cancel --name=unit-alpha"));
        /* A running unit is not cancellable, and the row says why instead
         * of offering a command that would be refused. */
        ASSERT(dcx_any(arr, "what", "unit_running"));
        for (size_t i = 0; i < json_size(arr); i++) {
            const struct json_value *row = json_at(arr, i);
            if (strcmp(dcx_str(row, "what"), "unit_running") != 0)
                continue;
            ASSERT(dcx_str(row, "command")[0] == '\0');
            ASSERT(dcx_str(row, "reason")[0] != '\0');
        }
        /* Nothing was cancelled: the queue file is byte-identical. */
        dcx_slurp(qpath, after, sizeof(after));
        ASSERT(before[0] != '\0');
        ASSERT(strcmp(before, after) == 0);
        dcx_end(&c);
        PASS();
    }

_test_next:;
    dcx_restore();
    return failures;
}

static int dcx_t_retry(void)
{
    int failures = 0;

    TEST("ci: retry names the exact proof pair and never guesses a base") {
        struct dcx_call c;
        const struct json_value *arr;
        char input[DCX_BUF], path[DCX_BUF];
        dcx_isolate("retry");
        dcx_seed_land();
        dcx_seed_receipt(DCX_FAILED, DCX_BASE);
        if ((size_t)snprintf(input, sizeof(input),
                "{\"topic\":\"retry\",\"root\":\"%s\"}", g_dcx_checkout) >=
            sizeof(input))
            dcx_fail("retry input does not fit");
        dcx_begin(&c, input);
        ASSERT(dcx_run(&c));
        ASSERT(dcx_ok(&c));
        ASSERT(dcx_bool(&c.reply.data, "read_only"));
        arr = dcx_arr(&c, "retryable");
        ASSERT(arr != NULL);
        ASSERT(json_size(arr) == 1);
        ASSERT(dcx_any(arr, "command",
                       "dev proof retry --local_commit=" DCX_FAILED
                       " --remote_base=" DCX_BASE));
        /* This leaf creates nothing under the state root. */
        dcx_join(path, sizeof(path), g_dcx_root, "ci");
        ASSERT(!dcx_exists(path));
        dcx_end(&c);
        PASS();
    }

_test_next:;
    dcx_restore();
    return failures;
}

static int dcx_t_retry_unresolved_base(void)
{
    int failures = 0;

    TEST("ci: a failure with no receipt reports an unknown base and no command") {
        struct dcx_call c;
        const struct json_value *row;
        char input[DCX_BUF];
        dcx_isolate("retry_unresolved");
        dcx_seed_land();
        /* A receipt for some OTHER commit must not lend its base to this
         * one: the failing tip has no receipt of its own here. */
        dcx_seed_receipt(DCX_LANDED, DCX_BASE);
        if ((size_t)snprintf(input, sizeof(input),
                "{\"topic\":\"retry\",\"root\":\"%s\"}", g_dcx_checkout) >=
            sizeof(input))
            dcx_fail("retry input does not fit");
        dcx_begin(&c, input);
        ASSERT(dcx_run(&c));
        ASSERT(dcx_ok(&c));
        row = json_at(dcx_arr(&c, "retryable"), 0);
        ASSERT(row != NULL);
        ASSERT(strcmp(dcx_str(row, "tip"), DCX_FAILED) == 0);
        ASSERT(strcmp(dcx_str(row, "remote_base"), "unknown") == 0);
        ASSERT(dcx_str(row, "command")[0] == '\0');
        ASSERT(dcx_str(row, "reason")[0] != '\0');
        dcx_end(&c);
        PASS();
    }

_test_next:;
    dcx_restore();
    return failures;
}

int test_dev_ci(void)
{
    int failures = 0;
    failures += dcx_t_registered();
    failures += dcx_t_status();
    failures += dcx_t_queue();
    failures += dcx_t_jobs();
    failures += dcx_t_last_pass();
    failures += dcx_t_last_fail();
    failures += dcx_t_worker_active();
    failures += dcx_t_worker_owner_reused();
    failures += dcx_t_worker_owner_unverified();
    failures += dcx_t_worker_stale();
    failures += dcx_t_worker_unnamed();
    failures += dcx_t_worker_no_claim();
    failures += dcx_t_worker_unmeasured();
    failures += dcx_t_land_unreadable();
    failures += dcx_t_receipt_found();
    failures += dcx_t_receipt_unknown();
    failures += dcx_t_receipt_refusals();
    failures += dcx_t_cancel();
    failures += dcx_t_retry();
    failures += dcx_t_retry_unresolved_base();
    return failures;
}
