/* Copyright 2026 Rhett Creighton - Apache License 2.0
 *
 * ACCEPTANCE BAR for fleet.steer + fleet.steer.grant
 * (tools/command/native_fleet_steer.c).
 *
 * The thin remote-STEER adapter over the existing fleet leaves: brief composes
 * mail/queue/board/ledger in-process, send posts bounded directive batches
 * with idempotency keys, evidence returns one object per exact reference,
 * and the grant leaf mints/revokes scoped bearer grants.
 *
 * Written against an isolated platform state root, never the operator's
 * real state dir. The board and ledger siblings have no node and no
 * delegation here, so the tests pin their honest absence (missing[] /
 * EVIDENCE_UNAVAILABLE) rather than their data. No case touches the
 * network, sleeps, or polls. Do not edit this file to make the
 * implementation pass.
 */

#include "test/test_core.h"

#include "command/native_command.h"
#include "command/native_devagent.h"
#include "command/native_fleet.h"
#include "config/command_catalog.h"
#include "controllers/rpc_client.h"
#include "json/json.h"
#include "kernel/command_registry.h"
#include "platform/private_directory.h"
#include "platform/time_compat.h"

#include <limits.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#if defined(_WIN32)
#ifndef WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
#endif
#include <windows.h>
#else
#include <dirent.h>
#include <fcntl.h>
#include <sys/file.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <unistd.h>
#endif

#define FMX_BRIEF_PATH "fleet.steer.brief"
#define FMX_SEND_PATH "fleet.steer.send"
#define FMX_EVIDENCE_PATH "fleet.steer.evidence"
#define FMX_GRANT_PATH "fleet.steer.grant"

/* The sender every plain fixture grant is minted under. A grant's label IS
 * its sender identity now, so a fixture that mints one has named one. */
#define FMX_SENDER "steer-caller"

/* ── isolated state root (this group owns its own rig) ─────────────────── */

static char g_fmx_state[1024];
static bool g_fmx_had_root;
static bool g_fmx_isolated;
#if defined(_WIN32)
static wchar_t g_fmx_saved_root[32768];
#else
static char g_fmx_saved_root[4096];
#endif

static void fmx_fixture_fail(const char *context)
{
    fprintf(stderr, "fleet_steer fixture: %s\n", context);
    abort();
}

#if defined(_WIN32)
static void fmx_isolate_env(const char *state)
{
    wchar_t root[1024];
    g_fmx_saved_root[0] = L'\0';
    SetLastError(ERROR_SUCCESS);
    DWORD length = GetEnvironmentVariableW(L"ZCL_STATE_ROOT", g_fmx_saved_root,
                                           32768);
    DWORD error = GetLastError();
    if (length >= 32768 || (length == 0 && error != ERROR_SUCCESS &&
                            error != ERROR_ENVVAR_NOT_FOUND))
        fmx_fixture_fail("could not preserve ZCL_STATE_ROOT");
    g_fmx_had_root = length > 0 || error == ERROR_SUCCESS;
    if (MultiByteToWideChar(CP_UTF8, MB_ERR_INVALID_CHARS, state, -1,
                            root, 1024) <= 0 ||
        !SetEnvironmentVariableW(L"ZCL_STATE_ROOT", root))
        fmx_fixture_fail("could not isolate ZCL_STATE_ROOT");
}
#else
static void fmx_isolate_env(const char *state)
{
    const char *original = getenv("XDG_STATE_HOME");
    g_fmx_had_root = original != NULL;
    if (original) {
        int n = snprintf(g_fmx_saved_root, sizeof(g_fmx_saved_root), "%s",
                         original);
        if (n < 0 || (size_t)n >= sizeof(g_fmx_saved_root))
            fmx_fixture_fail("could not preserve XDG_STATE_HOME");
    }
    if (setenv("XDG_STATE_HOME", state, 1) != 0)
        fmx_fixture_fail("could not isolate XDG_STATE_HOME");
}
#endif

static void fmx_isolate(const char *tag)
{
    char base[512];
    if (g_fmx_isolated)
        fmx_fixture_fail("previous state root has not been restored");
    test_make_tmpdir(base, sizeof(base), "fleet_steer", tag);
    int n = snprintf(g_fmx_state, sizeof(g_fmx_state), "%s/state", base);
    if (n <= 0 || (size_t)n >= sizeof(g_fmx_state) ||
        !platform_private_directory_ensure(g_fmx_state))
        fmx_fixture_fail("could not create isolated state parent");
    fmx_isolate_env(g_fmx_state);
    g_fmx_isolated = true;
}

static void fmx_restore(void)
{
    if (!g_fmx_isolated) return;
#if defined(_WIN32)
    if (!SetEnvironmentVariableW(L"ZCL_STATE_ROOT",
                                 g_fmx_had_root ? g_fmx_saved_root : NULL))
        fmx_fixture_fail("could not restore ZCL_STATE_ROOT");
#else
    int rc = g_fmx_had_root ? setenv("XDG_STATE_HOME", g_fmx_saved_root, 1)
                            : unsetenv("XDG_STATE_HOME");
    if (rc != 0)
        fmx_fixture_fail("could not restore XDG_STATE_HOME");
#endif
    g_fmx_isolated = false;
}

/* ── one in-process invocation ─────────────────────────────────────────── */

struct fmx_call {
    struct json_value input;
    struct zcl_command_request request;
    struct zcl_command_reply reply;
};

static void fmx_begin(struct fmx_call *c, const char *path,
                      const char *schema)
{
    json_init(&c->input);
    json_set_object(&c->input);
    memset(&c->request, 0, sizeof(c->request));
    c->request.input = &c->input;
    c->request.spec =
        zcl_command_registry_find(zcl_command_catalog(), path, NULL);
    zcl_command_reply_init(&c->reply, schema);
}

static bool fmx_run(struct fmx_call *c,
                    void (*handler)(const struct zcl_command_request *,
                                    struct zcl_command_reply *))
{
    char why[256];
    if (c->request.spec &&
        !zcl_command_registry_input_validate(c->request.spec, &c->input, why,
                                             sizeof(why))) {
        printf("[input rejected: %s] ", why);
        return false;
    }
    handler(&c->request, &c->reply);
    return true;
}

static void fmx_end(struct fmx_call *c)
{
    zcl_command_reply_free(&c->reply);
    json_free(&c->input);
}

static bool fmx_ok(const struct fmx_call *c)
{
    return c->reply.status == ZCL_COMMAND_STATUS_PASSED;
}

static const struct json_value *fmx_get(const struct fmx_call *c,
                                        const char *key)
{
    return json_get(&c->reply.data, key);
}

static const char *fmx_str(const struct fmx_call *c, const char *key)
{
    const struct json_value *v = fmx_get(c, key);
    return v && v->type == JSON_STR && json_get_str(v) ? json_get_str(v) : "";
}

static const struct json_value *fmx_arr(const struct fmx_call *c,
                                        const char *key)
{
    const struct json_value *v = fmx_get(c, key);
    return v && v->type == JSON_ARR ? v : NULL;
}

/* Integer reply field, or -1 when absent/wrong-typed. */
static long long fmx_int(const struct fmx_call *c, const char *key)
{
    const struct json_value *v = fmx_get(c, key);
    return v && v->type == JSON_INT ? json_get_int(v) : -1;
}

/* True when missing[] names the given source. */
static bool fmx_missing_has(const struct fmx_call *c, const char *source)
{
    const struct json_value *missing = fmx_arr(c, "missing");
    size_t n, i;
    if (!missing)
        return false;
    n = json_size(missing);
    for (i = 0; i < n; i++) {
        const struct json_value *e = json_at(missing, i);
        const struct json_value *v;
        const char *s;
        if (!e || e->type != JSON_OBJ)
            continue;
        v = json_get(e, "source");
        s = (v && v->type == JSON_STR) ? json_get_str(v) : NULL;
        if (s && strcmp(s, source) == 0)
            return true;
    }
    return false;
}

/* Mint a grant through the real leaf under an explicit sender label;
 * copies the id out before freeing. */
static bool fmx_mint_as(const char *scopes, const char *label, char *id_out,
                        size_t id_cap)
{
    struct fmx_call g;
    const char *id;
    bool ok = false;
    fmx_begin(&g, FMX_GRANT_PATH, "zcl.fleet_steer_grant.v1");
    (void)json_push_kv_str(&g.input, "action", "mint");
    (void)json_push_kv_str(&g.input, "scopes", scopes);
    if (label)
        (void)json_push_kv_str(&g.input, "label", label);
    if (!fmx_run(&g, zcl_native_handle_fleet_steer_grant) || !fmx_ok(&g)) {
        fmx_end(&g);
        return false;
    }
    id = fmx_str(&g, "id");
    if (id[0] && strlen(id) == 32 && strlen(id) < id_cap) {
        snprintf(id_out, id_cap, "%s", id);
        ok = true;
    }
    fmx_end(&g);
    return ok;
}

/* The ordinary fixture grant: one live credential speaking as FMX_SENDER. */
static bool fmx_mint(const char *scopes, char *id_out, size_t id_cap)
{
    return fmx_mint_as(scopes, FMX_SENDER, id_out, id_cap);
}

/* One send item object. */
static void fmx_item(struct json_value *item, const char *to,
                     const char *body, const char *ref, const char *key)
{
    json_init(item);
    json_set_object(item);
    (void)json_push_kv_str(item, "to", to);
    (void)json_push_kv_str(item, "body", body);
    (void)json_push_kv_str(item, "ref", ref);
    (void)json_push_kv_str(item, "idempotency_key", key);
}

/* Send one batch under an explicit sender name, so a case can address a
 * reply row back at the sender the way a real recipient would — and so a
 * case can claim a name its credential does not carry. A NULL `from`
 * states no sender at all. */
static bool fmx_send_from(struct fmx_call *c, const char *grant,
                          const char *from, struct json_value *items)
{
    fmx_begin(c, FMX_SEND_PATH, "zcl.fleet_steer_send.v1");
    if (grant)
        (void)json_push_kv_str(&c->input, "grant", grant);
    if (from)
        (void)json_push_kv_str(&c->input, "from", from);
    (void)json_push_kv(&c->input, "items", items);
    return fmx_run(c, zcl_native_handle_fleet_steer_send);
}

/* Send one batch through the real leaf, speaking as the fixture grant's own
 * label — the honest case, which is what most cases here are about. Caller
 * frees items/out. */
static bool fmx_send(struct fmx_call *c, const char *grant,
                     struct json_value *items)
{
    return fmx_send_from(c, grant, grant ? FMX_SENDER : NULL, items);
}

static void fmx_brief(struct fmx_call *c, const char *grant, long long since)
{
    fmx_begin(c, FMX_BRIEF_PATH, "zcl.fleet_steer_brief.v1");
    if (grant)
        (void)json_push_kv_str(&c->input, "grant", grant);
    (void)json_push_kv_int(&c->input, "since", since);
}

static void fmx_evidence(struct fmx_call *c, const char *grant,
                         const char *type, const char *ref)
{
    fmx_begin(c, FMX_EVIDENCE_PATH, "zcl.fleet_steer_evidence.v1");
    if (grant)
        (void)json_push_kv_str(&c->input, "grant", grant);
    (void)json_push_kv_str(&c->input, "type", type);
    (void)json_push_kv_str(&c->input, "ref", ref);
}

/* Mail pull count through the real mail leaf (outbox line accounting
 * without touching paths directly). */
static long long fmx_mail_count(void)
{
    struct fmx_call p;
    long long n = -1;
    json_init(&p.input);
    json_set_object(&p.input);
    memset(&p.request, 0, sizeof(p.request));
    p.request.input = &p.input;
    p.request.spec =
        zcl_command_registry_find(zcl_command_catalog(), "dev.agent.mail",
                                  NULL);
    zcl_command_reply_init(&p.reply, "zcl.agent_mail.v1");
    (void)json_push_kv_str(&p.input, "action", "pull");
    (void)json_push_kv_int(&p.input, "since", 0);
    zcl_native_handle_dev_agent_mail(&p.request, &p.reply);
    if (p.reply.status == ZCL_COMMAND_STATUS_PASSED) {
        const struct json_value *v = json_get(&p.reply.data, "count");
        if (v && v->type == JSON_INT)
            n = json_get_int(v);
    }
    zcl_command_reply_free(&p.reply);
    json_free(&p.input);
    return n;
}

/* Mail ack through the real mail leaf. */
static bool fmx_ack(const char *agent, long long cursor)
{
    struct fmx_call a;
    bool ok;
    json_init(&a.input);
    json_set_object(&a.input);
    memset(&a.request, 0, sizeof(a.request));
    a.request.input = &a.input;
    a.request.spec =
        zcl_command_registry_find(zcl_command_catalog(), "dev.agent.mail",
                                  NULL);
    zcl_command_reply_init(&a.reply, "zcl.agent_mail.v1");
    (void)json_push_kv_str(&a.input, "action", "ack");
    (void)json_push_kv_str(&a.input, "agent", agent);
    (void)json_push_kv_int(&a.input, "cursor", cursor);
    zcl_native_handle_dev_agent_mail(&a.request, &a.reply);
    ok = a.reply.status == ZCL_COMMAND_STATUS_PASSED;
    zcl_command_reply_free(&a.reply);
    json_free(&a.input);
    return ok;
}

/* Seed one queue outcome row so completed-by-ref has evidence to match.
 * The queue status leaf parses this exact reap format. */
static void fmx_seed_outcome(const char *name)
{
    char dir[1024], path[1200];
    int n = snprintf(dir, sizeof(dir), "%s/z23/dev/queue", g_fmx_state);
    if (n <= 0 || (size_t)n >= sizeof(dir))
        fmx_fixture_fail("queue dir exceeds bound");
    if (!platform_private_directory_ensure(dir))
        fmx_fixture_fail("cannot create isolated queue dir");
    n = snprintf(path, sizeof(path), "%s/outcomes.jsonl", dir);
    if (n <= 0 || (size_t)n >= sizeof(path))
        fmx_fixture_fail("outcome path exceeds bound");
    FILE *f = fopen(path, "a");
    if (!f)
        fmx_fixture_fail("cannot seed outcome row");
    /* Writes the reap row shape status parses: name/attempt required,
     * verdict+rc decide pass-like. */
    if (fprintf(f,
                "{\"ts\":\"2026-09-15T00:00:00Z\",\"name\":\"%s\","
                "\"attempt\":1,\"verdict\":\"pass\",\"rc\":0}\n",
                name) < 0)
        fmx_fixture_fail("cannot write outcome row");
    if (fclose(f) != 0)
        fmx_fixture_fail("cannot finish outcome row");
}

/* Drop one row into <state>/mail/inbox.<peer>.jsonl — exactly what a
 * transport does when it carries a peer's row onto this host, and the only
 * way a row this host did not write appears in pull. The shape is the mail
 * leaf's own row; `ts` is the caller's so pull order (ts, from, seq) stays
 * deterministic without a sleep. */
static void fmx_seed_inbox(const char *peer, const char *ts, long long seq,
                           const char *from, const char *to,
                           const char *kind, const char *body,
                           const char *ref)
{
    char dir[1024], path[1200];
    int n = snprintf(dir, sizeof(dir), "%s/z23/dev/mail", g_fmx_state);
    if (n <= 0 || (size_t)n >= sizeof(dir))
        fmx_fixture_fail("mail dir exceeds bound");
    if (!platform_private_directory_ensure(dir))
        fmx_fixture_fail("cannot create isolated mail dir");
    n = snprintf(path, sizeof(path), "%s/inbox.%s.jsonl", dir, peer);
    if (n <= 0 || (size_t)n >= sizeof(path))
        fmx_fixture_fail("inbox path exceeds bound");
    FILE *f = fopen(path, "a");
    if (!f)
        fmx_fixture_fail("cannot seed an inbox row");
    if (fprintf(f,
                "{\"seq\":%lld,\"ts\":\"%s\",\"from\":\"%s\",\"to\":\"%s\","
                "\"kind\":\"%s\",\"body\":\"%s\",\"ref\":\"%s\"}\n",
                seq, ts, from, to, kind, body, ref) < 0)
        fmx_fixture_fail("cannot write an inbox row");
    if (fclose(f) != 0)
        fmx_fixture_fail("cannot finish an inbox row");
}

/* The state the brief reports for the change row `from` wrote under `ref`,
 * or "" when the brief shows no such row. Matching on both fields keeps a
 * directive and the reply that shares its ref apart. */
static const char *fmx_change_state(const struct json_value *changes,
                                    const char *from, const char *ref)
{
    size_t n, i;
    if (!changes || changes->type != JSON_ARR)
        return "";
    n = json_size(changes);
    for (i = 0; i < n; i++) {
        const struct json_value *ch = json_at(changes, i);
        const struct json_value *v;
        if (!ch || ch->type != JSON_OBJ)
            continue;
        v = json_get(ch, "from");
        if (!v || v->type != JSON_STR || strcmp(json_get_str(v), from) != 0)
            continue;
        v = json_get(ch, "ref");
        if (!v || v->type != JSON_STR || strcmp(json_get_str(v), ref) != 0)
            continue;
        v = json_get(ch, "state");
        return (v && v->type == JSON_STR && json_get_str(v)) ? json_get_str(v)
                                                             : "";
    }
    return "";
}

/* One string field of the bounded evidence object. */
static const char *fmx_obj_str(const struct fmx_call *e, const char *key)
{
    const struct json_value *obj = json_get(&e->reply.data, "object");
    const struct json_value *v = obj ? json_get(obj, key) : NULL;
    return v && v->type == JSON_STR && json_get_str(v) ? json_get_str(v) : "";
}

/* True when evidence for `ref` reports `want` AND the brief reports the
 * same state for that very row (matched by the evidence object's own from
 * and ref). The two surfaces must never disagree about one row. */
static bool fmx_state_agrees(const char *gid, const char *ref,
                             const char *want)
{
    struct fmx_call b, e;
    bool ok = false;
    fmx_brief(&b, gid, 0);
    if (!fmx_run(&b, zcl_native_handle_fleet_steer_brief) || !fmx_ok(&b)) {
        fmx_end(&b);
        return false;
    }
    fmx_evidence(&e, gid, "mail", ref);
    if (fmx_run(&e, zcl_native_handle_fleet_steer_evidence) && fmx_ok(&e)) {
        const char *estate = fmx_str(&e, "state");
        const char *bstate = fmx_change_state(fmx_arr(&b, "changes"),
                                              fmx_obj_str(&e, "from"),
                                              fmx_obj_str(&e, "ref"));
        ok = strcmp(estate, want) == 0 && strcmp(bstate, want) == 0;
    }
    fmx_end(&e);
    fmx_end(&b);
    return ok;
}

/* Craft one expired grant row: expiry honors the wall clock, and no test
 * should sleep to prove it. */
static void fmx_seed_expired(const char *id)
{
    char dir[1024], path[1200];
    int n = snprintf(dir, sizeof(dir), "%s/z23/dev/steer", g_fmx_state);
    if (n <= 0 || (size_t)n >= sizeof(dir))
        fmx_fixture_fail("steer dir exceeds bound");
    if (!platform_private_directory_ensure(dir))
        fmx_fixture_fail("cannot create isolated steer dir");
    n = snprintf(path, sizeof(path), "%s/grants.jsonl", dir);
    if (n <= 0 || (size_t)n >= sizeof(path))
        fmx_fixture_fail("grant path exceeds bound");
    FILE *f = fopen(path, "a");
    if (!f)
        fmx_fixture_fail("cannot seed expired grant");
    if (fprintf(f,
                "{\"id\":\"%s\",\"scopes\":\"brief,send,evidence\","
                "\"created\":1,\"expires\":2,\"revoked\":\"0\","
                "\"label\":\"expired\"}\n",
                id) < 0)
        fmx_fixture_fail("cannot write expired grant");
    if (fclose(f) != 0)
        fmx_fixture_fail("cannot finish expired grant");
}

/* No node in this group, deterministically: every board sibling call
 * fails closed with NODE_UNAVAILABLE instead of depending on ambient
 * ports or cookies. Groups run forked, and the hook is cleared at the
 * single function exit so the sequential runner is unaffected. */
static char *fmx_no_node(const char *method, const char *params_json)
{
    (void)method;
    (void)params_json;
    return NULL;
}

static int fmx_t_register(void)
{
    int failures = 0;

    TEST("steer: all four leaves are registered with declared keys") {
        const struct zcl_command_spec *spec =
            zcl_command_registry_find(zcl_command_catalog(), FMX_BRIEF_PATH,
                                      NULL);
        ASSERT(spec != NULL);
        ASSERT(spec->input_keys && strstr(spec->input_keys, "since") != NULL);
        spec = zcl_command_registry_find(zcl_command_catalog(),
                                         FMX_SEND_PATH, NULL);
        ASSERT(spec != NULL);
        ASSERT(spec->input_keys && strstr(spec->input_keys, "items") != NULL);
        spec = zcl_command_registry_find(zcl_command_catalog(),
                                         FMX_EVIDENCE_PATH, NULL);
        ASSERT(spec != NULL);
        ASSERT(spec->input_keys && strstr(spec->input_keys, "ref") != NULL);
        spec = zcl_command_registry_find(zcl_command_catalog(),
                                         FMX_GRANT_PATH, NULL);
        ASSERT(spec != NULL);
        ASSERT(spec->input_keys && strstr(spec->input_keys, "scopes") != NULL);
        PASS();
    }

_test_next:;
    fmx_restore();
    return failures;
}

static int fmx_t_brief_empty(void)
{
    int failures = 0;

    TEST("steer: brief on an empty root reports shape and honest absence") {
        struct fmx_call b;
        fmx_isolate("brief_empty");
        fmx_brief(&b, NULL, 0);
        ASSERT(fmx_run(&b, zcl_native_handle_fleet_steer_brief));
        ASSERT(fmx_ok(&b));
        ASSERT(fmx_arr(&b, "agents") != NULL);
        ASSERT(fmx_arr(&b, "work") != NULL);
        ASSERT(fmx_arr(&b, "blockers") != NULL);
        ASSERT(fmx_arr(&b, "candidates") != NULL);
        ASSERT(fmx_arr(&b, "changes") != NULL);
        ASSERT(fmx_arr(&b, "missing") != NULL);
        ASSERT(json_get(&b.reply.data, "capacity") != NULL);
        ASSERT(json_get(&b.reply.data, "evidence") != NULL);
        /* No node here: the board must be reported missing, never empty. */
        ASSERT(fmx_missing_has(&b, "fleet.board"));
        fmx_end(&b);
        fmx_restore();
        PASS();
    }

_test_next:;
    fmx_restore();
    return failures;
}

/* One minted grant plus one accepted directive through the real leaves.
 * Plain checks (no ASSERT: the macro's goto cannot cross functions), so
 * callers assert once on the outcome. */
struct fmx_accept {
    char gid[64];
    long long seq;
    long long accepted;
    bool duplicate;
    bool ok;
};

static struct fmx_accept fmx_probe(void)
{
    struct fmx_call s;
    struct json_value items, item;
    struct fmx_accept a;
    const struct json_value *out, *row, *v;
    memset(&a, 0, sizeof(a));
    a.seq = -1;
    if (!fmx_mint("brief,send,evidence", a.gid, sizeof(a.gid)))
        return a;
    json_init(&items);
    json_set_array(&items);
    fmx_item(&item, "field-agent", "sweep the north fence line",
             "fence-sweep", "key-fence-1");
    (void)json_push_back(&items, &item);
    json_free(&item);
    if (!fmx_send(&s, a.gid, &items)) {
        json_free(&items);
        return a;
    }
    json_free(&items);
    if (!fmx_ok(&s)) {
        fmx_end(&s);
        return a;
    }
    out = fmx_arr(&s, "items");
    row = out ? json_at(out, 0) : NULL;
    v = row ? json_get(row, "duplicate") : NULL;
    a.duplicate = v && v->type == JSON_BOOL && json_get_bool(v);
    v = row ? json_get(row, "seq") : NULL;
    if (v && v->type == JSON_INT)
        a.seq = json_get_int(v);
    a.accepted = fmx_int(&s, "accepted");
    v = row ? json_get(row, "state") : NULL;
    a.ok = v && v->type == JSON_STR && strcmp(json_get_str(v), "queued") == 0;
    fmx_end(&s);
    return a;
}

/* The single change row a fresh probe leaves behind: queued, with a
 * lead (not the body) and its ref. Queued, not delivered: the probe's own
 * outbox is always inside the probe's own pull, so nothing here says the
 * directive reached the recipient. */
static bool fmx_check_queued(const struct json_value *changes)
{
    const struct json_value *ch, *v;
    if (!changes || changes->type != JSON_ARR || json_size(changes) != 1)
        return false;
    ch = json_at(changes, 0);
    if (!ch || ch->type != JSON_OBJ)
        return false;
    v = json_get(ch, "state");
    if (!v || v->type != JSON_STR ||
        strcmp(json_get_str(v), "queued") != 0)
        return false;
    v = json_get(ch, "lead");
    if (!v || v->type != JSON_STR ||
        strstr(json_get_str(v), "north fence") == NULL)
        return false;
    v = json_get(ch, "ref");
    if (!v || v->type != JSON_STR ||
        strcmp(json_get_str(v), "fence-sweep") != 0)
        return false;
    return true;
}

/* The bounded evidence object carries the whole row body. */
static bool fmx_check_body(const struct fmx_call *e, const char *want)
{
    const struct json_value *obj, *v;
    if (!e || !want)
        return false;
    obj = json_get(&e->reply.data, "object");
    if (!obj || obj->type != JSON_OBJ)
        return false;
    v = json_get(obj, "body");
    if (!v || v->type != JSON_STR)
        return false;
    return strcmp(json_get_str(v), want) == 0;
}

static int fmx_t_send_flow(void)
{
    int failures = 0;

    TEST("steer: mint and send accept one directive") {
        struct fmx_accept a;
        fmx_isolate("send_flow");
        a = fmx_probe();
        ASSERT(a.ok);
        ASSERT(a.seq >= 1);
        ASSERT(!a.duplicate);
        ASSERT(a.gid[0] != '\0');
        /* A fresh, wholly-accepted one-item batch reports accepted=1,
         * never the item-result count in disguise. */
        ASSERT_EQ(a.accepted, 1);
        fmx_restore();
        PASS();
    }

_test_next:;
    fmx_restore();
    return failures;
}

static int fmx_t_brief_changes(void)
{
    int failures = 0;

    TEST("steer: brief carries the directive as a queued lead") {
        struct fmx_call b;
        struct fmx_accept a;
        fmx_isolate("brief_changes");
        a = fmx_probe();
        ASSERT(a.ok);
        fmx_brief(&b, a.gid, 0);
        ASSERT(fmx_run(&b, zcl_native_handle_fleet_steer_brief));
        ASSERT(fmx_ok(&b));
        ASSERT(fmx_check_queued(fmx_arr(&b, "changes")));
        fmx_end(&b);
        fmx_restore();
        PASS();
    }

_test_next:;
    fmx_restore();
    return failures;
}

static int fmx_t_evidence(void)
{
    int failures = 0;

    TEST("steer: evidence by exact ref returns the bounded row") {
        struct fmx_call e;
        struct fmx_accept a;
        fmx_isolate("evidence");
        a = fmx_probe();
        ASSERT(a.ok);
        fmx_evidence(&e, a.gid, "mail", "fence-sweep");
        ASSERT(fmx_run(&e, zcl_native_handle_fleet_steer_evidence));
        ASSERT(fmx_ok(&e));
        ASSERT(fmx_check_body(&e, "sweep the north fence line"));
        fmx_end(&e);
        /* Unknown refs are typed refusals, not empty objects. */
        fmx_evidence(&e, a.gid, "mail", "no-such-ref");
        ASSERT(fmx_run(&e, zcl_native_handle_fleet_steer_evidence));
        ASSERT(!fmx_ok(&e));
        ASSERT_STR_EQ(e.reply.error.code, "EVIDENCE_NOT_FOUND");
        fmx_end(&e);
        fmx_restore();
        PASS();
    }

_test_next:;
    fmx_restore();
    return failures;
}

static int fmx_t_duplicate(void)
{
    int failures = 0;

    TEST("steer: duplicate delivery reconciles, never re-posts") {
        struct fmx_call s;
        struct json_value items, item;
        const struct json_value *out, *row;
        const struct json_value *v;
        char gid[64];
        long long before, seq1, seq2;
        fmx_isolate("duplicate");
        ASSERT(fmx_mint("brief,send,evidence", gid, sizeof(gid)));
        json_init(&items);
        json_set_array(&items);
        fmx_item(&item, "field-agent", "check the water pump", "pump-check",
                 "key-pump-1");
        (void)json_push_back(&items, &item);
        json_free(&item);
        ASSERT(fmx_send(&s, gid, &items));
        json_free(&items);
        ASSERT(fmx_ok(&s));
        out = fmx_arr(&s, "items");
        ASSERT(out != NULL);
        row = json_at(out, 0);
        v = json_get(row, "seq");
        ASSERT(v && v->type == JSON_INT);
        seq1 = json_get_int(v);
        fmx_end(&s);
        before = fmx_mail_count();
        ASSERT(before == 1);
        /* Same key again: same accept, duplicate flag, no second row. */
        json_init(&items);
        json_set_array(&items);
        fmx_item(&item, "field-agent", "check the water pump", "pump-check",
                 "key-pump-1");
        (void)json_push_back(&items, &item);
        json_free(&item);
        ASSERT(fmx_send(&s, gid, &items));
        json_free(&items);
        ASSERT(fmx_ok(&s));
        out = fmx_arr(&s, "items");
        row = json_at(out, 0);
        v = json_get(row, "seq");
        ASSERT(v && v->type == JSON_INT);
        seq2 = json_get_int(v);
        ASSERT_EQ(seq1, seq2);
        v = json_get(row, "duplicate");
        ASSERT(v && v->type == JSON_BOOL && json_get_bool(v));
        /* An exact duplicate is still an accept: it reports the
         * recorded row, not a refusal. */
        ASSERT_EQ(fmx_int(&s, "accepted"), 1);
        fmx_end(&s);
        ASSERT_EQ(fmx_mail_count(), before);
        /* A different payload under the same key is refused, not
         * counted as accepted. */
        {
            struct fmx_call conflict;
            struct json_value citems, citem;
            const struct json_value *crow;
            const struct json_value *cv;
            json_init(&citems);
            json_set_array(&citems);
            fmx_item(&citem, "field-agent", "check the OTHER water pump",
                     "pump-check", "key-pump-1");
            (void)json_push_back(&citems, &citem);
            json_free(&citem);
            ASSERT(fmx_send(&conflict, gid, &citems));
            json_free(&citems);
            ASSERT(fmx_ok(&conflict));
            ASSERT_EQ(fmx_int(&conflict, "accepted"), 0);
            crow = json_at(fmx_arr(&conflict, "items"), 0);
            cv = crow ? json_get(crow, "state") : NULL;
            ASSERT(cv && cv->type == JSON_STR &&
                   strcmp(json_get_str(cv), "refused") == 0);
            cv = crow ? json_get(crow, "error") : NULL;
            ASSERT(cv && cv->type == JSON_STR &&
                   strcmp(json_get_str(cv), "IDEMPOTENCY_CONFLICT") == 0);
            fmx_end(&conflict);
            ASSERT_EQ(fmx_mail_count(), before);
        }
        /* A batch of one good item plus one BAD_INPUT item reports
         * accepted=1, not 2: the refused item never counts. */
        {
            struct fmx_call mixed;
            struct json_value mitems, good, bad;
            long long mail_before = fmx_mail_count();
            json_init(&mitems);
            json_set_array(&mitems);
            fmx_item(&good, "field-agent", "check the generator",
                     "generator-check", "key-generator-1");
            (void)json_push_back(&mitems, &good);
            json_free(&good);
            /* No "to": fails shape validation as BAD_INPUT. */
            json_init(&bad);
            json_set_object(&bad);
            (void)json_push_kv_str(&bad, "body", "bad item, no to field");
            (void)json_push_kv_str(&bad, "ref", "bad-item");
            (void)json_push_kv_str(&bad, "idempotency_key", "key-bad-1");
            (void)json_push_back(&mitems, &bad);
            json_free(&bad);
            ASSERT(fmx_send(&mixed, gid, &mitems));
            json_free(&mitems);
            ASSERT(fmx_ok(&mixed));
            ASSERT_EQ(fmx_int(&mixed, "accepted"), 1);
            ASSERT_EQ(fmx_mail_count(), mail_before + 1);
            fmx_end(&mixed);
        }
        /* Oversize batches are refused whole, not truncated. */
        {
            struct fmx_call big;
            struct json_value many, it;
            size_t k;
            json_init(&many);
            json_set_array(&many);
            for (k = 0; k < 9; k++) {
                char kb[32];
                snprintf(kb, sizeof(kb), "key-big-%zu", k);
                fmx_item(&it, "field-agent", "bulk", "", kb);
                (void)json_push_back(&many, &it);
                json_free(&it);
            }
            /* Refused whole at registry validation (bound 8), so the
             * handler never sees a truncated batch. */
            ASSERT(!fmx_send(&big, gid, &many));
            json_free(&many);
            fmx_end(&big);
        }
        fmx_restore();
        PASS();
    }

_test_next:;
    fmx_restore();
    return failures;
}

static int fmx_t_lifecycle(void)
{
    int failures = 0;

    TEST("steer: acknowledged and completed are distinct observed states") {
        struct fmx_call s, b;
        struct json_value items, item;
        const struct json_value *out, *row, *v;
        char gid[64];
        long long seq;
        fmx_isolate("lifecycle");
        ASSERT(fmx_mint("brief,send,evidence", gid, sizeof(gid)));
        json_init(&items);
        json_set_array(&items);
        fmx_item(&item, "rover", "map the crater rim", "crater-rim",
                 "key-crater-1");
        (void)json_push_back(&items, &item);
        json_free(&item);
        ASSERT(fmx_send(&s, gid, &items));
        json_free(&items);
        ASSERT(fmx_ok(&s));
        out = fmx_arr(&s, "items");
        row = json_at(out, 0);
        v = json_get(row, "seq");
        ASSERT(v && v->type == JSON_INT);
        seq = json_get_int(v);
        fmx_end(&s);
        /* The receiver acks: the change upgrades to acknowledged. */
        ASSERT(fmx_ack("rover", seq));
        fmx_brief(&b, gid, 0);
        ASSERT(fmx_run(&b, zcl_native_handle_fleet_steer_brief));
        ASSERT(fmx_ok(&b));
        {
            const struct json_value *changes = fmx_arr(&b, "changes");
            const struct json_value *st;
            ASSERT(changes != NULL);
            ASSERT_EQ((long long)json_size(changes), 1);
            st = json_get(json_at(changes, 0), "state");
            ASSERT(st && st->type == JSON_STR &&
                   strcmp(json_get_str(st), "acknowledged") == 0);
        }
        fmx_end(&b);
        /* A pass-like queue outcome on the ref completes it. */
        fmx_seed_outcome("crater-rim");
        fmx_brief(&b, gid, 0);
        ASSERT(fmx_run(&b, zcl_native_handle_fleet_steer_brief));
        ASSERT(fmx_ok(&b));
        {
            const struct json_value *changes = fmx_arr(&b, "changes");
            const struct json_value *st;
            ASSERT(changes != NULL);
            ASSERT_EQ((long long)json_size(changes), 1);
            st = json_get(json_at(changes, 0), "state");
            ASSERT(st && st->type == JSON_STR &&
                   strcmp(json_get_str(st), "completed") == 0);
        }
        fmx_end(&b);
        fmx_restore();
        PASS();
    }

_test_next:;
    fmx_restore();
    return failures;
}

/* The sender's own outbox is never delivery. A row this host sent through
 * steer stays queued until the receiver itself has written something;
 * rows this host did not send keep the older reading. */
static int fmx_t_sent_needs_receiver(void)
{
    int failures = 0;

    TEST("steer: a sent row is queued until the recipient answers") {
        struct fmx_call s, b;
        struct json_value items, item;
        const struct json_value *out, *row, *v;
        char gid[64];
        long long seq;
        fmx_isolate("sent_receiver");
        ASSERT(fmx_mint("brief,send,evidence", gid, sizeof(gid)));
        json_init(&items);
        json_set_array(&items);
        fmx_item(&item, "fence-crew", "sweep the north fence line",
                 "fence-sweep", "key-sent-1");
        (void)json_push_back(&items, &item);
        json_free(&item);
        ASSERT(fmx_send_from(&s, gid, "steer-caller", &items));
        json_free(&items);
        ASSERT(fmx_ok(&s));
        out = fmx_arr(&s, "items");
        row = out ? json_at(out, 0) : NULL;
        v = row ? json_get(row, "seq") : NULL;
        ASSERT(v && v->type == JSON_INT);
        seq = json_get_int(v);
        fmx_end(&s);
        ASSERT(seq >= 1);
        /* Nothing has carried those bytes anywhere. The row sits in this
         * host's own outbox, which is always inside this host's own pull,
         * so neither surface may call it delivered. */
        ASSERT(fmx_state_agrees(gid, "fence-sweep", "queued"));
        /* A row a transport dropped here keeps the older reading, even
         * when the peer's own numbering collides with our seq: the
         * receipt names a recipient, not a bare sequence number. */
        fmx_seed_inbox("peer-host", "2026-09-16T00:00:00Z", seq, "peer-host",
                       "other-crew", "note", "peer note", "inbound-ref");
        fmx_brief(&b, gid, 0);
        ASSERT(fmx_run(&b, zcl_native_handle_fleet_steer_brief));
        ASSERT(fmx_ok(&b));
        ASSERT_STR_EQ(fmx_change_state(fmx_arr(&b, "changes"), "peer-host",
                                       "inbound-ref"),
                      "delivered");
        ASSERT_STR_EQ(fmx_change_state(fmx_arr(&b, "changes"),
                                       "steer-caller", "fence-sweep"),
                      "queued");
        fmx_end(&b);
        /* The recipient's own reply under the same ref is receiver
         * evidence a sender cannot forge: the sent row promotes straight
         * to acknowledged. */
        fmx_seed_inbox("fence-crew", "2026-12-31T00:00:00Z", 9001,
                       "fence-crew", "steer-caller", "result",
                       "north fence swept", "fence-sweep");
        fmx_brief(&b, gid, 0);
        ASSERT(fmx_run(&b, zcl_native_handle_fleet_steer_brief));
        ASSERT(fmx_ok(&b));
        ASSERT_STR_EQ(fmx_change_state(fmx_arr(&b, "changes"),
                                       "steer-caller", "fence-sweep"),
                      "acknowledged");
        /* The reply row itself was not sent from here, so it reads
         * delivered. */
        ASSERT_STR_EQ(fmx_change_state(fmx_arr(&b, "changes"), "fence-crew",
                                       "fence-sweep"),
                      "delivered");
        fmx_end(&b);
        /* Evidence for that ref returns the latest row under it (the
         * reply) and agrees with the brief row for row. */
        ASSERT(fmx_state_agrees(gid, "fence-sweep", "delivered"));
        fmx_restore();
        PASS();
    }

_test_next:;
    fmx_restore();
    return failures;
}

/* The other half of the rule: a receiver on THIS host acks by writing the
 * mail cursor, and that promotes the same sent row. */
static int fmx_t_sent_local_ack(void)
{
    int failures = 0;

    TEST("steer: the local ack cursor promotes a sent row") {
        struct fmx_call s;
        struct json_value items, item;
        const struct json_value *out, *row, *v;
        char gid[64];
        long long seq;
        fmx_isolate("sent_local_ack");
        ASSERT(fmx_mint("brief,send,evidence", gid, sizeof(gid)));
        json_init(&items);
        json_set_array(&items);
        fmx_item(&item, "desk-crew", "check the desk log", "desk-check",
                 "key-sent-2");
        (void)json_push_back(&items, &item);
        json_free(&item);
        ASSERT(fmx_send_from(&s, gid, "steer-caller", &items));
        json_free(&items);
        ASSERT(fmx_ok(&s));
        out = fmx_arr(&s, "items");
        row = out ? json_at(out, 0) : NULL;
        v = row ? json_get(row, "seq") : NULL;
        ASSERT(v && v->type == JSON_INT);
        seq = json_get_int(v);
        fmx_end(&s);
        ASSERT(fmx_state_agrees(gid, "desk-check", "queued"));
        ASSERT(fmx_ack("desk-crew", seq));
        ASSERT(fmx_state_agrees(gid, "desk-check", "acknowledged"));
        fmx_restore();
        PASS();
    }

_test_next:;
    fmx_restore();
    return failures;
}

static int fmx_t_grants(void)
{
    int failures = 0;

    TEST("steer: revoked, unknown, expired and scoped grants fail closed") {
        struct fmx_call c;
        struct json_value items, item;
        char gid[64], narrow[64];
        fmx_isolate("grants");
        ASSERT(fmx_mint("brief,send,evidence", gid, sizeof(gid)));
        ASSERT(fmx_mint("send", narrow, sizeof(narrow)));
        /* Narrow scope: brief is outside it. */
        fmx_brief(&c, narrow, 0);
        ASSERT(fmx_run(&c, zcl_native_handle_fleet_steer_brief));
        ASSERT(!fmx_ok(&c));
        ASSERT_STR_EQ(c.reply.error.code, "STEER_GRANT_SCOPE");
        fmx_end(&c);
        /* Unknown bearer. */
        fmx_brief(&c, "0123456789abcdef0123456789abcdef", 0);
        ASSERT(fmx_run(&c, zcl_native_handle_fleet_steer_brief));
        ASSERT(!fmx_ok(&c));
        ASSERT_STR_EQ(c.reply.error.code, "STEER_GRANT_UNKNOWN");
        fmx_end(&c);
        /* Revoke: brief and send both refuse, nothing is disguised. */
        fmx_begin(&c, FMX_GRANT_PATH, "zcl.fleet_steer_grant.v1");
        (void)json_push_kv_str(&c.input, "action", "revoke");
        (void)json_push_kv_str(&c.input, "id", gid);
        ASSERT(fmx_run(&c, zcl_native_handle_fleet_steer_grant));
        ASSERT(fmx_ok(&c));
        fmx_end(&c);
        fmx_brief(&c, gid, 0);
        ASSERT(fmx_run(&c, zcl_native_handle_fleet_steer_brief));
        ASSERT(!fmx_ok(&c));
        ASSERT_STR_EQ(c.reply.error.code, "STEER_GRANT_REVOKED");
        fmx_end(&c);
        json_init(&items);
        json_set_array(&items);
        fmx_item(&item, "field-agent", "after revoke", "", "key-rev-1");
        (void)json_push_back(&items, &item);
        json_free(&item);
        ASSERT(fmx_send(&c, gid, &items));
        json_free(&items);
        ASSERT(!fmx_ok(&c));
        ASSERT_STR_EQ(c.reply.error.code, "STEER_GRANT_REVOKED");
        fmx_end(&c);
        /* The revoked send posted nothing. */
        ASSERT_EQ(fmx_mail_count(), 0);
        /* Revoking an unknown id is a refusal, not a silent accept. */
        fmx_begin(&c, FMX_GRANT_PATH, "zcl.fleet_steer_grant.v1");
        (void)json_push_kv_str(&c.input, "action", "revoke");
        (void)json_push_kv_str(&c.input,
                               "id",
                               "ffffffffffffffffffffffffffffffff");
        ASSERT(fmx_run(&c, zcl_native_handle_fleet_steer_grant));
        ASSERT(!fmx_ok(&c));
        ASSERT_STR_EQ(c.reply.error.code, "STEER_GRANT_UNKNOWN");
        fmx_end(&c);
        /* Expired rows refuse even with full scope. */
        fmx_seed_expired("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa");
        fmx_brief(&c, "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", 0);
        ASSERT(fmx_run(&c, zcl_native_handle_fleet_steer_brief));
        ASSERT(!fmx_ok(&c));
        ASSERT_STR_EQ(c.reply.error.code, "STEER_GRANT_EXPIRED");
        fmx_end(&c);
        fmx_restore();
        PASS();
    }

_test_next:;
    fmx_restore();
    return failures;
}

static int fmx_t_revoke_cancels_queued(void)
{
    int failures = 0;

    TEST("steer: revoke cancels queued work and blocks later stages") {
        struct fmx_call s, q, c, b;
        struct json_value items, item;
        const struct json_value *v;
        char gid[64];
        fmx_isolate("revoke_claim");
        ASSERT(fmx_mint("brief,send,evidence", gid, sizeof(gid)));
        json_init(&items);
        json_set_array(&items);
        fmx_item(&item, "field-agent", "revoke probe body",
                 "revoke-claim-ref", "key-revoke-claim-1");
        (void)json_push_back(&items, &item);
        json_free(&item);
        ASSERT(fmx_send(&s, gid, &items));
        json_free(&items);
        ASSERT(fmx_ok(&s));
        fmx_end(&s);
        ASSERT_EQ(fmx_mail_count(), 1);
        /* The authenticated task/ref lands on the queue under the same
         * ref so the worker journey can complete it. */
        fmx_begin(&q, "dev.agent.queue", "zcl.agent_queue.v1");
        (void)json_push_kv_str(&q.input, "action", "post");
        (void)json_push_kv_str(&q.input, "kind", "leaf");
        (void)json_push_kv_str(&q.input, "name", "revoke-claim-ref");
        ASSERT(fmx_run(&q, zcl_native_handle_dev_agent_queue));
        ASSERT(fmx_ok(&q));
        fmx_end(&q);
        /* Revoke: the grant dies and the queued row goes with it. */
        fmx_begin(&c, FMX_GRANT_PATH, "zcl.fleet_steer_grant.v1");
        (void)json_push_kv_str(&c.input, "action", "revoke");
        (void)json_push_kv_str(&c.input, "id", gid);
        ASSERT(fmx_run(&c, zcl_native_handle_fleet_steer_grant));
        ASSERT(fmx_ok(&c));
        v = json_get(&c.reply.data, "cancelled");
        ASSERT(v && v->type == JSON_INT && json_get_int(v) == 1);
        fmx_end(&c);
        /* The queued row is gone: an explicit cancel finds nothing, and
         * a later claim has nothing to adopt. Running rows still need
         * their worker's explicit authority (CANCEL_RUNNING elsewhere). */
        fmx_begin(&q, "dev.agent.queue", "zcl.agent_queue.v1");
        (void)json_push_kv_str(&q.input, "action", "cancel");
        (void)json_push_kv_str(&q.input, "name", "revoke-claim-ref");
        ASSERT(fmx_run(&q, zcl_native_handle_dev_agent_queue));
        ASSERT(!fmx_ok(&q));
        ASSERT_STR_EQ(q.reply.error.code, "CANCEL_NOT_FOUND");
        fmx_end(&q);
        /* Later stages stay blocked on the revoked credential. */
        json_init(&items);
        json_set_array(&items);
        fmx_item(&item, "field-agent", "after revoke", "",
                 "key-revoke-claim-2");
        (void)json_push_back(&items, &item);
        json_free(&item);
        ASSERT(fmx_send(&s, gid, &items));
        json_free(&items);
        ASSERT(!fmx_ok(&s));
        ASSERT_STR_EQ(s.reply.error.code, "STEER_GRANT_REVOKED");
        fmx_end(&s);
        fmx_brief(&b, gid, 0);
        ASSERT(fmx_run(&b, zcl_native_handle_fleet_steer_brief));
        ASSERT(!fmx_ok(&b));
        ASSERT_STR_EQ(b.reply.error.code, "STEER_GRANT_REVOKED");
        fmx_end(&b);
        fmx_restore();
        PASS();
    }

_test_next:;
    fmx_restore();
    return failures;
}

/* Send one item and return the refusal code, or "" when it was accepted.
 * Isolation and the grant belong to the caller so one root can carry the
 * whole table. */
static void fmx_ref_attempt(const char *gid, const char *ref, const char *key,
                            char *out, size_t cap)
{
    struct fmx_call c;
    struct json_value items, item;
    const struct json_value *rows, *row, *v;
    out[0] = '\0';
    json_init(&items);
    json_set_array(&items);
    fmx_item(&item, "field-agent", "ref grammar probe", ref, key);
    (void)json_push_back(&items, &item);
    json_free(&item);
    if (!fmx_send(&c, gid, &items)) {
        json_free(&items);
        snprintf(out, cap, "CALL_FAILED");
        return;
    }
    json_free(&items);
    rows = fmx_arr(&c, "items");
    row = rows ? json_at(rows, 0) : NULL;
    v = row ? json_get(row, "state") : NULL;
    if (v && v->type == JSON_STR && strcmp(json_get_str(v), "refused") == 0) {
        v = json_get(row, "error");
        snprintf(out, cap, "%s",
                 (v && v->type == JSON_STR) ? json_get_str(v) : "?");
    }
    fmx_end(&c);
}

/* The ingress ref grammar is the queue's grammar. A ref accepted here that
 * the queue would refuse is work that can be delivered and never dispatched,
 * which is exactly what this proves cannot happen. The hostile refs are the
 * ones a live adversarial run actually sent at the deployed endpoint. */
static int fmx_t_ref_grammar(void)
{
    int failures = 0;

    TEST("steer: a ref the queue would refuse never becomes mail") {
        static const char *hostile[] = {
            "../../etc/passwd",   /* path-shaped: the live stress case */
            "a/b",                /* any second segment at all */
            "",                   /* empty names nothing */
            ".",                  /* resolves to the run directory itself */
            "..",                 /* resolves to its parent */
            "has space",
            "star*",              /* legal for a recipient, never for a ref */
            "/absolute",
            "back\\slash",
            "ref;semi",
            NULL
        };
        char gid[64], code[64];
        size_t i;
        char toolong[ZCL_DEVAGENT_NAME_MAX + 2];
        fmx_isolate("ref_grammar");
        ASSERT(fmx_mint("brief,send,evidence", gid, sizeof(gid)));

        for (i = 0; hostile[i]; i++) {
            char key[64];
            snprintf(key, sizeof(key), "key-hostile-%zu", i);
            fmx_ref_attempt(gid, hostile[i], key, code, sizeof(code));
            /* Typed, and specifically about the ref. */
            ASSERT(strcmp(code, "BAD_REF") == 0);
            /* The one grammar: ingress and queue agree on every case. */
            ASSERT(!zcl_devagent_name_ok(hostile[i]));
        }

        /* One byte over the bound is refused; exactly at the bound is not. */
        memset(toolong, 'a', sizeof(toolong) - 1);
        toolong[sizeof(toolong) - 1] = '\0';
        fmx_ref_attempt(gid, toolong, "key-long", code, sizeof(code));
        ASSERT(strcmp(code, "BAD_REF") == 0);
        ASSERT(!zcl_devagent_name_ok(toolong));

        /* Not one of them wrote a row. */
        ASSERT_EQ(fmx_mail_count(), 0);

        {
            static const char *legal[] = {
                "ext-181257",        /* the refs this fleet actually uses */
                "probe-20260917",
                "acc-20260917T183948Z",
                "x",
                "dot.ted",
                "under_score",
                NULL
            };
            long long expect = 0;
            char maxlen[ZCL_DEVAGENT_NAME_MAX + 1];
            memset(maxlen, 'b', sizeof(maxlen) - 1);
            maxlen[sizeof(maxlen) - 1] = '\0';
            for (i = 0; legal[i]; i++) {
                char key[64];
                snprintf(key, sizeof(key), "key-legal-%zu", i);
                fmx_ref_attempt(gid, legal[i], key, code, sizeof(code));
                ASSERT(code[0] == '\0');
                ASSERT(zcl_devagent_name_ok(legal[i]));
                expect++;
                ASSERT_EQ(fmx_mail_count(), expect);
            }
            fmx_ref_attempt(gid, maxlen, "key-maxlen", code, sizeof(code));
            ASSERT(code[0] == '\0');
            ASSERT(zcl_devagent_name_ok(maxlen));
        }
        fmx_restore();
        PASS();
    }

_test_next:;
    fmx_restore();
    return failures;
}

/* The sender binding stamped on the mail row under `ref`, or "" when the
 * row carries none. Read through the real mail leaf, never by parsing a
 * path, so the field has to survive post and pull to be seen here. */
static void fmx_row_binding(const char *ref, char *out, size_t cap)
{
    struct fmx_call p;
    const struct json_value *rows;
    out[0] = '\0';
    fmx_begin(&p, "dev.agent.mail", "zcl.agent_mail.v1");
    (void)json_push_kv_str(&p.input, "action", "pull");
    (void)json_push_kv_int(&p.input, "since", 0);
    zcl_native_handle_dev_agent_mail(&p.request, &p.reply);
    rows = fmx_ok(&p) ? fmx_arr(&p, "rows") : NULL;
    if (rows) {
        size_t n = json_size(rows), i;
        for (i = 0; i < n; i++) {
            const struct json_value *r = json_at(rows, i);
            const struct json_value *f = r ? json_get(r, "ref") : NULL;
            const struct json_value *b =
                r ? json_get(r, "sender_binding") : NULL;
            if (!f || f->type != JSON_STR ||
                strcmp(json_get_str(f), ref) != 0)
                continue;
            if (b && b->type == JSON_STR && json_get_str(b))
                (void)snprintf(out, cap, "%s", json_get_str(b));
        }
    }
    fmx_end(&p);
}

/* What one claimed send answered. `code` is the batch refusal code, or ""
 * when the batch passed; `items` records whether per-item outcomes came
 * back at all, which is how a case tells a batch refused outright from one
 * that reached the items — a reconcile is an item-level answer. */
struct fmx_claim_out {
    char code[64];
    bool items;
};

/* One directive under `ref`, sent with `grant` while claiming `from`. */
static void fmx_claim(const char *grant, const char *from, const char *ref,
                      const char *key, struct fmx_claim_out *o)
{
    struct fmx_call c;
    struct json_value items, item;
    memset(o, 0, sizeof(*o));
    json_init(&items);
    json_set_array(&items);
    fmx_item(&item, "field-agent", "check the water pump", ref, key);
    (void)json_push_back(&items, &item);
    json_free(&item);
    if (fmx_send_from(&c, grant, from, &items)) {
        if (!fmx_ok(&c))
            (void)snprintf(o->code, sizeof(o->code), "%s",
                           c.reply.error.code);
        o->items = fmx_arr(&c, "items") != NULL;
    }
    fmx_end(&c);
    json_free(&items);
}

/* ── the sender is the credential, not the claim ────────────────────────
 *
 * Proven live on the public endpoint 2026-09-17: one grant labelled
 * "impersonation-probe" successfully sent as itself, as "A", as
 * "acceptance-20260917" and as "owner", and the receiver dispatched on the
 * claimed name. Each case below is one of those doors, closed. */
static int fmx_t_sender_binding(void)
{
    int failures = 0;

    TEST("steer: a grant sends as its own label and stamps the row") {
        struct fmx_claim_out o;
        char gid[64], bind[80], want[80];
        fmx_isolate("sender_own");
        ASSERT(fmx_mint_as("send", "steer-victim", gid, sizeof(gid)));
        fmx_claim(gid, "steer-victim", "own-a", "k-own-a", &o);
        ASSERT_STR_EQ(o.code, "");
        ASSERT_EQ(fmx_mail_count(), 1);
        /* The stamp is on the row, it is this grant's own, and it is not
         * the grant id: a mail row crosses hosts and the id is the bearer
         * secret. */
        fmx_row_binding("own-a", bind, sizeof(bind));
        ASSERT_EQ((long long)strlen(bind),
                  (long long)ZCL_FLEET_STEER_BINDING_HEX);
        ASSERT(strcmp(bind, gid) != 0);
        ASSERT(zcl_fleet_steer_sender_binding(gid, "steer-victim", want,
                                              sizeof(want)));
        ASSERT_STR_EQ(bind, want);
        fmx_restore();
        PASS();
    }

    /* Proven live on 2026-09-18: a host store holding 82 older grant ids
     * made the receiver answer STEER_GRANT_UNKNOWN for a grant minted a
     * minute earlier, because admission kept only the FIRST 64 ids of the
     * whole file. Other labels must not spend a sender's bound, and within
     * one label the newest ids are the ones kept. */
    TEST("steer: a live grant after 70 others still admits its own row") {
        struct fmx_claim_out o;
        char gid[64], bind[80], label[32];
        int i;
        fmx_isolate("sender_late_grant");
        for (i = 0; i < 70; i++) {
            (void)snprintf(label, sizeof(label), "filler-%d", i);
            ASSERT(fmx_mint_as("send", label, gid, sizeof(gid)));
        }
        for (i = 0; i < 70; i++)
            ASSERT(fmx_mint_as("send", "steer-late", gid, sizeof(gid)));
        fmx_claim(gid, "steer-late", "late-a", "k-late-a", &o);
        ASSERT_STR_EQ(o.code, "");
        fmx_row_binding("late-a", bind, sizeof(bind));
        ASSERT(zcl_fleet_steer_grant_binding_live("steer-late", bind,
                                                  "send") == NULL);
        fmx_restore();
        PASS();
    }

    TEST("steer: a grant claiming another sender is refused, not rewritten") {
        struct fmx_claim_out o;
        char victim[64], actor[64];
        fmx_isolate("sender_impersonation");
        ASSERT(fmx_mint_as("send", "steer-victim", victim, sizeof(victim)));
        ASSERT(fmx_mint_as("send", "steer-actor", actor, sizeof(actor)));
        /* Both identities exist. The question is never whether the victim
         * exists — it is whether the actor may speak as it. */
        fmx_claim(actor, "steer-victim", "imp-a", "k-imp-a", &o);
        ASSERT_STR_EQ(o.code, "STEER_SENDER_MISMATCH");
        ASSERT(!o.items);
        ASSERT_EQ(fmx_mail_count(), 0);
        /* Rewriting the claim to the credential's own name would have
         * posted a row and told the caller nothing. The same actor sending
         * as itself is accepted, so what was refused is the claim. */
        fmx_claim(actor, "steer-actor", "act-a", "k-act-a", &o);
        ASSERT_STR_EQ(o.code, "");
        ASSERT_EQ(fmx_mail_count(), 1);
        fmx_restore();
        PASS();
    }

    TEST("steer: a bearer stating no sender is refused, never defaulted") {
        struct fmx_claim_out o;
        char gid[64];
        fmx_isolate("sender_absent");
        ASSERT(fmx_mint_as("send", "steer-victim", gid, sizeof(gid)));
        fmx_claim(gid, NULL, "abs-a", "k-abs-a", &o);
        ASSERT_STR_EQ(o.code, "STEER_SENDER_UNSTATED");
        ASSERT(!o.items);
        ASSERT_EQ(fmx_mail_count(), 0);
        fmx_restore();
        PASS();
    }

    TEST("steer: a grant minted without a label names no sender") {
        struct fmx_claim_out o;
        char gid[64];
        fmx_isolate("sender_unlabelled");
        ASSERT(fmx_mint_as("send", NULL, gid, sizeof(gid)));
        fmx_claim(gid, "steer-victim", "unl-a", "k-unl-a", &o);
        ASSERT_STR_EQ(o.code, "STEER_GRANT_UNLABELLED");
        ASSERT_EQ(fmx_mail_count(), 0);
        fmx_restore();
        PASS();
    }

    TEST("steer: a replay under another sender is refused before reconcile") {
        struct fmx_claim_out o;
        char victim[64], actor[64], bind[80], want[80];
        fmx_isolate("sender_replay");
        ASSERT(fmx_mint_as("send", "steer-victim", victim, sizeof(victim)));
        ASSERT(fmx_mint_as("send", "steer-actor", actor, sizeof(actor)));
        fmx_claim(victim, "steer-victim", "rep-a", "k-rep", &o);
        ASSERT_STR_EQ(o.code, "");
        ASSERT_EQ(fmx_mail_count(), 1);
        /* The same idempotency key under a different claimed sender.
         * Reconcile would answer with the victim's recorded accept and let
         * the actor inherit the victim's row, so the binding has to refuse
         * before idempotency is consulted at all. */
        fmx_claim(actor, "steer-victim", "rep-a", "k-rep", &o);
        ASSERT_STR_EQ(o.code, "STEER_SENDER_MISMATCH");
        /* No per-item answer means no reconcile was reached: a duplicate
         * would have come back as an item carrying duplicate:true. */
        ASSERT(!o.items);
        ASSERT_EQ(fmx_mail_count(), 1);
        /* And nothing was inherited: the one row still carries the
         * victim's own stamp. */
        fmx_row_binding("rep-a", bind, sizeof(bind));
        ASSERT(zcl_fleet_steer_sender_binding(victim, "steer-victim", want,
                                              sizeof(want)));
        ASSERT_STR_EQ(bind, want);
        fmx_restore();
        PASS();
    }

    TEST("steer: revoked, wrong-scope and malformed senders keep their codes") {
        struct fmx_claim_out o;
        char gid[64], evidence[64];
        fmx_isolate("sender_existing_refusals");
        ASSERT(fmx_mint_as("send", "steer-victim", gid, sizeof(gid)));
        /* A malformed name is malformed whatever credential carries it,
         * and is not reported as an impersonation. */
        fmx_claim(gid, "../../etc/passwd", "mal-a", "k-mal", &o);
        ASSERT_STR_EQ(o.code, "BAD_INPUT");
        ASSERT_EQ(fmx_mail_count(), 0);
        /* Scope is authority too, and it still refuses before identity. */
        ASSERT(fmx_mint_as("evidence", "steer-evidence-only", evidence,
                           sizeof(evidence)));
        fmx_claim(evidence, "steer-evidence-only", "scope-a", "k-scope", &o);
        ASSERT_STR_EQ(o.code, "STEER_GRANT_SCOPE");
        /* A dead credential speaks for nobody, not even for itself. */
        {
            struct fmx_call r;
            fmx_begin(&r, FMX_GRANT_PATH, "zcl.fleet_steer_grant.v1");
            (void)json_push_kv_str(&r.input, "action", "revoke");
            (void)json_push_kv_str(&r.input, "id", gid);
            ASSERT(fmx_run(&r, zcl_native_handle_fleet_steer_grant));
            ASSERT(fmx_ok(&r));
            fmx_end(&r);
        }
        fmx_claim(gid, "steer-victim", "rev-a", "k-rev", &o);
        ASSERT_STR_EQ(o.code, "STEER_GRANT_REVOKED");
        ASSERT_EQ(fmx_mail_count(), 0);
        fmx_restore();
        PASS();
    }

    TEST("steer: the local operator sends as itself, with no grant stamp") {
        struct fmx_claim_out o;
        char bind[80];
        fmx_isolate("sender_operator");
        /* No grant: dispatch already gated this on AUTH_OPERATOR and the
         * sender is the operator. The row carries no grant stamp, which is
         * exactly why a receiver will not dispatch work on it. */
        fmx_claim(NULL, "steer-operator", "op-a", "k-op", &o);
        ASSERT_STR_EQ(o.code, "");
        ASSERT_EQ(fmx_mail_count(), 1);
        fmx_row_binding("op-a", bind, sizeof(bind));
        ASSERT_STR_EQ(bind, "");
        fmx_restore();
        PASS();
    }

_test_next:;
    fmx_restore();
    return failures;
}

static int fmx_t_board_absent(void)
{
    int failures = 0;

    TEST("steer: board evidence without a node is unavailable, not empty") {
        struct fmx_call e;
        char gid[64];
        fmx_isolate("board_absent");
        ASSERT(fmx_mint("brief,send,evidence", gid, sizeof(gid)));
        fmx_evidence(&e, gid, "board", "deadbeef");
        ASSERT(fmx_run(&e, zcl_native_handle_fleet_steer_evidence));
        ASSERT(!fmx_ok(&e));
        ASSERT_STR_EQ(e.reply.error.code, "EVIDENCE_UNAVAILABLE");
        fmx_end(&e);
        fmx_restore();
        PASS();
    }

_test_next:;
    fmx_restore();
    return failures;
}

/* ── workers, capacity, stale directives, budget ─────────────────────────
 *
 * The brief's worker view must be evidence, never a name list: an entry
 * exists only for an identity that answered as a receiver or worker, or
 * for this host's own resident; unknown numbers are null with a reason;
 * and a big history can never make the reply fail wholesale. */

/* Write (or append) one file under the isolated state root, creating its
 * directory. rel is "<dir>/<file>" relative to <state>/z23/dev. */
static void fmx_state_file(const char *dirrel, const char *file,
                           const char *text, bool append)
{
    char dir[1024], path[1400];
    int n = snprintf(dir, sizeof(dir), "%s/z23/dev/%s/", g_fmx_state, dirrel);
    size_t base = strlen(g_fmx_state) + 1, i;
    if (n <= 0 || (size_t)n >= sizeof(dir))
        fmx_fixture_fail("state dir exceeds bound");
    /* Each component in turn: the private-directory helper makes one
     * level, never a chain. */
    for (i = base; dir[i]; i++) {
        if (dir[i] != '/')
            continue;
        dir[i] = '\0';
        if (!platform_private_directory_ensure(dir))
            fmx_fixture_fail("cannot create an isolated state dir");
        dir[i] = '/';
    }
    dir[n - 1] = '\0';
    n = snprintf(path, sizeof(path), "%s/%s", dir, file);
    if (n <= 0 || (size_t)n >= sizeof(path))
        fmx_fixture_fail("state file exceeds bound");
    FILE *f = fopen(path, append ? "a" : "w");
    if (!f)
        fmx_fixture_fail("cannot open an isolated state file");
    if (fputs(text, f) < 0)
        fmx_fixture_fail("cannot write an isolated state file");
    if (fclose(f) != 0)
        fmx_fixture_fail("cannot finish an isolated state file");
}

/* The mail dir chain exists before fmx_seed_inbox, which makes one level
 * only. An empty stream file is no row at all. */
static void fmx_prime_mail(void)
{
    fmx_state_file("mail", "inbox.prime.jsonl", "", true);
}

/* "now" as the mail leaf stamps it, so a seeded row is fresh evidence. */
static void fmx_now_ts(char *out, size_t cap)
{
    struct tm tm_utc;
    time_t now = platform_time_wall_time_t();
    if (!platform_time_utc_tm(now, &tm_utc) ||
        strftime(out, cap, "%Y-%m-%dT%H:%M:%SZ", &tm_utc) == 0)
        fmx_fixture_fail("cannot format the current time");
}

/* The workers[] entry named name, or NULL. */
static const struct json_value *fmx_worker(const struct fmx_call *c,
                                           const char *name)
{
    const struct json_value *arr = fmx_arr(c, "workers");
    size_t n = arr ? json_size(arr) : 0u, i;
    for (i = 0; i < n; i++) {
        const struct json_value *w = json_at(arr, i);
        const struct json_value *v = w ? json_get(w, "name") : NULL;
        if (v && v->type == JSON_STR && strcmp(json_get_str(v), name) == 0)
            return w;
    }
    return NULL;
}

static const char *fmx_wstr(const struct json_value *o, const char *key)
{
    const struct json_value *v = o ? json_get(o, key) : NULL;
    return v && v->type == JSON_STR && json_get_str(v) ? json_get_str(v) : "";
}

/* -1 when absent, not an int, or null — callers check null separately. */
static long long fmx_wint(const struct json_value *o, const char *key)
{
    const struct json_value *v = o ? json_get(o, key) : NULL;
    return v && v->type == JSON_INT ? json_get_int(v) : -1;
}

static bool fmx_wnull(const struct json_value *o, const char *key)
{
    const struct json_value *v = o ? json_get(o, key) : NULL;
    return v && v->type == JSON_NULL;
}

static bool fmx_blocker_has(const struct fmx_call *c, const char *needle)
{
    const struct json_value *arr = fmx_arr(c, "blockers");
    size_t n = arr ? json_size(arr) : 0u, i;
    for (i = 0; i < n; i++) {
        const struct json_value *b = json_at(arr, i);
        if (b && b->type == JSON_STR && strstr(json_get_str(b), needle))
            return true;
    }
    return false;
}

static int fmx_t_capacity_unknown(void)
{
#if defined(_WIN32)
    return 0;
#else
    int failures = 0;

    TEST("steer: a queue nobody could read is unknown capacity, not zero") {
        struct fmx_call b;
        const struct json_value *cap;
        char dir[1200];
        fmx_isolate("capacity_unknown");
        /* queue.jsonl as a directory: the queue sibling cannot read it
         * and refuses, exactly like an unreadable queue in the field. */
        fmx_state_file("queue", "pool.txt", "", false);
        (void)snprintf(dir, sizeof(dir), "%s/z23/dev/queue/queue.jsonl",
                       g_fmx_state);
        ASSERT(platform_private_directory_ensure(dir));
        fmx_brief(&b, NULL, 0);
        ASSERT(fmx_run(&b, zcl_native_handle_fleet_steer_brief));
        ASSERT(fmx_ok(&b));
        ASSERT(fmx_missing_has(&b, "dev.agent.queue"));
        cap = fmx_get(&b, "capacity");
        ASSERT(cap && cap->type == JSON_OBJ);
        ASSERT(json_get(cap, "known") &&
               !json_get_bool(json_get(cap, "known")));
        ASSERT(fmx_wnull(cap, "pool_total"));
        ASSERT(fmx_wnull(cap, "pool_free"));
        ASSERT(fmx_wnull(cap, "queued"));
        ASSERT(fmx_wnull(cap, "running"));
        ASSERT(strstr(fmx_wstr(cap, "reason"), "sibling_refused") != NULL);
        fmx_end(&b);
        /* A readable queue reports real numbers and known:true. */
        ASSERT(rmdir(dir) == 0);
        fmx_brief(&b, NULL, 0);
        ASSERT(fmx_run(&b, zcl_native_handle_fleet_steer_brief));
        ASSERT(fmx_ok(&b));
        cap = fmx_get(&b, "capacity");
        ASSERT(json_get_bool(json_get(cap, "known")));
        ASSERT(fmx_wint(cap, "queued") == 0);
        ASSERT(fmx_wnull(cap, "reason"));
        fmx_end(&b);
        fmx_restore();
        PASS();
    }

_test_next:;
    fmx_restore();
    return failures;
#endif
}

static int fmx_t_worker_answers(void)
{
    int failures = 0;

    TEST("steer: a refusal answer makes that worker blocked with its reason") {
        struct fmx_call b;
        const struct json_value *w;
        fmx_isolate("worker_refused");
        fmx_prime_mail();
        fmx_seed_inbox("box-a", "2026-09-16T00:00:00Z", 4, "box-a",
                       FMX_SENDER, "problem",
                       "receiver=box-a\\nstate=refused\\nsrc=inbox\\n"
                       "reason=WORKSPACE_DIRTY\\ndetail=tracked paths "
                       "diverge\\n",
                       "job-refused");
        fmx_brief(&b, NULL, 0);
        ASSERT(fmx_run(&b, zcl_native_handle_fleet_steer_brief));
        ASSERT(fmx_ok(&b));
        w = fmx_worker(&b, "box-a");
        ASSERT(w != NULL);
        ASSERT_STR_EQ(fmx_wstr(w, "state"), "blocked");
        ASSERT(strstr(fmx_wstr(w, "reason"), "WORKSPACE_DIRTY") != NULL);
        ASSERT(strstr(fmx_wstr(w, "reason"), "job-refused") != NULL);
        ASSERT_STR_EQ(fmx_wstr(w, "source"), "mail");
        ASSERT(json_get_bool(json_get(w, "self_reported")));
        ASSERT_STR_EQ(fmx_wstr(w, "current_ref"), "job-refused");
        /* Nothing reported: every resource is null with its reason. */
        ASSERT(fmx_wnull(w, "load1_centi"));
        ASSERT(fmx_wnull(w, "mem_avail_kib"));
        ASSERT(fmx_wnull(w, "disk_free_kib"));
        ASSERT(fmx_wnull(w, "host"));
        ASSERT(fmx_wnull(w, "tokens_last_run"));
        ASSERT_STR_EQ(fmx_wstr(w, "resources_reason"), "not reported");
        fmx_end(&b);
        fmx_restore();
        PASS();
    }

    TEST("steer: an accept answer populates the worker's workspace") {
        struct fmx_call b;
        const struct json_value *w;
        char now[32], body[1024];
        fmx_isolate("worker_accept");
        fmx_prime_mail();
        fmx_seed_inbox("box-b", "2026-09-16T00:00:00Z", 5, "box-b",
                       FMX_SENDER, "claim",
                       "receiver=box-b\\nstate=accepted\\nsrc=inbox\\n"
                       "queue_seq=3\\nstage=running\\nkind=file\\n"
                       "gate=steer_gate\\nbrief_sha3=aa\\n"
                       "workspace_selector=receiver\\nworkspace_sha3=bb\\n"
                       "workspace_head=0123456789abcdef\\n"
                       "workspace_tree_sha3=cc\\nresolved_sha3=dd\\n"
                       "host=box-b.lan\\nload1_centi=250\\n"
                       "mem_avail_kib=4096\\n",
                       "job-accept");
        fmx_brief(&b, NULL, 0);
        ASSERT(fmx_run(&b, zcl_native_handle_fleet_steer_brief));
        ASSERT(fmx_ok(&b));
        w = fmx_worker(&b, "box-b");
        ASSERT(w != NULL);
        ASSERT_STR_EQ(fmx_wstr(w, "workspace_head"), "0123456789abcdef");
        ASSERT_STR_EQ(fmx_wstr(w, "workspace_selector"), "receiver");
        ASSERT_STR_EQ(fmx_wstr(w, "current_ref"), "job-accept");
        ASSERT_STR_EQ(fmx_wstr(w, "stage"), "running");
        ASSERT_STR_EQ(fmx_wstr(w, "host"), "box-b.lan");
        ASSERT(fmx_wint(w, "load1_centi") == 250);
        ASSERT(fmx_wint(w, "mem_avail_kib") == 4096);
        ASSERT(fmx_wnull(w, "disk_free_kib"));
        ASSERT_STR_EQ(fmx_wstr(w, "last_seen_ts"), "2026-09-16T00:00:00Z");
        ASSERT(fmx_wint(w, "age_s") > 0);
        /* Claimed (stage=running) and no terminal result: working. */
        ASSERT_STR_EQ(fmx_wstr(w, "state"), "working");
        fmx_end(&b);
        /* The worker's result row closes the ref and states its cost. */
        fmx_now_ts(now, sizeof(now));
        (void)snprintf(body, sizeof(body), "%s",
                       "ref=job-accept\\nworker=box-b\\nsession=s1\\n"
                       "model=m\\nattempt=1\\nterminal=pass\\n"
                       "candidate=c\\ngate=pass\\nrc=0\\ntokens=1500\\n"
                       "wall_ms=42\\n");
        fmx_seed_inbox("box-b", now, 6, "box-b", "*", "result", body,
                       "job-accept");
        fmx_brief(&b, NULL, 0);
        ASSERT(fmx_run(&b, zcl_native_handle_fleet_steer_brief));
        ASSERT(fmx_ok(&b));
        w = fmx_worker(&b, "box-b");
        ASSERT(w != NULL);
        ASSERT(fmx_wint(w, "tokens_last_run") == 1500);
        ASSERT(fmx_wint(w, "tokens_total") == 1500);
        /* Fresh terminal evidence, nothing open: idle, and the workspace
         * the accept named is still reported. */
        ASSERT_STR_EQ(fmx_wstr(w, "state"), "idle");
        ASSERT_STR_EQ(fmx_wstr(w, "workspace_head"), "0123456789abcdef");
        fmx_end(&b);
        fmx_restore();
        PASS();
    }

_test_next:;
    fmx_restore();
    return failures;
}

static int fmx_t_queued_stale(void)
{
    int failures = 0;

    TEST("steer: a sent ref with no receiver evidence past 120 s blocks") {
        struct fmx_call b;
        const struct json_value *changes, *ch = NULL, *ev;
        size_t i;
        fmx_isolate("queued_stale");
        fmx_prime_mail();
        /* One directive this host sent long ago: its outbox row plus the
         * send receipt naming the same seq and recipient. */
        fmx_seed_inbox("self", "2026-01-01T00:00:00Z", 7, FMX_SENDER,
                       "silent-box", "directive", "do the thing",
                       "stale-ref");
        fmx_state_file("steer", "sent.jsonl",
                       "{\"key\":\"k-stale\",\"seq\":7,\"to\":\"silent-box\","
                       "\"ref\":\"stale-ref\"}\n",
                       true);
        fmx_brief(&b, NULL, 0);
        ASSERT(fmx_run(&b, zcl_native_handle_fleet_steer_brief));
        ASSERT(fmx_ok(&b));
        changes = fmx_arr(&b, "changes");
        ASSERT_STR_EQ(fmx_change_state(changes, FMX_SENDER, "stale-ref"),
                      "queued");
        for (i = 0; changes && i < json_size(changes); i++) {
            if (strcmp(fmx_wstr(json_at(changes, i), "ref"), "stale-ref") ==
                0)
                ch = json_at(changes, i);
        }
        ASSERT(ch != NULL);
        ASSERT(fmx_wint(ch, "queued_age_s") > 120);
        ASSERT(fmx_blocker_has(&b, "stale-ref"));
        ASSERT(fmx_blocker_has(&b, "no receiver evidence after"));
        ev = fmx_get(&b, "evidence");
        ASSERT(fmx_wint(ev, "queued_stale_after_s") == 120);
        /* The silent recipient never answered, so it is no worker. */
        ASSERT(fmx_worker(&b, "silent-box") == NULL);
        fmx_end(&b);
        /* Its answer under the same ref is receiver evidence: the blocker
         * goes away and the row is acknowledged. */
        fmx_seed_inbox("silent-box", "2026-01-01T00:01:00Z", 1, "silent-box",
                       FMX_SENDER, "claim",
                       "receiver=silent-box\\nstate=accepted\\nstage=queued\\n",
                       "stale-ref");
        fmx_brief(&b, NULL, 0);
        ASSERT(fmx_run(&b, zcl_native_handle_fleet_steer_brief));
        ASSERT(fmx_ok(&b));
        ASSERT_STR_EQ(fmx_change_state(fmx_arr(&b, "changes"), FMX_SENDER,
                                       "stale-ref"),
                      "acknowledged");
        ASSERT(!fmx_blocker_has(&b, "stale-ref"));
        /* Accepted into its queue but never claimed: unknown, not
         * working. */
        ASSERT_STR_EQ(fmx_wstr(fmx_worker(&b, "silent-box"), "state"),
                      "unknown");
        fmx_end(&b);
        fmx_restore();
        PASS();
    }

    TEST("steer: many stale directives spell eight and count the rest") {
        struct fmx_call b;
        const struct json_value *bl;
        char ref[32], line[160];
        long long i;
        size_t n, spelled = 0;
        fmx_isolate("queued_stale_many");
        fmx_prime_mail();
        for (i = 0; i < 11; i++) {
            (void)snprintf(ref, sizeof(ref), "many-%02lld", i);
            fmx_seed_inbox("self", "2026-01-01T00:00:00Z", 30 + i,
                           FMX_SENDER, "deaf-box", "directive", "work",
                           ref);
            (void)snprintf(line, sizeof(line),
                           "{\"key\":\"k-%lld\",\"seq\":%lld,"
                           "\"to\":\"deaf-box\",\"ref\":\"%s\"}\n",
                           i, 30 + i, ref);
            fmx_state_file("steer", "sent.jsonl", line, true);
        }
        fmx_brief(&b, NULL, 0);
        ASSERT(fmx_run(&b, zcl_native_handle_fleet_steer_brief));
        ASSERT(fmx_ok(&b));
        bl = fmx_arr(&b, "blockers");
        n = bl ? json_size(bl) : 0u;
        for (i = 0; (size_t)i < n; i++) {
            if (strstr(json_get_str(json_at(bl, (size_t)i)), "to deaf-box"))
                spelled++;
        }
        ASSERT(spelled == 8);
        ASSERT(fmx_blocker_has(&b, "3 more directives sent from here"));
        fmx_end(&b);
        fmx_restore();
        PASS();
    }

_test_next:;
    fmx_restore();
    return failures;
}

/* The outcome projection of one reaped name through the real queue leaf. */
static const struct json_value *fmx_outcome_named(const struct fmx_call *q,
                                                  const char *name)
{
    const struct json_value *arr = fmx_arr(q, "outcomes");
    size_t n = arr ? json_size(arr) : 0u, i;
    for (i = 0; i < n; i++) {
        if (strcmp(fmx_wstr(json_at(arr, i), "name"), name) == 0)
            return json_at(arr, i);
    }
    return NULL;
}

static int fmx_t_receipt_tokens(void)
{
    int failures = 0;

    TEST("steer: receipt tokens reach the brief through the queue outcome") {
        struct fmx_call q, b;
        const struct json_value *w, *o;
        fmx_isolate("receipt_tokens");
        fmx_state_file("queue", "queue.jsonl",
                       "{\"seq\":1,\"ts\":\"2026-09-15T00:00:00Z\","
                       "\"kind\":\"file\",\"name\":\"tokjob\",\"group\":\"g\","
                       "\"path\":\"p\",\"brief\":\"\",\"model\":\"\","
                       "\"attempt\":1,\"state\":\"running\",\"worktree\":\"\","
                       "\"pid_or_unit\":\"\",\"started\":0}\n"
                       "{\"seq\":2,\"ts\":\"2026-09-15T00:00:00Z\","
                       "\"kind\":\"file\",\"name\":\"nojob\",\"group\":\"g\","
                       "\"path\":\"p\",\"brief\":\"\",\"model\":\"\","
                       "\"attempt\":1,\"state\":\"running\",\"worktree\":\"\","
                       "\"pid_or_unit\":\"\",\"started\":0}\n",
                       false);
        fmx_state_file("engine/tokjob/a1", "receipt.json",
                       "{\"verdict\":\"pass\",\"worker\":\"wk\","
                       "\"tokens\":1234,\"wall_ms\":99,\"ts\":1}\n",
                       false);
        fmx_state_file("engine/tokjob/a1", "run.out", "rc=0\n", false);
        /* No receipt at all: its cost is unknown, never zero. */
        fmx_state_file("engine/nojob/a1", "run.out", "rc=1\n", false);
        fmx_begin(&q, "dev.agent.queue", "zcl.agent_queue.v1");
        (void)json_push_kv_str(&q.input, "action", "reap");
        ASSERT(fmx_run(&q, zcl_native_handle_dev_agent_queue));
        ASSERT(fmx_ok(&q));
        o = fmx_outcome_named(&q, "tokjob");
        ASSERT(fmx_wint(o, "tokens_used") == 1234);
        ASSERT(fmx_wint(o, "wall_ms") == 99);
        o = fmx_outcome_named(&q, "nojob");
        ASSERT(fmx_wnull(o, "tokens_used"));
        ASSERT(fmx_wnull(o, "wall_ms"));
        fmx_end(&q);
        /* The resident worker's lock file exists (nobody holds it), so
         * the local resident is reported; its usage is the receipt's. */
        fmx_state_file("queue", "worker.lock", "", false);
        fmx_brief(&b, NULL, 0);
        ASSERT(fmx_run(&b, zcl_native_handle_fleet_steer_brief));
        ASSERT(fmx_ok(&b));
        w = fmx_worker(&b, "local");
        ASSERT(w != NULL);
        ASSERT_STR_EQ(fmx_wstr(w, "source"), "local");
        ASSERT(!json_get_bool(json_get(w, "self_reported")));
        ASSERT(fmx_wint(w, "tokens_last_run") == 1234);
        ASSERT(fmx_wint(w, "tokens_total") == 1234);
        /* Nothing running and no lock held: never "working" or "idle". */
        ASSERT_STR_EQ(fmx_wstr(w, "state"), "unknown");
        fmx_end(&b);
        fmx_restore();
        PASS();
    }

_test_next:;
    fmx_restore();
    return failures;
}

static int fmx_t_process_not_work(void)
{
    int failures = 0;

    TEST("steer: a name or a live process alone is never a working worker") {
        struct fmx_call b;
        const struct json_value *w;
        size_t i, n;
        bool named = false;
        fmx_isolate("process_not_work");
        fmx_prime_mail();
        /* A correspondent that never answered as a receiver: a name in
         * agents[], and no worker. */
        fmx_seed_inbox("chatty", "2026-09-16T00:00:00Z", 3, "chatty",
                       FMX_SENDER, "note", "hello there", "chat-1");
#if !defined(_WIN32)
        char lockpath[1400];
        int fd;
        fmx_state_file("queue", "worker.lock", "", false);
        (void)snprintf(lockpath, sizeof(lockpath),
                       "%s/z23/dev/queue/worker.lock", g_fmx_state);
        fd = open(lockpath, O_RDWR);
        ASSERT(fd >= 0);
        ASSERT(flock(fd, LOCK_EX | LOCK_NB) == 0);
        /* The receiver's cumulative intake record is history for the
         * reason, never a current block. */
        fmx_state_file("receive", "intake.state",
                       "position=\nfailures=2\nlast_error=MAIL_READ_FAILED\n",
                       false);
#endif
        fmx_brief(&b, NULL, 0);
        ASSERT(fmx_run(&b, zcl_native_handle_fleet_steer_brief));
        ASSERT(fmx_ok(&b));
        n = fmx_arr(&b, "agents") ? json_size(fmx_arr(&b, "agents")) : 0u;
        for (i = 0; i < n; i++) {
            const struct json_value *a = json_at(fmx_arr(&b, "agents"), i);
            named = named || strcmp(json_get_str(a), "chatty") == 0;
        }
        ASSERT(named);
        ASSERT(fmx_worker(&b, "chatty") == NULL);
#if !defined(_WIN32)
        /* A resident holds worker.lock: a live process with nothing
         * queued or running is idle at most, never working. */
        w = fmx_worker(&b, "local");
        ASSERT(w != NULL);
        ASSERT_STR_EQ(fmx_wstr(w, "state"), "idle");
        ASSERT(fmx_wint(w, "age_s") == 0);
        ASSERT(strstr(fmx_wstr(w, "reason"), "2 past intake failure") !=
               NULL);
        ASSERT(strstr(fmx_wstr(w, "reason"), "MAIL_READ_FAILED") != NULL);
        ASSERT(fmx_wnull(w, "current_ref"));
        (void)flock(fd, LOCK_UN);
        (void)close(fd);
#else
        w = NULL;
        (void)w;
#endif
        fmx_end(&b);
        fmx_restore();
        PASS();
    }

_test_next:;
    fmx_restore();
    return failures;
}

static int fmx_t_large_history(void)
{
    int failures = 0;

    TEST("steer: a large mail history is bounded, never a failed brief") {
        struct fmx_call b;
        char body[2048], name[32], ref[32], ts[32], quotes[400], peer[32];
        const struct json_value *workers, *cut;
        long long i;
        fmx_isolate("large_history");
        fmx_prime_mail();
        /* A first line of 150 quote marks: every change lead is 160 chars
         * that each escape to two bytes, so 100 changes alone overrun the
         * budget and the trim must fire. */
        for (i = 0; i < 150; i++)
            memcpy(quotes + i * 2, "\\\"", 2);
        quotes[300] = '\0';
        for (i = 0; i < 3000; i++) {
            (void)snprintf(name, sizeof(name), "box-%03lld", i % 200);
            (void)snprintf(ref, sizeof(ref), "job-%04lld", i);
            (void)snprintf(ts, sizeof(ts), "2026-09-16T%02lld:%02lld:%02lldZ",
                           (i / 3600) % 24, (i / 60) % 60, i % 60);
            (void)snprintf(body, sizeof(body),
                           "note=%s\\nreceiver=%s\\nstate=accepted\\n"
                           "src=inbox\\n"
                           "queue_seq=%lld\\nstage=queued\\nkind=file\\n"
                           "gate=a_long_gate_name_for_padding\\n"
                           "brief_sha3=%064lld\\nworkspace_selector=receiver\\n"
                           "workspace_head=%040lld\\n",
                           quotes, name, i, i, i);
            /* Eight transport streams (the mail leaf reads at most 16),
             * each carrying many receivers' answers. */
            (void)snprintf(peer, sizeof(peer), "bulk-%lld", i % 8);
            fmx_seed_inbox(peer, ts, i + 1, name, FMX_SENDER, "claim", body,
                           ref);
        }
        fmx_brief(&b, NULL, 0);
        (void)json_push_kv_int(&b.input, "limit", 100);
        ASSERT(fmx_run(&b, zcl_native_handle_fleet_steer_brief));
        ASSERT(fmx_ok(&b));
        workers = fmx_arr(&b, "workers");
        ASSERT(workers != NULL);
        ASSERT(json_size(workers) <= 16);
        ASSERT(json_get_bool(fmx_get(&b, "workers_truncated")));
        cut = json_get(&b.reply.data, "budget_truncated");
        ASSERT(cut && cut->type == JSON_OBJ);
        ASSERT(fmx_wint(cut, "changes") > 0);
        ASSERT(fmx_arr(&b, "changes") != NULL);
        /* The whole reply data fits well inside the 64 KiB response
         * budget, envelope included. */
        ASSERT(json_write(&b.reply.data, NULL, 0) <= 49152u);
        fmx_end(&b);
        fmx_restore();
        PASS();
    }

_test_next:;
    fmx_restore();
    return failures;
}

/* ── sessions[]: one row per coding-agent session ───────────────────────
 *
 * A session announces itself with a `note` row under ref presence-<ROLE>
 * whose body is the strict presence.v1 line. Every mail row on a box says
 * from=<unix user>, so the ROLE comes from the ref, never from `from`. */

#define FMX_SHA256 \
    "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"

/* A stamp `ago` seconds before now, shaped as the mail leaf stamps it. */
static void fmx_ts_ago(long long ago, char *out, size_t cap)
{
    struct tm tm_utc;
    time_t t = platform_time_wall_time_t() - (time_t)ago;
    if (!platform_time_utc_tm(t, &tm_utc) ||
        strftime(out, cap, "%Y-%m-%dT%H:%M:%SZ", &tm_utc) == 0)
        fmx_fixture_fail("cannot format a past time");
}

/* One presence.v1 row for role on host, stamped `ago` seconds back. */
static void fmx_seed_presence(const char *role, const char *host,
                              long long ago, long long seq)
{
    char ts[32], body[768], ref[64];
    fmx_ts_ago(ago, ts, sizeof(ts));
    (void)snprintf(body, sizeof(body),
                   "presence.v1; host=%s; session=sess-%s-1; pid=4242; "
                   "started=2026-09-18T01:00:00Z; role=%s; observed=%s; "
                   "task=fleet.steer sessions; phase=build; "
                   "source=main@720a41afcf; binary_sha256=" FMX_SHA256
                   "; workers=muse-%s; spend=1200",
                   host, role, role, ts, role);
    (void)snprintf(ref, sizeof(ref), "presence-%s", role);
    fmx_seed_inbox("peer", ts, seq, "box-user", "*", "note", body, ref);
}

/* The sessions[] entry for role, or NULL. */
static const struct json_value *fmx_session(const struct fmx_call *c,
                                            const char *role)
{
    const struct json_value *arr = fmx_arr(c, "sessions");
    size_t n = arr ? json_size(arr) : 0u, i;
    for (i = 0; i < n; i++) {
        const struct json_value *s = json_at(arr, i);
        if (strcmp(fmx_wstr(s, "role"), role) == 0)
            return s;
    }
    return NULL;
}

/* True when the whole serialized reply data contains needle. */
static bool fmx_reply_has(const struct fmx_call *c, const char *needle)
{
    size_t len = json_write(&c->reply.data, NULL, 0);
    char *buf = (char *)calloc(len + 1, 1);
    bool hit;
    if (!buf)
        fmx_fixture_fail("cannot allocate the reply text");
    (void)json_write(&c->reply.data, buf, len + 1);
    hit = strstr(buf, needle) != NULL;
    free(buf);
    return hit;
}

/* True when the string array arr holds s. */
static bool fmx_arr_has(const struct json_value *arr, const char *s)
{
    size_t n = arr && arr->type == JSON_ARR ? json_size(arr) : 0u, i;
    for (i = 0; i < n; i++) {
        const struct json_value *v = json_at(arr, i);
        if (v && v->type == JSON_STR && strcmp(json_get_str(v), s) == 0)
            return true;
    }
    return false;
}

static int fmx_t_sessions(void)
{
    int failures = 0;

    TEST("steer: a fresh presence row is a live session with its fields") {
        struct fmx_call b;
        const struct json_value *s;
        fmx_isolate("session_live");
        fmx_prime_mail();
        fmx_seed_presence("A", "box-a.lan", 30, 1);
        fmx_brief(&b, NULL, 0);
        ASSERT(fmx_run(&b, zcl_native_handle_fleet_steer_brief));
        ASSERT(fmx_ok(&b));
        s = fmx_session(&b, "A");
        ASSERT(s != NULL);
        ASSERT_STR_EQ(fmx_wstr(s, "state"), "live");
        ASSERT_STR_EQ(fmx_wstr(s, "format"), "presence.v1");
        ASSERT_STR_EQ(fmx_wstr(s, "host"), "box-a.lan");
        ASSERT_STR_EQ(fmx_wstr(s, "session"), "sess-A-1");
        ASSERT(fmx_wint(s, "pid") == 4242);
        ASSERT_STR_EQ(fmx_wstr(s, "started"), "2026-09-18T01:00:00Z");
        ASSERT_STR_EQ(fmx_wstr(s, "task"), "fleet.steer sessions");
        ASSERT_STR_EQ(fmx_wstr(s, "phase"), "build");
        ASSERT_STR_EQ(fmx_wstr(s, "source"), "main@720a41afcf");
        ASSERT_STR_EQ(fmx_wstr(s, "binary_sha256"), FMX_SHA256);
        ASSERT(fmx_wint(s, "spend_tokens") == 1200);
        ASSERT(fmx_wint(s, "age_s") >= 30 && fmx_wint(s, "age_s") < 900);
        ASSERT(strlen(fmx_wstr(s, "last_observed_ts")) == 20);
        ASSERT_STR_EQ(fmx_wstr(s, "observed_via"), "dev.agent.mail pull");
        ASSERT(fmx_wint(s, "mail_seq") == 1);
        fmx_end(&b);
        fmx_restore();
        PASS();
    }

    TEST("steer: a two-hour-old presence row is stale with its age") {
        struct fmx_call b;
        const struct json_value *s;
        fmx_isolate("session_stale");
        fmx_prime_mail();
        fmx_seed_presence("B", "box-b.lan", 7200, 2);
        fmx_brief(&b, NULL, 0);
        ASSERT(fmx_run(&b, zcl_native_handle_fleet_steer_brief));
        ASSERT(fmx_ok(&b));
        s = fmx_session(&b, "B");
        ASSERT(s != NULL);
        ASSERT_STR_EQ(fmx_wstr(s, "state"), "stale");
        ASSERT(fmx_wint(s, "age_s") >= 7200);
        ASSERT(strstr(fmx_wstr(s, "reason"), "older than") != NULL);
        ASSERT_STR_EQ(fmx_wstr(s, "host"), "box-b.lan");
        fmx_end(&b);
        fmx_restore();
        PASS();
    }

    TEST("steer: an expected role with no presence row reads UNKNOWN") {
        struct fmx_call b;
        const struct json_value *s;
        fmx_isolate("session_absent");
        fmx_prime_mail();
        fmx_seed_presence("A", "box-a.lan", 30, 1);
        fmx_seed_presence("E2", "box-e.lan", 30, 2);
        fmx_brief(&b, NULL, 0);
        ASSERT(fmx_run(&b, zcl_native_handle_fleet_steer_brief));
        ASSERT(fmx_ok(&b));
        ASSERT(fmx_session(&b, "B") != NULL);
        ASSERT(fmx_session(&b, "C") != NULL);
        ASSERT(fmx_session(&b, "E2") != NULL);
        s = fmx_session(&b, "D");
        ASSERT(s != NULL);
        ASSERT_STR_EQ(fmx_wstr(s, "state"), "UNKNOWN");
        ASSERT_STR_EQ(fmx_wstr(s, "format"), "UNKNOWN");
        ASSERT_STR_EQ(fmx_wstr(s, "host"), "UNKNOWN");
        ASSERT_STR_EQ(fmx_wstr(s, "pid"), "UNKNOWN");
        ASSERT_STR_EQ(fmx_wstr(s, "age_s"), "UNKNOWN");
        ASSERT_STR_EQ(fmx_wstr(s, "last_observed_ts"), "UNKNOWN");
        ASSERT(fmx_int(&b, "sessions_total") == 5);
        fmx_end(&b);
        fmx_restore();
        PASS();
    }

    TEST("steer: a malformed presence body leaves every field UNKNOWN") {
        struct fmx_call b;
        const struct json_value *s;
        char ts[32];
        fmx_isolate("session_malformed");
        fmx_prime_mail();
        fmx_ts_ago(10, ts, sizeof(ts));
        fmx_seed_inbox("peer", ts, 3, "box-user", "*", "note",
                       "PRESENCE C on box-c pid=12; host=box-c; ;;==;",
                       "presence-C");
        fmx_seed_inbox("peer", ts, 4, "box-user", "*", "note",
                       "presence.v1;;; =x; host=; pid=12ab; started=yday; "
                       "binary_sha256=XYZ; host",
                       "presence-D");
        fmx_brief(&b, NULL, 0);
        ASSERT(fmx_run(&b, zcl_native_handle_fleet_steer_brief));
        ASSERT(fmx_ok(&b));
        s = fmx_session(&b, "C");
        ASSERT(s != NULL);
        ASSERT_STR_EQ(fmx_wstr(s, "format"), "unparsed");
        ASSERT_STR_EQ(fmx_wstr(s, "host"), "UNKNOWN");
        ASSERT_STR_EQ(fmx_wstr(s, "pid"), "UNKNOWN");
        ASSERT_STR_EQ(fmx_wstr(s, "session"), "UNKNOWN");
        s = fmx_session(&b, "D");
        ASSERT(s != NULL);
        ASSERT_STR_EQ(fmx_wstr(s, "format"), "presence.v1");
        ASSERT_STR_EQ(fmx_wstr(s, "host"), "UNKNOWN");
        ASSERT_STR_EQ(fmx_wstr(s, "pid"), "UNKNOWN");
        ASSERT_STR_EQ(fmx_wstr(s, "started"), "UNKNOWN");
        ASSERT_STR_EQ(fmx_wstr(s, "binary_sha256"), "UNKNOWN");
        ASSERT(fmx_arr_has(json_get(s, "refused_fields"), "pid"));
        fmx_end(&b);
        fmx_restore();
        PASS();
    }

    TEST("steer: a credential-shaped presence value is never echoed") {
        struct fmx_call b;
        const struct json_value *s;
        char ts[32];
        fmx_isolate("session_secret");
        fmx_prime_mail();
        fmx_ts_ago(10, ts, sizeof(ts));
        fmx_seed_inbox("peer", ts, 5, "box-user", "*", "note",
                       "presence.v1; host=box-a.lan; "
                       "session=Bearer ZZtopsecretZZ; "
                       "task=sk-ant-api03-QQleakQQ; phase=hunter2password; "
                       "source=0123456789abcdef0123456789abcdef; pid=77",
                       "presence-A");
        fmx_brief(&b, NULL, 0);
        ASSERT(fmx_run(&b, zcl_native_handle_fleet_steer_brief));
        ASSERT(fmx_ok(&b));
        s = fmx_session(&b, "A");
        ASSERT(s != NULL);
        ASSERT_STR_EQ(fmx_wstr(s, "host"), "box-a.lan");
        ASSERT(fmx_wint(s, "pid") == 77);
        ASSERT_STR_EQ(fmx_wstr(s, "session"), "UNKNOWN");
        ASSERT_STR_EQ(fmx_wstr(s, "task"), "UNKNOWN");
        ASSERT_STR_EQ(fmx_wstr(s, "phase"), "UNKNOWN");
        ASSERT_STR_EQ(fmx_wstr(s, "source"), "UNKNOWN");
        ASSERT(fmx_arr_has(json_get(s, "refused_fields"), "session"));
        /* Not in sessions[], and not in any change lead either. */
        ASSERT(!fmx_reply_has(&b, "ZZtopsecretZZ"));
        ASSERT(!fmx_reply_has(&b, "QQleakQQ"));
        ASSERT(!fmx_reply_has(&b, "hunter2"));
        ASSERT(!fmx_reply_has(&b, "0123456789abcdef0123456789abcdef"));
        fmx_end(&b);
        fmx_restore();
        PASS();
    }

    TEST("steer: a session links the Muse workers reporting its host") {
        struct fmx_call b;
        const struct json_value *s, *sp;
        char now[32], old[32];
        fmx_isolate("session_workers");
        fmx_prime_mail();
        fmx_seed_presence("A", "box-a.lan", 30, 1);
        fmx_now_ts(now, sizeof(now));
        fmx_ts_ago(60, old, sizeof(old));
        /* muse-a stated its host in an older claim; its newest row is a
         * result that names none, and the host still links it. */
        fmx_seed_inbox("box-a", old, 7, "box-a", FMX_SENDER, "claim",
                       "receiver=muse-a\\nstate=accepted\\nstage=running\\n"
                       "host=box-a.lan\\n",
                       "job-a");
        fmx_seed_inbox("box-a", now, 8, "box-a", "*", "result",
                       "ref=job-a\\nworker=muse-a\\ngate=pass\\nrc=0\\n"
                       "tokens=1500\\n",
                       "job-a");
        fmx_seed_inbox("box-a", now, 9, "box-a", FMX_SENDER, "claim",
                       "receiver=muse-a2\\nstate=accepted\\n"
                       "host=box-a.lan\\nload1_centi=250\\n"
                       "mem_avail_kib=4096\\n",
                       "job-a2");
        fmx_seed_inbox("box-f", now, 10, "box-f", FMX_SENDER, "claim",
                       "receiver=muse-f\\nstate=accepted\\nhost=box-f.lan\\n",
                       "job-f");
        fmx_brief(&b, NULL, 0);
        ASSERT(fmx_run(&b, zcl_native_handle_fleet_steer_brief));
        ASSERT(fmx_ok(&b));
        s = fmx_session(&b, "A");
        ASSERT(s != NULL);
        ASSERT(fmx_arr_has(json_get(s, "workers"), "muse-a"));
        ASSERT(fmx_arr_has(json_get(s, "workers"), "muse-a2"));
        ASSERT(!fmx_arr_has(json_get(s, "workers"), "muse-f"));
        ASSERT(fmx_wint(s, "load1_centi") == 250);
        ASSERT(fmx_wint(s, "mem_avail_kib") == 4096);
        ASSERT_STR_EQ(fmx_wstr(s, "disk_free_kib"), "UNKNOWN");
        ASSERT_STR_EQ(fmx_wstr(s, "resources_from"), "muse-a2");
        ASSERT_STR_EQ(fmx_wstr(fmx_worker(&b, "muse-a"), "host"),
                      "box-a.lan");
        /* B has no host: nothing links, resources unknown. */
        s = fmx_session(&b, "B");
        ASSERT(s != NULL);
        ASSERT(json_size(json_get(s, "workers")) == 0);
        ASSERT_STR_EQ(fmx_wstr(s, "load1_centi"), "UNKNOWN");
        sp = json_get(&b.reply.data, "muse_spend");
        ASSERT(sp != NULL);
        ASSERT(fmx_wint(sp, "tokens_total") == 1500);
        ASSERT_STR_EQ(fmx_wstr(sp, "reservations"), "UNKNOWN");
        fmx_end(&b);
        fmx_restore();
        PASS();
    }

_test_next:;
    fmx_restore();
    return failures;
}

int test_fleet_steer(void);
int test_fleet_steer(void)
{
    int failures = 0;

    node_rpc_client_set_test_hook(fmx_no_node);
    failures += fmx_t_register();
    failures += fmx_t_brief_empty();
    failures += fmx_t_send_flow();
    failures += fmx_t_brief_changes();
    failures += fmx_t_evidence();
    failures += fmx_t_duplicate();
    failures += fmx_t_lifecycle();
    failures += fmx_t_sent_needs_receiver();
    failures += fmx_t_sent_local_ack();
    failures += fmx_t_grants();
    failures += fmx_t_revoke_cancels_queued();
    failures += fmx_t_ref_grammar();
    failures += fmx_t_sender_binding();
    failures += fmx_t_board_absent();
    failures += fmx_t_capacity_unknown();
    failures += fmx_t_worker_answers();
    failures += fmx_t_queued_stale();
    failures += fmx_t_receipt_tokens();
    failures += fmx_t_process_not_work();
    failures += fmx_t_large_history();
    failures += fmx_t_sessions();

    /* No ASSERT lives in this function, so no goto needs the label: the
     * hook is always cleared on the single fall-through path. */
    node_rpc_client_set_test_hook(NULL);
    fmx_restore();
    if (failures == 0)
        printf("test_fleet_steer: all passed\n");
    else
        printf("test_fleet_steer: %d FAILED\n", failures);
    return failures;
}
