/* Copyright 2026 Rhett Creighton - Apache License 2.0
 * Purpose: C23 corpus census core proofs (counting, exclusions, assembly). */
#include "test/test_core.h"

#include "base/hex.h"
#include "base/safe_alloc.h"
#include "vcs/zcode_c23_corpus.h"
#include "vcs/zcode_c23_corpus_census.h"

#include <stdlib.h>
#include <string.h>

/* Frozen after the first green run; these pin the canonical lineage/shard
 * roots the census derives (same KAT style as the corpus projection). */
static const char alpha_lineage_kat[] =
    "41f00c587b5e59732c4c999dae2f3c09d8bb9b85bfaf602b2554282e0142cbf8";
static const char assembly_shard_root_kat[] =
    "8d5bbb228156e6e9fd0f0f54f9692c22b05778d4dc43261988d4ca6940a2c99a";

static void fill(uint8_t root[32], uint8_t value)
{
    memset(root, value, 32);
}

static bool root_is_zero(const uint8_t root[32])
{
    uint8_t acc = 0;
    for (size_t i = 0; i < 32; i++) acc |= root[i];
    return acc == 0;
}

static const char alpha_src[] =
    "/* alpha core */\n"
    "int alpha_add(int a, int b) {\n"
    "    return a + b;\n"
    "}\n"
    "\n"
    "int alpha_sub(int a, int b) {\n"
    "    return a - b;\n"
    "}\n";
static const char alpha_test_src[] =
    "static void test_alpha(void) {\n"
    "    ASSERT(alpha_add(1, 2) == 3);\n"
    "    ASSERT(alpha_sub(4, 1) == 3);\n"
    "}\n";
static const char beta_src[] =
    "int beta_mul(int a, int b) {\n"
    "    return a * b;\n"
    "}\n";
static const char beta_test_src[] =
    "static void test_beta(void) {\n"
    "    ASSERT(beta_mul(2, 3) == 6);\n"
    "}\n";
static const char gamma_src[] =
    "int gamma_id(int a) {\n"
    "    return a;\n"
    "}\n";
static const char gamma_test_src[] =
    "static void test_gamma(void) {\n"
    "    ASSERT(gamma_id(5) == 5);\n"
    "}\n";
static const char delta_src[] =
    "int delta_dec(int a) {\n"
    "    return a - 1;\n"
    "}\n";
static const char delta_test_src[] =
    "static void test_delta(void) {\n"
    "    ASSERT(delta_dec(2) == 1);\n"
    "}\n";
static const char vend_src[] =
    "int vend(void) { return 9; }\n";
static const char gen_src[] =
    "/* GENERATED by ztool; do not edit */\n"
    "int gen_x(void) { return 7; }\n";
static const char dup_src[] =
    "int dup_one(void) {\n"
    "    return 1;\n"
    "}\n"
    "int dup_two(void) {\n"
    "    return 2;\n"
    "}\n";
static const char dup_test_src[] =
    "static void test_dup(void) {\n"
    "    ASSERT(dup_one() == 1);\n"
    "}\n";
static const char extra_src[] =
    "int extra_three(void) {\n"
    "    return 3;\n"
    "}\n"
    "int extra_four(void) {\n"
    "    return 4;\n"
    "}\n";
static const char extra_test_src[] =
    "static void test_extra(void) {\n"
    "    ASSERT(extra_three() == 3);\n"
    "}\n";

static struct vcs_zcode_corpus_census_file file_of(const char *path,
                                                   const char *content)
{
    struct vcs_zcode_corpus_census_file f = {
        .path = path,
        .bytes = (const uint8_t *)content,
        .len = strlen(content),
    };
    f.declared_size = f.len;
    return f;
}

/* A fully-bound scope: every root nonzero, evidence complete, permissive
 * license, human-authored. Tests mutate one field at a time. */
static void scope_defaults(
    struct vcs_zcode_corpus_census_scope_input *in, const char *name,
    const struct vcs_zcode_corpus_census_file *files, size_t file_count)
{
    memset(in, 0, sizeof(*in));
    in->name = name;
    in->source_kind = VCS_ZCODE_SOURCE_HUMAN_AUTHORED;
    in->license_spdx = "Apache-2.0";
    fill(in->license_root, 0x11);
    in->evidence_mask = VCS_ZCODE_C23_EVIDENCE_REQUIRED_MASK;
    fill(in->release_root, 0x12);
    fill(in->passport_root, 0x13);
    fill(in->proof_root, 0x14);
    fill(in->source_assignment_root, 0x15);
    fill(in->admission_root, 0x16);
    fill(in->possession_root, 0x17);
    in->release_sequence = 1;
    in->files = files;
    in->file_count = file_count;
}

static int test_counted_happy_path(void)
{
    int failures = 0;
    TEST("counted entry: all roots bound, evidence complete, tests present") {
        struct vcs_zcode_corpus_census census;
        vcs_zcode_corpus_census_init(&census);
        struct vcs_zcode_corpus_census_file files[] = {
            file_of("src/alpha.c", alpha_src),
            file_of("tests/test_alpha.c", alpha_test_src),
        };
        struct vcs_zcode_corpus_census_scope_input in;
        scope_defaults(&in, "zclassic23/alpha", files, 2);
        struct vcs_zcode_corpus_census_scope_result r;
        ASSERT(vcs_zcode_corpus_census_process_scope(&census, &in, &r));
        ASSERT_EQ(r.scope_exclusion_mask, 0u);
        ASSERT(r.entry.flags & VCS_ZCODE_C23_ENTRY_COUNTED);
        ASSERT(r.entry.flags & VCS_ZCODE_C23_ENTRY_DURABLE);
        ASSERT(!root_is_zero(r.entry.semantic_lineage_root));
        ASSERT(!root_is_zero(r.entry.possession_root));
        ASSERT_EQ(r.entry.release_sequence, 1u);
        ASSERT_EQ(r.entry.evidence_mask, VCS_ZCODE_C23_EVIDENCE_REQUIRED_MASK);
        /* alpha.c: 4 semantic of 8 lines; test: 3 semantic of 4 lines. */
        ASSERT_EQ(r.entry.production_loc, 4u);
        ASSERT_EQ(r.entry.test_loc, 3u);
        ASSERT_EQ(r.entry.physical_lines, 12u);
        ASSERT(r.entry.unique_semantic_units > 0);
        ASSERT_EQ(r.entry.unique_semantic_units, r.units_total);
        ASSERT_EQ(r.units_already_claimed, 0u);
        ASSERT_EQ(r.scanned_files, 2u);
        ASSERT_EQ(r.excluded_files, 0u);
        ASSERT(!r.overlap_duplicate);
        ASSERT(!r.possession_suppressed);
        char hex[65];
        zcl_hex_encode(r.entry.semantic_lineage_root, 32, hex);
        printf("census_lineage.alpha=%s\n", hex);
        uint8_t expected[32];
        ASSERT(zcl_hex_decode(alpha_lineage_kat, expected, 32));
        ASSERT(memcmp(r.entry.semantic_lineage_root, expected, 32) == 0);
        vcs_zcode_corpus_census_free(&census);
        PASS();
    } _test_next:;
    return failures;
}

static int test_file_exclusions(void)
{
    int failures = 0;
    TEST("vendor/generated/unsupported files are diagnostics, never counted") {
        struct vcs_zcode_corpus_census census;
        vcs_zcode_corpus_census_init(&census);
        struct vcs_zcode_corpus_census_file files[] = {
            file_of("src/alpha.c", alpha_src),
            file_of("vendor/vend.c", vend_src),
            file_of("src/gen_thing.c", gen_src),
            file_of("README.md", "# alpha\n"),
            file_of("tests/test_alpha.c", alpha_test_src),
        };
        struct vcs_zcode_corpus_census_scope_input in;
        scope_defaults(&in, "zclassic23/alpha", files, 5);
        struct vcs_zcode_corpus_census_scope_result r;
        ASSERT(vcs_zcode_corpus_census_process_scope(&census, &in, &r));
        ASSERT_EQ(r.scope_exclusion_mask, 0u);
        ASSERT(r.entry.flags & VCS_ZCODE_C23_ENTRY_COUNTED);
        ASSERT_EQ(r.scanned_files, 2u);
        ASSERT_EQ(r.excluded_files, 3u);
        /* vend.c and gen_thing.c each carry one semantic line; the
         * markdown line is prose the classifier reads as one semantic. */
        ASSERT_EQ(r.file_excluded_loc[VCS_ZCODE_CENSUS_FILE_VENDOR], 1u);
        ASSERT_EQ(r.file_excluded_loc[VCS_ZCODE_CENSUS_FILE_MECHANICAL], 1u);
        ASSERT_EQ(r.file_excluded_loc[VCS_ZCODE_CENSUS_FILE_UNSUPPORTED], 1u);
        /* Excluded content never enters the counted tallies. */
        ASSERT_EQ(r.entry.production_loc, 4u);
        ASSERT_EQ(r.entry.test_loc, 3u);
        ASSERT_EQ(r.entry.physical_lines, 12u);
        vcs_zcode_corpus_census_free(&census);
        PASS();
    } _test_next:;
    return failures;
}

static int test_large_file_band(void)
{
    int failures = 0;
    TEST("1 MiB..64 MiB files still count physical lines (no undercount)") {
        static const char line[] = "int band_fn(void) { return 1; }\n";
        size_t line_len = strlen(line);
        size_t reps = (1024u * 1024u) / line_len + 2u;
        size_t len = reps * line_len;
        char *buf = zcl_malloc(len, "test_census_band");
        ASSERT(buf != NULL);
        for (size_t i = 0; i < reps; i++)
            memcpy(buf + i * line_len, line, line_len);
        ASSERT(len > VCS_SCORE_MAX_FILE_BYTES);
        struct vcs_zcode_corpus_census census;
        vcs_zcode_corpus_census_init(&census);
        struct vcs_zcode_corpus_census_file files[] = {
            {.path = "src/band.c", .bytes = (const uint8_t *)buf,
             .len = len, .declared_size = len},
            file_of("tests/test_band.c", alpha_test_src),
        };
        struct vcs_zcode_corpus_census_scope_input in;
        scope_defaults(&in, "zclassic23/band", files, 2);
        struct vcs_zcode_corpus_census_scope_result r;
        ASSERT(vcs_zcode_corpus_census_process_scope(&census, &in, &r));
        ASSERT_EQ(r.scope_exclusion_mask, 0u);
        ASSERT(r.entry.flags & VCS_ZCODE_C23_ENTRY_COUNTED);
        ASSERT_EQ(r.excluded_files, 0u);
        ASSERT_EQ(r.scanned_files, 2u);
        /* Every repeated line is one semantic line. */
        ASSERT_EQ(r.entry.production_loc, (uint64_t)reps);
        ASSERT_EQ(r.entry.test_loc, 3u);
        ASSERT_EQ(r.entry.physical_lines, (uint64_t)reps + 4u);
        /* The unitizer never saw the band file: only the test units. */
        ASSERT(r.entry.unique_semantic_units > 0);
        ASSERT(r.entry.unique_semantic_units <= r.entry.test_loc);
        free(buf);
        vcs_zcode_corpus_census_free(&census);
        PASS();
    } _test_next:;
    return failures;
}

static int test_entry_exclusions(void)
{
    int failures = 0;
    TEST("entry exclusions: license, unassigned, incomplete, evidence") {
        struct vcs_zcode_corpus_census census;
        vcs_zcode_corpus_census_init(&census);
        struct vcs_zcode_corpus_census_file full[] = {
            file_of("src/alpha.c", alpha_src),
            file_of("tests/test_alpha.c", alpha_test_src),
        };
        struct vcs_zcode_corpus_census_file no_tests[] = {
            file_of("src/alpha.c", alpha_src),
        };
        struct vcs_zcode_corpus_census_scope_input in;
        struct vcs_zcode_corpus_census_scope_result r;

        /* Unsupported license: LOC zeroed, not counted, possession
         * suppressed and reported. */
        scope_defaults(&in, "zclassic23/gpl", full, 2);
        in.license_spdx = "GPL-3.0-only";
        ASSERT(vcs_zcode_corpus_census_process_scope(&census, &in, &r));
        ASSERT(r.scope_exclusion_mask & VCS_ZCODE_C23_EXCLUDE_LICENSE);
        ASSERT_EQ(vcs_zcode_corpus_census_primary_exclusion(
                      r.scope_exclusion_mask),
                  (uint32_t)VCS_ZCODE_C23_EXCLUDE_LICENSE);
        ASSERT(!(r.entry.flags & VCS_ZCODE_C23_ENTRY_COUNTED));
        ASSERT(!(r.entry.flags & VCS_ZCODE_C23_ENTRY_DURABLE));
        ASSERT_EQ(r.entry.production_loc, 0u);
        ASSERT_EQ(r.entry.test_loc, 0u);
        ASSERT(root_is_zero(r.entry.possession_root));
        ASSERT(r.possession_suppressed);
        /* Diagnostics stay populated (shard validation permits this). */
        ASSERT_EQ(r.entry.physical_lines, 12u);
        ASSERT(r.entry.unique_semantic_units > 0);

        /* Zero license_root is as unsupported as a bad identifier. */
        scope_defaults(&in, "zclassic23/noroot", full, 2);
        memset(in.license_root, 0, 32);
        ASSERT(vcs_zcode_corpus_census_process_scope(&census, &in, &r));
        ASSERT(r.scope_exclusion_mask & VCS_ZCODE_C23_EXCLUDE_LICENSE);

        /* Missing signed source assignment. */
        scope_defaults(&in, "zclassic23/unassigned", full, 2);
        memset(in.source_assignment_root, 0, 32);
        ASSERT(vcs_zcode_corpus_census_process_scope(&census, &in, &r));
        ASSERT(r.scope_exclusion_mask & VCS_ZCODE_C23_EXCLUDE_UNASSIGNED);

        /* No test semantic lines. */
        scope_defaults(&in, "zclassic23/untested", no_tests, 1);
        ASSERT(vcs_zcode_corpus_census_process_scope(&census, &in, &r));
        ASSERT(r.scope_exclusion_mask & VCS_ZCODE_C23_EXCLUDE_INCOMPLETE);
        ASSERT_EQ(vcs_zcode_corpus_census_primary_exclusion(
                      r.scope_exclusion_mask),
                  (uint32_t)VCS_ZCODE_C23_EXCLUDE_INCOMPLETE);

        /* Partial evidence. */
        scope_defaults(&in, "zclassic23/partial", full, 2);
        in.evidence_mask =
            VCS_ZCODE_C23_EVIDENCE_REQUIRED_MASK &
            ~VCS_ZCODE_C23_EVIDENCE_REPRODUCIBLE;
        ASSERT(vcs_zcode_corpus_census_process_scope(&census, &in, &r));
        ASSERT(r.scope_exclusion_mask &
               VCS_ZCODE_C23_EXCLUDE_REVIEW_REQUIRED);

        /* Vendor/mechanical source kinds. */
        scope_defaults(&in, "zclassic23/vendored", full, 2);
        in.source_kind = VCS_ZCODE_SOURCE_VENDOR_MATERIAL;
        ASSERT(vcs_zcode_corpus_census_process_scope(&census, &in, &r));
        ASSERT(r.scope_exclusion_mask & VCS_ZCODE_C23_EXCLUDE_VENDOR);
        scope_defaults(&in, "zclassic23/mechanical", full, 2);
        in.source_kind = VCS_ZCODE_SOURCE_MECHANICAL_GENERATION;
        ASSERT(vcs_zcode_corpus_census_process_scope(&census, &in, &r));
        ASSERT(r.scope_exclusion_mask & VCS_ZCODE_C23_EXCLUDE_MECHANICAL);

        /* Excluded scopes claim nothing: the same content processed again
         * is still entirely unclaimed. */
        scope_defaults(&in, "zclassic23/alpha", full, 2);
        ASSERT(vcs_zcode_corpus_census_process_scope(&census, &in, &r));
        ASSERT_EQ(r.scope_exclusion_mask, 0u);
        ASSERT_EQ(r.units_already_claimed, 0u);
        vcs_zcode_corpus_census_free(&census);
        PASS();
    } _test_next:;
    return failures;
}

static int test_cross_scope_overlap(void)
{
    int failures = 0;
    TEST(">=80% shared units exclude the later scope without claiming") {
        struct vcs_zcode_corpus_census census;
        vcs_zcode_corpus_census_init(&census);
        struct vcs_zcode_corpus_census_file dup_files[] = {
            file_of("src/dup.c", dup_src),
            file_of("tests/test_dup.c", dup_test_src),
        };
        struct vcs_zcode_corpus_census_file mixed_files[] = {
            file_of("src/dup.c", dup_src),
            file_of("src/extra.c", extra_src),
            file_of("tests/test_extra.c", extra_test_src),
        };
        struct vcs_zcode_corpus_census_scope_input in;
        struct vcs_zcode_corpus_census_scope_result first, mixed, copy,
            copy2;

        scope_defaults(&in, "zclassic23/dup", dup_files, 2);
        ASSERT(vcs_zcode_corpus_census_process_scope(&census, &in, &first));
        ASSERT_EQ(first.scope_exclusion_mask, 0u);

        /* Half the units shared: counted, only the new units credited. */
        scope_defaults(&in, "zclassic23/mixed", mixed_files, 3);
        ASSERT(vcs_zcode_corpus_census_process_scope(&census, &in, &mixed));
        ASSERT_EQ(mixed.scope_exclusion_mask, 0u);
        ASSERT(!mixed.overlap_duplicate);
        ASSERT(mixed.units_already_claimed > 0);
        ASSERT(mixed.units_already_claimed < mixed.units_total);
        ASSERT_EQ(mixed.entry.unique_semantic_units,
                  mixed.units_total - mixed.units_already_claimed);
        ASSERT_EQ(mixed.entry.unique_semantic_units,
                  first.units_total); /* identical file sets by symmetry */
        printf("census_overlap.first_total=%llu mixed_total=%llu "
               "mixed_claimed=%llu\n",
               (unsigned long long)first.units_total,
               (unsigned long long)mixed.units_total,
               (unsigned long long)mixed.units_already_claimed);

        /* Byte-identical copy: 100% overlap -> DUPLICATE, unclaimed. */
        scope_defaults(&in, "zclassic23/copy", dup_files, 2);
        ASSERT(vcs_zcode_corpus_census_process_scope(&census, &in, &copy));
        ASSERT(copy.overlap_duplicate);
        ASSERT(copy.scope_exclusion_mask & VCS_ZCODE_C23_EXCLUDE_DUPLICATE);
        ASSERT(!(copy.entry.flags & VCS_ZCODE_C23_ENTRY_COUNTED));
        ASSERT_EQ(copy.entry.unique_semantic_units, 0u);

        /* A second identical copy proves the duplicate claimed nothing:
         * its overlap is still measured against the ORIGINAL only. */
        scope_defaults(&in, "zclassic23/copy2", dup_files, 2);
        ASSERT(vcs_zcode_corpus_census_process_scope(&census, &in, &copy2));
        ASSERT(copy2.overlap_duplicate);
        ASSERT(copy2.scope_exclusion_mask & VCS_ZCODE_C23_EXCLUDE_DUPLICATE);
        ASSERT(memcmp(copy.entry.semantic_lineage_root,
                      copy2.entry.semantic_lineage_root, 32) == 0);
        vcs_zcode_corpus_census_free(&census);
        PASS();
    } _test_next:;
    return failures;
}

static int test_assemble(void)
{
    int failures = 0;
    TEST("assemble sorts by lineage root and totals the checkpoint binding") {
        struct vcs_zcode_corpus_census census;
        vcs_zcode_corpus_census_init(&census);
        struct vcs_zcode_corpus_census_scope_result results[4];
        struct vcs_zcode_corpus_census_scope_input in;

        struct vcs_zcode_corpus_census_file alpha_files[] = {
            file_of("src/alpha.c", alpha_src),
            file_of("tests/test_alpha.c", alpha_test_src),
        };
        struct vcs_zcode_corpus_census_file beta_files[] = {
            file_of("src/beta.c", beta_src),
            file_of("tests/test_beta.c", beta_test_src),
        };
        struct vcs_zcode_corpus_census_file gamma_files[] = {
            file_of("src/gamma.c", gamma_src),
            file_of("tests/test_gamma.c", gamma_test_src),
        };
        /* The excluded scope carries DISTINCT content: an identical copy
         * of a counted scope would collide on the lineage root, which
         * assembly deliberately refuses (see test_assemble_fails_closed). */
        struct vcs_zcode_corpus_census_file delta_files[] = {
            file_of("src/delta.c", delta_src),
            file_of("tests/test_delta.c", delta_test_src),
        };
        /* Deliberately processed out of eventual lineage order. */
        scope_defaults(&in, "zclassic23/gamma", gamma_files, 2);
        ASSERT(vcs_zcode_corpus_census_process_scope(
            &census, &in, &results[0]));
        scope_defaults(&in, "zclassic23/alpha", alpha_files, 2);
        ASSERT(vcs_zcode_corpus_census_process_scope(
            &census, &in, &results[1]));
        scope_defaults(&in, "zclassic23/beta", beta_files, 2);
        ASSERT(vcs_zcode_corpus_census_process_scope(
            &census, &in, &results[2]));
        scope_defaults(&in, "zclassic23/excluded", delta_files, 2);
        memset(in.source_assignment_root, 0, 32);
        ASSERT(vcs_zcode_corpus_census_process_scope(
            &census, &in, &results[3]));
        ASSERT_EQ(results[0].scope_exclusion_mask, 0u);
        ASSERT_EQ(results[1].scope_exclusion_mask, 0u);
        ASSERT_EQ(results[2].scope_exclusion_mask, 0u);
        ASSERT(results[3].scope_exclusion_mask &
               VCS_ZCODE_C23_EXCLUDE_UNASSIGNED);
        /* Excluded entries keep their diagnostic tallies. */
        ASSERT(results[3].entry.unique_semantic_units > 0);
        ASSERT(results[3].entry.physical_lines > 0);

        uint8_t family_root[32], moderation_root[32];
        fill(family_root, 0x32);
        fill(moderation_root, 0x33);
        struct vcs_zcode_corpus_census_assembly assembly;
        ASSERT_EQ(vcs_zcode_corpus_census_assemble(
                      results, 4, family_root, moderation_root, &assembly),
                  VCS_ZCODE_C23_OK);
        ASSERT_EQ(assembly.entry_count, 4u);
        for (size_t i = 1; i < assembly.entry_count; i++)
            ASSERT(memcmp(
                       assembly.entries[i - 1u].semantic_lineage_root,
                       assembly.entries[i].semantic_lineage_root, 32) < 0);
        ASSERT_EQ(vcs_zcode_c23_corpus_shard_v1_validate(&assembly.shard),
                  VCS_ZCODE_C23_OK);
        /* Hand-computed totals over the emitted entries. */
        ASSERT_EQ(assembly.total_entries, 4u);
        ASSERT_EQ(assembly.excluded_entries, 1u);
        ASSERT_EQ(assembly.production_loc, 4u + 2u + 2u);
        ASSERT_EQ(assembly.test_loc, 3u + 2u + 2u);
        ASSERT_EQ(assembly.durable_loc, 4u + 2u + 2u + 3u + 2u + 2u);
        ASSERT_EQ(assembly.physical_lines,
                  results[0].entry.physical_lines +
                  results[1].entry.physical_lines +
                  results[2].entry.physical_lines +
                  results[3].entry.physical_lines);
        ASSERT_EQ(assembly.unique_semantic_units,
                  results[0].entry.unique_semantic_units +
                  results[1].entry.unique_semantic_units +
                  results[2].entry.unique_semantic_units +
                  results[3].entry.unique_semantic_units);
        struct vcs_zcode_c23_corpus_rules_v1 rules;
        vcs_zcode_c23_corpus_rules_v1_default(&rules);
        uint8_t rules_root[32];
        ASSERT_EQ(vcs_zcode_c23_corpus_rules_v1_root(&rules, rules_root),
                  VCS_ZCODE_C23_OK);
        ASSERT(memcmp(assembly.rules_root, rules_root, 32) == 0);
        ASSERT(memcmp(assembly.shard.rules_root, rules_root, 32) == 0);
        uint8_t shard_root[32];
        ASSERT_EQ(vcs_zcode_c23_corpus_shard_v1_root(&assembly.shard,
                                                     shard_root),
                  VCS_ZCODE_C23_OK);
        char hex[65];
        zcl_hex_encode(shard_root, 32, hex);
        printf("census_assembly.shard=%s\n", hex);
        uint8_t expected[32];
        ASSERT(zcl_hex_decode(assembly_shard_root_kat, expected, 32));
        ASSERT(memcmp(shard_root, expected, 32) == 0);
        vcs_zcode_corpus_census_assembly_free(&assembly);
        ASSERT(assembly.entries == NULL);
        vcs_zcode_corpus_census_free(&census);
        PASS();
    } _test_next:;
    return failures;
}

static int test_assemble_fails_closed(void)
{
    int failures = 0;
    TEST("identical lineage roots fail assembly closed") {
        struct vcs_zcode_corpus_census census;
        vcs_zcode_corpus_census_init(&census);
        struct vcs_zcode_corpus_census_scope_result results[2];
        struct vcs_zcode_corpus_census_scope_input in;
        /* Two file-less, license-excluded scopes unitize to the same
         * empty wire and therefore collide on the lineage root. */
        scope_defaults(&in, "zclassic23/empty-a", NULL, 0);
        in.license_spdx = NULL;
        ASSERT(vcs_zcode_corpus_census_process_scope(
            &census, &in, &results[0]));
        scope_defaults(&in, "zclassic23/empty-b", NULL, 0);
        in.license_spdx = NULL;
        ASSERT(vcs_zcode_corpus_census_process_scope(
            &census, &in, &results[1]));
        ASSERT(!root_is_zero(results[0].entry.semantic_lineage_root));
        ASSERT(memcmp(results[0].entry.semantic_lineage_root,
                      results[1].entry.semantic_lineage_root, 32) == 0);
        uint8_t family_root[32], moderation_root[32];
        fill(family_root, 0x32);
        fill(moderation_root, 0x33);
        struct vcs_zcode_corpus_census_assembly assembly;
        ASSERT_EQ(vcs_zcode_corpus_census_assemble(
                      results, 2, family_root, moderation_root, &assembly),
                  VCS_ZCODE_C23_ORDER);
        ASSERT(assembly.entries == NULL);
        /* Zero family root is refused before any work. */
        uint8_t zero_root[32] = {0};
        ASSERT_EQ(vcs_zcode_corpus_census_assemble(
                      results, 1, zero_root, moderation_root, &assembly),
                  VCS_ZCODE_C23_ROOT);
        vcs_zcode_corpus_census_free(&census);
        PASS();
    } _test_next:;
    return failures;
}

static int test_caller_contract(void)
{
    int failures = 0;
    TEST("caller-contract violations are logged hard failures") {
        struct vcs_zcode_corpus_census census;
        vcs_zcode_corpus_census_init(&census);
        struct vcs_zcode_corpus_census_file files[] = {
            file_of("src/alpha.c", alpha_src),
            file_of("tests/test_alpha.c", alpha_test_src),
        };
        struct vcs_zcode_corpus_census_scope_input in;
        struct vcs_zcode_corpus_census_scope_result r;
        scope_defaults(&in, "zclassic23/bad-seq", files, 2);
        in.release_sequence = 0;
        ASSERT(!vcs_zcode_corpus_census_process_scope(&census, &in, &r));
        scope_defaults(&in, "zclassic23/bad-release", files, 2);
        memset(in.release_root, 0, 32);
        ASSERT(!vcs_zcode_corpus_census_process_scope(&census, &in, &r));
        ASSERT(!vcs_zcode_corpus_census_process_scope(&census, NULL, &r));
        ASSERT(!vcs_zcode_corpus_census_process_scope(NULL, &in, &r));
        vcs_zcode_corpus_census_free(&census);
        PASS();
    } _test_next:;
    return failures;
}

int test_zcode_c23_corpus_census(void)
{
    int failures = test_counted_happy_path() + test_file_exclusions() +
                   test_large_file_band() + test_entry_exclusions() +
                   test_cross_scope_overlap() + test_assemble() +
                   test_assemble_fails_closed() + test_caller_contract();
    printf("=== zcode_c23_corpus_census: %d failures ===\n", failures);
    return failures;
}
