/* Copyright 2026 Rhett Creighton - Apache License 2.0
 *
 * ZCL_CORE_SEAL_TREE + ZCL_CORE_SEAL_SECTION_ROWS — the sealed consensus core's
 * per-SECTION identity, as compile-time strings. AUTO-GENERATED by
 * `make core-seal-sections` (and by `make core-seal`) from the SECTION/TREE
 * lines of core/MANIFEST.sha3. Do not edit by hand.
 *
 * WHY IT IS NOT UNDER core/. Same reason as hotswap/core_seal_root.h: a mirror
 * living inside the sealed set would be part of its own input. It lives beside
 * the consumer, and test_hotswap_module's
 * "compiled section table matches core/MANIFEST.sha3" case proves the two
 * agree — a forgotten regeneration fails the hotswap_module test group.
 *
 * WHAT IT IS FOR. hotswap/core_seal_root.h carries ONE value: the flat ROOT
 * fold over every sealed file. It is a whole-tree pin — every module is
 * invalidated by a change to any of the 70 sealed files. These rows carry the
 * SAME sealed set at directory granularity, in lib/codeindex's source Merkle
 * dialect (a structurally different fold over the same bytes), so a module can
 * RECORD which sections it actually compiled against and the resident can
 * verify each of them IN ADDITION to ROOT.
 *
 * THIS FILE RELAXES NOTHING. The ROOT equality check is unchanged and still
 * runs first. A module that declares sections must ALSO match every one of
 * them and the TREE; a module that declares a section this resident does not
 * have is refused. The section rows are strictly additional evidence.
 *
 * The N-ary node digest for a directory covers that directory RECURSIVELY, so
 * an ancestor row ("core") subsumes its descendants. A module declares the
 * DEEPEST section containing each sealed file in its compile closure and never
 * its ancestors — an ancestor digest would pin sibling directories the module
 * never saw, which is the opposite of what section granularity is for.
 */

#ifndef ZCL_HOTSWAP_CORE_SEAL_SECTIONS_H
#define ZCL_HOTSWAP_CORE_SEAL_SECTIONS_H

/* Root node digest over the whole sealed set (dirpath ""). */
#define ZCL_CORE_SEAL_TREE \
    "cedb5217f76366e703a8c9deacb20f402b78d31c5ce552263bf2f4bce09f67e1"

/* SECTION lines in core/MANIFEST.sha3 at generation time. */
#define ZCL_CORE_SEAL_SECTION_COUNT 23u

/* X-macro row list. The consumer supplies ZCL_HOTSWAP_SECTION_ROW(path, hex);
 * hotswap/hotswap_module.h defines it as an initializer element. */
#define ZCL_CORE_SEAL_SECTION_ROWS \
    ZCL_HOTSWAP_SECTION_ROW("core", \
        "47e0783f6870a125bfe8740faac32e78fd3059ec52fc724d5a29720e77d87b3e") \
    ZCL_HOTSWAP_SECTION_ROW("core/chainparams", \
        "92f3588bd5bf7baa762047db111f4ec501be81170255ec38fb44b3a6a816434f") \
    ZCL_HOTSWAP_SECTION_ROW("core/chainparams/include", \
        "ef779ffaa74f93f2f119830afc90b607b4f2dc7597503f7e8d71e68cf9d71d6c") \
    ZCL_HOTSWAP_SECTION_ROW("core/chainparams/include/chain", \
        "c85db47e801c763c9f5e35853d264553512aae99a6a04a1c64f773764257064e") \
    ZCL_HOTSWAP_SECTION_ROW("core/chainparams/src", \
        "2e6e7bdb45fce18019f2bae2ecd516d7d3ba7bd00eee3b6c8a46c01bd13bd850") \
    ZCL_HOTSWAP_SECTION_ROW("core/consensus", \
        "4a93644417c715d8edd7c561829bce03efc0bcb1ef51f98fbd9cc3477e70bcdd") \
    ZCL_HOTSWAP_SECTION_ROW("core/consensus/include", \
        "93a0d56cd53b8242ab03862de7f4fa8474c3e051907ebfc13ad17b2c88c3bf08") \
    ZCL_HOTSWAP_SECTION_ROW("core/consensus/include/domain", \
        "dd10b76650d4502aa2a3a1bd513432c11f0a4e6fc71f0d2efd2eca27b06982e4") \
    ZCL_HOTSWAP_SECTION_ROW("core/consensus/include/domain/consensus", \
        "053940e24559cbb016fad0cf0707604edecad6781eb4a60839635422d4cd8dcf") \
    ZCL_HOTSWAP_SECTION_ROW("core/consensus/src", \
        "34d704684dc2b44950f03038e0e3398cf03b0f230cc1713d7a249acf4f63de03") \
    ZCL_HOTSWAP_SECTION_ROW("core/math", \
        "4a12df854665934805645f7b11b9ce279b93b7568fe58dde37f68d84913813da") \
    ZCL_HOTSWAP_SECTION_ROW("core/math/include", \
        "3d74828940990b6914192791641041d1ad63de1b84d7693d2533f1c9b29a7edd") \
    ZCL_HOTSWAP_SECTION_ROW("core/math/include/core", \
        "13bc29100524578193cb79036f24fe9e1d8538c0f45dcc4dd87956a25f4f2b38") \
    ZCL_HOTSWAP_SECTION_ROW("core/math/src", \
        "bed7851826222b99834c6ee74bb3e7ce6155798a5ef78c798fe2f836bbf30862") \
    ZCL_HOTSWAP_SECTION_ROW("core/params", \
        "9b023bcd18300a51052f45e69609bb741b2832e3ce6e6a02fd21a12ea94647c0") \
    ZCL_HOTSWAP_SECTION_ROW("core/params/include", \
        "e07dc0f2326862830b48105e02648f8d76dfeee9a859b7c56679c461e2cca7f1") \
    ZCL_HOTSWAP_SECTION_ROW("core/params/include/consensus", \
        "5680a2f2d804163e77f94854ee18838480d785b74b297265f2f8a77db9d02242") \
    ZCL_HOTSWAP_SECTION_ROW("core/params/src", \
        "8fdd673c41b8758e48c6fb225c15d7bbdf79f6816066a1d0c793d4bee2c5f6b1") \
    ZCL_HOTSWAP_SECTION_ROW("lib", \
        "98813389662a275597c863c78603e0650962a47376ca2d5aa022ce1d1438a559") \
    ZCL_HOTSWAP_SECTION_ROW("lib/validation", \
        "f96f6cc3afb4be3797bc41e1607ea3520dc52fb19e712314ed498c542053aaa7") \
    ZCL_HOTSWAP_SECTION_ROW("lib/validation/include", \
        "8434c5b6af68ca0b7e7f8148bffddffa21b92864af22ac86a5257611a309e480") \
    ZCL_HOTSWAP_SECTION_ROW("lib/validation/include/validation", \
        "9449e5ef64f9226c770a9dd86d83745a8e0ada3611d909d7854ce2f1cf4fa3ca") \
    ZCL_HOTSWAP_SECTION_ROW("lib/validation/src", \
        "6f9378a457006f876ccd8b298e882f924e56bbb4794c8a98bb87a2578bc3cd88")

#endif /* ZCL_HOTSWAP_CORE_SEAL_SECTIONS_H */
