/* Copyright 2026 Rhett Creighton - Apache License 2.0
 *
 * vcs_walk — implementation. See vcs_walk.h. */

#include "vcs_walk.h"

#include "vcs/vcs_object.h"
#include "vcs_priv.h"

#include "platform/positioned_file.h"
#include "util/log_macros.h"
#include "util/safe_alloc.h"

#if !defined(_WIN32)
#include <dirent.h>
#include <errno.h>
#include <fcntl.h>
#include <sys/stat.h>
#include <unistd.h>
#endif
#include <stdlib.h>
#include <string.h>

/* Return the final path component of relpath. */
static const char *base_of(const char *relpath)
{
    const char *slash = strrchr(relpath, '/');
    return slash ? slash + 1 : relpath;
}

/* Does relpath (or any ancestor component) equal one of the ignored dir
 * names, or start with an ignored dir prefix? */
static bool has_dir_component(const char *relpath, const char *comp)
{
    size_t clen = strlen(comp);
    const char *p = relpath;
    while (*p) {
        /* p points at the start of a component. */
        if (strncmp(p, comp, clen) == 0 && (p[clen] == '/' || p[clen] == '\0'))
            return true;
        const char *slash = strchr(p, '/');
        if (!slash)
            break;
        p = slash + 1;
    }
    return false;
}

/* Root-relative directory match. Unlike has_dir_component(), this does not
 * hide a same-named directory nested inside tracked source. */
static bool has_root_prefix(const char *relpath, const char *prefix)
{
    size_t len = strlen(prefix);
    return strncmp(relpath, prefix, len) == 0 &&
           (relpath[len] == '/' || relpath[len] == '\0');
}

bool vcs_path_ignored(const char *relpath)
{
    if (!relpath || !relpath[0])
        return true;

    /* dir prefixes / components */
    if (has_dir_component(relpath, ".git"))
        return true;
    if (has_dir_component(relpath, ".zvcs"))
        return true;
    if (has_dir_component(relpath, "build"))
        return true;
    /* Checkout-local agent worktrees and generated caches can contain many
     * complete repository copies. Walking them made the first dev-loop
     * provenance snapshot recursively index ~150k files and stall a hot swap
     * for minutes. Keep tracked .claude commands/skills; prune only runtime
     * subtrees. These paths mirror the repository's generated-file policy. */
    static const char *const ignored_roots[] = {
        ".cache",
        ".claude/tmp",
        ".claude/worktrees",
        ".codeindex",
        ".zcl_test_render",
        "chaos-output",
        "examples/bin",
        "obj",
        "bin",
        "vendor/.build",
        "vendor/.cache",
        "vendor/lib",
        "vendor/tor",
        "vendor/zclassic-ref",
        "zcode",
        NULL,
    };
    for (size_t i = 0; ignored_roots[i]; i++)
        if (has_root_prefix(relpath, ignored_roots[i]))
            return true;

    /* make vendor materializes these from the already-carried, pinned
     * archives in vendor/.cache.  They are build outputs (and are ignored by
     * Git), not independent source inputs.  Capturing them made a sovereign
     * carrier contain both an archive and its expanded/generated bytes,
     * needlessly exhausting the shared content.v2 package bound. */
    if (strcmp(relpath, "vendor/sqlite3.c") == 0 ||
        strcmp(relpath, "vendor/include/zlib.h") == 0 ||
        strcmp(relpath, "vendor/include/zconf.h") == 0)
        return true;

    if (has_root_prefix(relpath, "vendor/include/openssl"))
        return true;

    const char *b = base_of(relpath);
    size_t blen = strlen(b);
    /* *.db */
    if (blen >= 3 && strcmp(b + blen - 3, ".db") == 0)
        return true;
    if (blen >= 7 && strcmp(b + blen - 7, ".db-wal") == 0)
        return true;
    if (blen >= 7 && strcmp(b + blen - 7, ".db-shm") == 0)
        return true;
    if (blen >= 4 && strcmp(b + blen - 4, ".log") == 0)
        return true;
    /* node.db* (covers node.db, node.db-wal, node.db-shm) */
    if (strncmp(b, "node.db", 7) == 0)
        return true;
    /* test-tmp* */
    if (strncmp(b, "test-tmp", 8) == 0)
        return true;
    if (strcmp(relpath, ".claude/scheduled_tasks.lock") == 0 ||
        strcmp(b, "compile_commands.json") == 0 ||
        strcmp(b, ".core-unseal-token") == 0)
        return true;

    return false;
}

#if !defined(_WIN32)
struct walk_ctx {
    const char  *repo_root;
    vcs_walk_cb  cb;
    void        *user;
    bool         aborted;
};

/* Recurse into <repo_root>/<rel> (rel="" for the root). */
static bool walk_dir(struct walk_ctx *w, const char *rel)
{
    char full[4096];
    int n;
    if (rel[0])
        n = snprintf(full, sizeof(full), "%s/%s", w->repo_root, rel);
    else
        n = snprintf(full, sizeof(full), "%s", w->repo_root);
    if (n <= 0 || (size_t)n >= sizeof(full))
        LOG_FAIL("vcs", "walk path too long");

    DIR *d = opendir(full);
    if (!d)
        LOG_FAIL("vcs", "opendir %s: %s", full, strerror(errno));

    /* Collect names first (sorted) so the walk order is deterministic. */
    char **names = NULL;
    size_t ncount = 0, ncap = 0;
    struct dirent *de;
    bool ok = true;
    while ((de = readdir(d)) != NULL) {
        if (strcmp(de->d_name, ".") == 0 || strcmp(de->d_name, "..") == 0)
            continue;
        if (ncount == ncap) {
            size_t ncap2 = ncap ? ncap * 2 : 64;
            char **nn = zcl_realloc(names, ncap2 * sizeof(*nn), "vcs_walk_names");
            if (!nn) { ok = false; break; }
            names = nn;
            ncap = ncap2;
        }
        names[ncount] = zcl_strdup(de->d_name, "vcs_walk_name");
        if (!names[ncount]) { ok = false; break; }
        ncount++;
    }
    closedir(d);
    if (!ok) {
        for (size_t i = 0; i < ncount; i++) free(names[i]);
        free(names);
        LOG_FAIL("vcs", "readdir alloc failed");
    }

    /* deterministic order */
    for (size_t i = 0; i + 1 < ncount; i++)
        for (size_t j = i + 1; j < ncount; j++)
            if (strcmp(names[i], names[j]) > 0) {
                char *t = names[i]; names[i] = names[j]; names[j] = t;
            }

    for (size_t i = 0; i < ncount && ok && !w->aborted; i++) {
        char childrel[4096];
        int cn;
        if (rel[0])
            cn = snprintf(childrel, sizeof(childrel), "%s/%s", rel, names[i]);
        else
            cn = snprintf(childrel, sizeof(childrel), "%s", names[i]);
        if (cn <= 0 || (size_t)cn >= sizeof(childrel))
            continue;  /* skip pathological over-long names */

        if (vcs_path_ignored(childrel))
            continue;

        char childfull[4096];
        int cfn = snprintf(childfull, sizeof(childfull), "%s/%s",
                           w->repo_root, childrel);
        if (cfn <= 0 || (size_t)cfn >= sizeof(childfull))
            continue;

        struct stat st;
        if (lstat(childfull, &st) != 0)
            continue;  /* vanished mid-walk; skip */

        if (S_ISDIR(st.st_mode)) {
            if (!walk_dir(w, childrel))
                ok = false;
        } else if (S_ISREG(st.st_mode)) {
            int64_t mtime_ns = (int64_t)st.st_mtim.tv_sec * 1000000000 +
                               st.st_mtim.tv_nsec;
            int64_t ctime_ns = (int64_t)st.st_ctim.tv_sec * 1000000000 +
                               st.st_ctim.tv_nsec;
            if (!w->cb(childrel, (uint32_t)st.st_mode, (uint64_t)st.st_size,
                       mtime_ns, ctime_ns, w->user)) {
                w->aborted = true;
            }
        }
        /* symlinks / fifos / sockets: not tracked in v1 */
    }

    for (size_t i = 0; i < ncount; i++) free(names[i]);
    free(names);
    return ok;
}
#endif

bool vcs_walk_tracked(const char *repo_root, vcs_walk_cb cb, void *user)
{
    if (!repo_root || !cb)
        LOG_FAIL("vcs", "null arg to walk_tracked");
#if defined(_WIN32)
    (void)user;
    /* Safe traversal requires enumeration relative to a retained directory
     * handle. The current Windows directory-list seam validates only the
     * final path and cannot exclude an intermediate reparse substitution. */
    return false;
#else
    struct walk_ctx w = { repo_root, cb, user, false };
    if (!walk_dir(&w, ""))
        return false;
    return !w.aborted;
#endif
}

static bool blob_snapshot_same(
    const struct platform_positioned_file_snapshot *a,
    const struct platform_positioned_file_snapshot *b)
{
    return a->size == b->size && a->volume == b->volume &&
           a->file_low == b->file_low && a->file_high == b->file_high &&
           a->modified_seconds == b->modified_seconds &&
           a->modified_nanoseconds == b->modified_nanoseconds &&
           a->changed_seconds == b->changed_seconds &&
           a->changed_nanoseconds == b->changed_nanoseconds;
}

bool vcs_blob_hash_file(const char *repo_root, const char *relpath,
                        uint8_t out[32])
{
    if (!repo_root || !relpath || !out)
        LOG_FAIL("vcs", "null arg to blob_hash_file");
    struct platform_positioned_file file;
    struct platform_positioned_file_snapshot before, after;
    platform_positioned_file_init(&file);
    if (!platform_positioned_file_open_beneath(&file, repo_root, relpath) ||
        !platform_positioned_file_snapshot(&file, &before)) {
        platform_positioned_file_close(&file);
        return false;
    }

    uint8_t tag = VCS_TAG_BLOB;
    struct sha3_256_ctx ctx;
    sha3_256_init(&ctx);
    sha3_256_write(&ctx, &tag, 1);

    unsigned char buf[65536];
    uint64_t offset = 0;
    bool ok = true;
    while (offset < before.size) {
        size_t want = before.size - offset > sizeof(buf)
                          ? sizeof(buf) : (size_t)(before.size - offset);
        int64_t r = platform_positioned_file_read(&file, buf, want, offset);
        if (r <= 0) { ok = false; break; }
        if (r == 0)
            break;
        sha3_256_write(&ctx, buf, (size_t)r);
        offset += (uint64_t)r;
    }
    ok = ok && offset == before.size &&
         platform_positioned_file_snapshot(&file, &after) &&
         blob_snapshot_same(&before, &after);
    platform_positioned_file_close(&file);
    if (!ok) return false;
    sha3_256_finalize(&ctx, out);
    return true;
}
