/* Copyright 2026 Rhett Creighton - Apache License 2.0
 *
 * Checkpoint LADDER rung — the exportable, portable form of one
 * complete-state checkpoint record.
 *
 * The sealed ROM table (core/chainparams/src/checkpoints.c) bakes ONE
 * rung: the g_rom_state_checkpoint keystone at a single height. The
 * ~122k-block region above it to tip has no checkpoint fallback, so a
 * corruption there is curable only by body refetch. A ladder is a chain
 * of additional rungs above the baked one, each a
 * `struct rom_state_checkpoint`-shaped record plus the cumulative
 * chainwork and a SHA3 self-digest, so a node can shrink the un-anchored
 * region and detect a divergent artifact.
 *
 * A `checkpoint_rung` carries EXACTLY the fields the sealed
 * `struct rom_state_checkpoint` carries (byte-for-byte the same transparent
 * + shielded digests, and the same pinned `rom_state_root` fold — see
 * core/chainparams/include/chain/checkpoints.h and
 * tools/rom_two_builder_compare.c), plus:
 *   - `chainwork`  — the 256-bit cumulative chainwork at `height`, BIG-endian
 *                    (the block-header convention); ladder monotonicity is a
 *                    bytewise compare on this.
 *   - `self_digest`— SHA3-256 over the serialized rung bytes preceding it,
 *                    so a tampered artifact fails to parse.
 *
 * HONESTY (see lane spec rule 4): a rung generated by a node from its own
 * state is SELF-ATTESTATION. It is a `candidate_unbaked` rung until the owner
 * re-derives and bakes it into the sealed table under the two-builder ritual.
 * Nothing in this module elevates a candidate rung to a trust root — only the
 * compiled `g_rom_state_checkpoint` is `bound`.
 */

#ifndef ZCL_STORAGE_CHECKPOINT_RUNG_H
#define ZCL_STORAGE_CHECKPOINT_RUNG_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

struct sqlite3;              /* derive-from-bundle reads a bundle handle */
struct rom_state_checkpoint; /* chain/checkpoints.h — only from_rom_checkpoint
                              * touches its fields; kept a forward decl here so
                              * consumers (and the standalone generator tool) do
                              * not pull the heavy chain/ include tree. */

/* One ladder rung. The first 13 members mirror struct rom_state_checkpoint
 * field-for-field (same order, same byte order — internal/hashed order for the
 * 32-byte arrays); the last two are the ladder-only extensions. */
struct checkpoint_rung {
    int32_t  height;
    uint8_t  block_hash[32];
    uint8_t  utxo_root[32];
    uint64_t utxo_count;
    int64_t  total_supply;
    uint8_t  anchor_digest[32];
    uint64_t anchor_count;
    uint8_t  sprout_frontier_root[32];
    int64_t  sprout_frontier_height;
    uint8_t  sapling_frontier_root[32];
    int64_t  sapling_frontier_height;
    uint8_t  nullifier_digest[32];
    uint64_t nullifier_count;
    uint8_t  rom_state_root[32];
    uint8_t  chainwork[32];    /* 256-bit cumulative chainwork, big-endian */
    uint8_t  self_digest[32];  /* SHA3-256 over serialized bytes [0, self) */
};

/* Fixed on-disk / on-wire artifact size. Layout is documented in
 * checkpoint_rung.c; it is a stable little-endian record framed by an
 * 8-byte magic + version so a parser can reject foreign bytes. */
#define CHECKPOINT_RUNG_WIRE_SIZE 404u
#define CHECKPOINT_RUNG_WIRE_VERSION 1u

/* Recompute the pinned complete-state fold from the rung's fields into
 * out[32]. Byte-identical to tools/rom_two_builder_compare.c's
 * rtb_rom_state_root and to the value baked as
 * g_rom_state_checkpoint.rom_state_root — a rung whose transparent+shielded
 * fields reproduce the keystone therefore has a byte-identical rom_state_root.
 * Reads only the 13 mirrored fields; ignores chainwork/self_digest. */
void checkpoint_rung_compute_rom_state_root(const struct checkpoint_rung *r,
                                            uint8_t out[32]);

/* Recompute the SHA3 self-digest (over the serialized rung minus the trailing
 * self_digest field) into out[32]. Uses the serialized form, so it binds every
 * field including rom_state_root and chainwork. */
void checkpoint_rung_compute_self_digest(const struct checkpoint_rung *r,
                                         uint8_t out[32]);

/* Fill r->rom_state_root then r->self_digest from the other fields. Call after
 * populating the 13 mirrored fields + chainwork. */
void checkpoint_rung_finalize(struct checkpoint_rung *r);

/* True iff the rung's stored rom_state_root and self_digest both agree with a
 * fresh recomputation from its own fields. A tampered artifact fails this. */
bool checkpoint_rung_self_consistent(const struct checkpoint_rung *r);

/* Serialize into buf[CHECKPOINT_RUNG_WIRE_SIZE]. Returns false on NULL args.
 * The rung is finalized-in-place first (rom_state_root + self_digest refreshed)
 * so the artifact is always internally consistent. */
bool checkpoint_rung_serialize(struct checkpoint_rung *r,
                               uint8_t buf[CHECKPOINT_RUNG_WIRE_SIZE]);

/* Parse `len` bytes into *out. Rejects (returns false, logs) on bad magic,
 * version, length, or a self_digest / rom_state_root that does not recompute —
 * a foreign or corrupt artifact never yields a rung. */
bool checkpoint_rung_parse(const uint8_t *buf, size_t len,
                           struct checkpoint_rung *out);

/* Convert the compiled sealed keystone into a rung (chainwork optional; pass
 * NULL for all-zero). Returns false if `cp` is NULL. The result is finalized;
 * its rom_state_root MUST equal cp->rom_state_root for a non-placeholder
 * keystone (asserted by callers, not here). */
bool checkpoint_rung_from_rom_checkpoint(const struct rom_state_checkpoint *cp,
                                         const uint8_t chainwork[32],
                                         struct checkpoint_rung *out);

/* Derive a rung's 13 mirrored fields from a consensus-state BUNDLE database
 * handle (the exporter's output: tables coins/anchors/nullifiers +
 * bundle_meta). Folds the exact codec preimages, then finalizes. `chainwork`
 * optional (NULL => zero). On success writes *out and returns true; on any
 * malformed/ordering/read error returns false (logged). Read-only. */
bool checkpoint_rung_derive_from_bundle(struct sqlite3 *bundle,
                                        const uint8_t chainwork[32],
                                        struct checkpoint_rung *out);

/* Emit a C designated-initializer fragment for pasting into the sealed ROM
 * table during the owner unseal ritual. Produces a
 * `static const struct rom_state_checkpoint ...` literal in the exact style of
 * checkpoints.c (hex-commented byte arrays), with chainwork + self_digest in a
 * trailing comment (the sealed struct has no such members). Writes a
 * NUL-terminated string into out[cap]; returns the number of bytes that WOULD
 * be written (excluding NUL), or -1 on NULL args. */
int checkpoint_rung_emit_c_fragment(const struct checkpoint_rung *r,
                                    char *out, size_t cap);

#endif
