/* Copyright 2026 Rhett Creighton - Apache License 2.0
 *
 * purpose: the split C23 lint runtime's gate table and CLI entry point
 * (z23-lint <gate-name> [--selftest] | z23-lint <gate-name> [args...] | --list).
 */

#ifndef _POSIX_C_SOURCE
#define _POSIX_C_SOURCE 200809L
#endif
#include <stdio.h>
#include <string.h>
#include "lintc.h"

static const struct lint_gate k_gates[] = {
    { "check-no-python", check_no_python_run, check_no_python_selftest },
    { "check-malloc", check_malloc_run, check_malloc_selftest },
    { "check-dev-proof-native-fast-path", check_dev_proof_native_fast_path_run,
      check_dev_proof_native_fast_path_selftest },
    { "check-before-save-hooks", check_before_save_hooks_run, check_before_save_hooks_selftest },
    { "check-pthread-create", check_pthread_create_run, check_pthread_create_selftest },
    { "check-silent-error-returns", check_silent_error_returns_run,
      check_silent_error_returns_selftest },
    { "check-no-gnu-va-args", check_no_gnu_va_args_run, check_no_gnu_va_args_selftest },
    { "check-sysinit-ordering", check_sysinit_ordering_run, check_sysinit_ordering_selftest },
    { "check-no-raw-clock-outside-platform", check_no_raw_clock_outside_platform_run,
      check_no_raw_clock_outside_platform_selftest },
    { "check-no-shellouts", check_no_shellouts_run, check_no_shellouts_selftest },
    { "check-command-contract", check_command_contract_run, check_command_contract_selftest },
    { "check-no-writer-below-sealed-frontier", check_no_writer_below_sealed_frontier_run,
      check_no_writer_below_sealed_frontier_selftest },
    { "check-no-stray-root-files", check_no_stray_root_files_run,
      check_no_stray_root_files_selftest },
    { "check-proc-self-shim", check_proc_self_shim_run, check_proc_self_shim_selftest },
    { "check-simd-os-support", check_simd_os_support_run, check_simd_os_support_selftest },
    { "check-c23-only", check_c23_only_run, check_c23_only_selftest },
    { "check-hotswap-dev-only", check_hotswap_dev_only_run, check_hotswap_dev_only_selftest },
    { "check-no-api-keys", check_no_api_keys_run, check_no_api_keys_selftest },
    { "check-error-doc-refs", check_error_doc_refs_run, check_error_doc_refs_selftest },
    { "check-core-seal-root-mirror", check_core_seal_root_mirror_run,
      check_core_seal_root_mirror_selftest },
    { "check-peer-floor-single-source", check_peer_floor_single_source_run,
      check_peer_floor_single_source_selftest },
    { "check-proof-server-pin", check_proof_server_pin_run,
      check_proof_server_pin_selftest },
    { "check-tu-random-seed", check_tu_random_seed_run,
      check_tu_random_seed_selftest },
    { "check-no-retired-agent-protocol", check_no_retired_agent_protocol_run,
      check_no_retired_agent_protocol_selftest },
    { "check-stopwatch-skip-detector", check_stopwatch_skip_detector_run,
      check_stopwatch_skip_detector_selftest },
    { "check-no-warning-suppression", check_no_warning_suppression_run,
      check_no_warning_suppression_selftest },
    { "check-privileged-transition-receipt", check_privileged_transition_receipt_run,
      check_privileged_transition_receipt_selftest },
    { "check-no-new-coin-backfill-caller", check_no_new_coin_backfill_caller_run,
      check_no_new_coin_backfill_caller_selftest },
    { "check-mind-owns-rebuild", check_mind_owns_rebuild_run,
      check_mind_owns_rebuild_selftest },
    { "check-codeindex-coverage", check_codeindex_coverage_run,
      check_codeindex_coverage_selftest },
    { "check-asan-adx-exception", check_asan_adx_exception_run,
      check_asan_adx_exception_selftest },
    { "check-framework-filename-suffix", check_framework_filename_suffix_run,
      check_framework_filename_suffix_selftest },
    { "check-no-stray-untracked-source", check_no_stray_untracked_source_run,
      check_no_stray_untracked_source_selftest },
    { "check-group-purpose", check_group_purpose_run, check_group_purpose_selftest },
    { "check-no-new-borrowed-seed", check_no_new_borrowed_seed_run,
      check_no_new_borrowed_seed_selftest },
    { "check-silent-errors-bool", check_silent_errors_bool_run,
      check_silent_errors_bool_selftest },
    { "check-no-raw-sqlite-in-controllers", check_no_raw_sqlite_in_controllers_run,
      check_no_raw_sqlite_in_controllers_selftest },
    { "check-blob-read-bounds", check_blob_read_bounds_run,
      check_blob_read_bounds_selftest },
    { "check-posix-ere-only", check_posix_ere_only_run, check_posix_ere_only_selftest },
    { "check-no-orphan-placement", check_no_orphan_placement_run,
      check_no_orphan_placement_selftest },
    { "check-architecture-tree", check_architecture_tree_run,
      check_architecture_tree_selftest },
    { "check-sandbox-wired", check_sandbox_wired_run, check_sandbox_wired_selftest },
    { "check-hotswap-eligible-scope", check_hotswap_eligible_scope_run,
      check_hotswap_eligible_scope_selftest },
    { "check-hotswap-static-state", check_hotswap_static_state_run,
      check_hotswap_static_state_selftest },
    { "check-hotswap-candidates-ledger", check_hotswap_candidates_ledger_run,
      check_hotswap_candidates_ledger_selftest },
    { "check-result-discard", check_result_discard_run,
      check_result_discard_selftest },
    { "check-wallet-raw-prepare-log", check_wallet_raw_prepare_log_run,
      check_wallet_raw_prepare_log_selftest },
    { "check-persona-resolves", check_persona_resolves_run, check_persona_resolves_selftest },
    { "check-prompt-templates", check_prompt_templates_run, check_prompt_templates_selftest },
    { "check-zcode-package-registry", check_zcode_package_registry_run,
      check_zcode_package_registry_selftest },
    { "check-zcode-package-standalone", check_zcode_package_standalone_run,
      check_zcode_package_standalone_selftest },
    { "check-honest-witness", check_honest_witness_run, check_honest_witness_selftest },
    { "check-mint-skip-crypto-offline-only", check_mint_skip_crypto_offline_only_run,
      check_mint_skip_crypto_offline_only_selftest },
    { "check-equihash-params", check_equihash_params_run, check_equihash_params_selftest },
    { "check-arena-view-stub", check_arena_view_stub_run, check_arena_view_stub_selftest },
    { "check-cyclomatic-complexity", check_cyclomatic_complexity_run,
      check_cyclomatic_complexity_selftest },
    { "check-framework-shape", check_framework_shape_run,
      check_framework_shape_selftest },
    { "check-zclassicd-reach-allowlist", check_zclassicd_reach_allowlist_run,
      check_zclassicd_reach_allowlist_selftest },
    { "check-file-purpose", check_file_purpose_run,
      check_file_purpose_selftest },
    { "check-route-command-parity", check_route_command_parity_run,
      check_route_command_parity_selftest },
    { "check-flag-registry", check_flag_registry_run, check_flag_registry_selftest },
    { "check-rpc-registrar", check_rpc_registrar_run,
      check_rpc_registrar_selftest },
    { "check-coins-lookup-nullcheck", check_coins_lookup_nullcheck_run,
      check_coins_lookup_nullcheck_selftest },
    { "check-wire-harness-security-gate", check_wire_harness_security_gate_run,
      check_wire_harness_security_gate_selftest },
    { "check-tor-dial-prewarm", check_tor_dial_prewarm_run,
      check_tor_dial_prewarm_selftest },
    { "check-describe-budget", check_describe_budget_run,
      check_describe_budget_selftest },
    { "check-json-value-init", check_json_value_init_run,
      check_json_value_init_selftest },
    { "check-one-write-path", check_one_write_path_run,
      check_one_write_path_selftest },
    { "check-supervisor-domain", check_supervisor_domain_run,
      check_supervisor_domain_selftest },
    { "check-controller-private-headers", check_controller_private_headers_run,
      check_controller_private_headers_selftest },
    { "check-generated-artifact-contradictions",
      check_generated_artifact_contradictions_run,
      check_generated_artifact_contradictions_selftest },
    { "check-model-column-drift", check_model_column_drift_run,
      check_model_column_drift_selftest },
    { "check-thread-supervision", check_thread_supervision_run,
      check_thread_supervision_selftest },
    { "check-model-validation", check_model_validation_run,
      check_model_validation_selftest },
    { "check-lag-slo-observable", check_lag_slo_observable_run,
      check_lag_slo_observable_selftest },
    { "check-vcs-no-git", check_vcs_no_git_run, check_vcs_no_git_selftest },
    { "check-no-authoritative-ram-state", check_no_authoritative_ram_state_run,
      check_no_authoritative_ram_state_selftest },
    { "check-operator-needed-sink", check_operator_needed_sink_run,
      check_operator_needed_sink_selftest },
    { "check-shape-includes-header", check_shape_includes_header_run,
      check_shape_includes_header_selftest },
    { "check-no-utxo-projection", check_no_utxo_projection_run,
      check_no_utxo_projection_selftest },
    { "check-no-block-index-flat", check_no_block_index_flat_run,
      check_no_block_index_flat_selftest },
    { "check-projections-pure", check_projections_pure_run,
      check_projections_pure_selftest },
    { "check-typed-blocker", check_typed_blocker_run,
      check_typed_blocker_selftest },
    { "check-core-include-boundary", check_core_include_boundary_run,
      check_core_include_boundary_selftest },
    { "check-shape-include-direction", check_shape_include_direction_run,
      check_shape_include_direction_selftest },
    { "check-no-silent-ready", check_no_silent_ready_run,
      check_no_silent_ready_selftest },
    { "check-stage-advances-or-blocks", check_stage_advances_or_blocks_run,
      check_stage_advances_or_blocks_selftest },
    { "check-lib-layering", check_lib_layering_run,
      check_lib_layering_selftest },
    { "check-domain-purity", check_domain_purity_run,
      check_domain_purity_selftest },
    { "check-one-result-type", check_one_result_type_run,
      check_one_result_type_selftest },
    { "check-no-secret-printf", check_no_secret_printf_run,
      check_no_secret_printf_selftest },
    { "check-long-functions", check_long_functions_run,
      check_long_functions_selftest },
    { "check-test-registration", check_test_registration_run,
      check_test_registration_selftest },
    { "check-consensus-parity", check_consensus_parity_run,
      check_consensus_parity_selftest },
    { "check-systemd-memory-budget", check_systemd_memory_budget_run,
      check_systemd_memory_budget_selftest },
    { "check-dumper-never-blocks", check_dumper_never_blocks_run,
      check_dumper_never_blocks_selftest },
    { "check-supervisor-registration", check_supervisor_registration_run,
      check_supervisor_registration_selftest },
    { "check-vcs-no-sha1", check_vcs_no_sha1_run, check_vcs_no_sha1_selftest },
    { "check-blocker-remedy", check_blocker_remedy_run,
      check_blocker_remedy_selftest },
    { "check-stable-publish-contained", check_stable_publish_containment_run,
      check_stable_publish_containment_selftest },
    { "check-service-result-convergence",
      check_service_result_convergence_run,
      check_service_result_convergence_selftest },
    { "check-frontier-single-writer", check_frontier_single_writer_run,
      check_frontier_single_writer_selftest },
    { "check-no-utxos-mirror-read", check_no_utxos_mirror_read_run,
      check_no_utxos_mirror_read_selftest },
    { "check-no-dev-history-in-contracts",
      check_no_dev_history_in_contracts_run,
      check_no_dev_history_in_contracts_selftest },
    { "check-no-uncited-victory", check_no_uncited_victory_run,
      check_no_uncited_victory_selftest },
    { "check-model-ar-lifecycle", check_model_ar_lifecycle_run,
      check_model_ar_lifecycle_selftest },
    { "check-raw-malloc", check_raw_malloc_run, check_raw_malloc_selftest },
    { "check-no-new-repair-rung", check_no_new_repair_rung_run,
      check_no_new_repair_rung_selftest },
    { "check-tor-full-default", check_tor_full_default_run,
      check_tor_full_default_selftest },
    { "check-installed-acceptance-tools", check_installed_acceptance_tools_run,
      check_installed_acceptance_tools_selftest },
    { "check-hotswap-denied-leaves", check_hotswap_denied_leaves_run,
      check_hotswap_denied_leaves_selftest },
    { "check-command-availability-truthful", check_command_availability_truthful_run,
      check_command_availability_truthful_selftest },
    { "check-rule-vocabulary", check_rule_vocabulary_run, check_rule_vocabulary_selftest },
    { "check-blocker-escape-registered", check_blocker_escape_registered_run,
      check_blocker_escape_registered_selftest },
    { "check-git-hooks-installed", check_git_hooks_installed_run,
      check_git_hooks_installed_selftest },
    { "check-fleet-facts", check_fleet_facts_run, check_fleet_facts_selftest },
};

int main(int argc, char **argv)
{
    g_lint_argv0 = argc > 0 ? argv[0] : NULL;
    if (argc >= 2 && strcmp(argv[1], "--list") == 0) {
        for (size_t i = 0; i < sizeof k_gates / sizeof k_gates[0]; i++)
            printf("%s\n", k_gates[i].name);
        return 0;
    }
    if (argc >= 2 && strcmp(argv[1], "--families") == 0)
        return lint_families_ledger();
    if (argc < 2)
        return die("z23-lint: usage: z23-lint <gate-name> [--selftest] | z23-lint <gate-name> [args...] | --list | --families\n",
                   "");
    const struct lint_gate *g = NULL;
    for (size_t i = 0; i < sizeof k_gates / sizeof k_gates[0]; i++) {
        if (strcmp(argv[1], k_gates[i].name) == 0)
            g = &k_gates[i];
    }
    if (!g)
        return die("z23-lint: unknown gate: %s\n", argv[1]);
    if (argc >= 3 && strcmp(argv[2], "--selftest") == 0)
        return g->selftest();
    return g->run(argc - 2, argv + 2);
}
