/* Copyright 2026 Rhett Creighton - Apache License 2.0
 *
 * Site layout helpers — the shared page chrome (document head, global nav,
 * footer) for the server-rendered site: explorer, ZNAM names, store, blog,
 * and any future /zcode route family. Pure header-only emitters over caller
 * buffers, following the explorer_emit_nav() pattern in
 * controllers/explorer_internal.h.
 *
 * The stylesheet is NOT here: it is the compiled `site_css` symbol in
 * views/site_css.h (generated by `make site-css` from
 * contexts/explorer/views/src/site.css). Pages either link it as /explorer/style.css
 * (explorer) or inline it in a <style> block via site_emit_head's css
 * parameter (names/store/blog — one round trip over the onion, whose
 * response buffer is 64 KiB).
 *
 * Contract for a new page family: open with site_emit_head(), emit
 * site_emit_global_nav() with the family's active id, mark the main content
 * with <main id='content'>, close with site_emit_footer(). Use the token
 * classes from site.css (.card/.grid/table/.pill/.btn/...) rather than
 * inventing page-local styles. */

#ifndef ZCL_VIEWS_SITE_LAYOUT_H
#define ZCL_VIEWS_SITE_LAYOUT_H

#include <stdbool.h>
#include <stddef.h>
#include <stdarg.h>
#include <stdio.h>
#include <string.h>

#include "base/format_attribute.h"
#include "net/site_routes.h"

ZCL_PRINTF_LIKE(4, 5)
static inline size_t site_appendf(char *buf, size_t max, size_t off,
                                  const char *format, ...)
{
    if (off >= max)
        return off;
    size_t remaining = max - off;
    va_list args;
    va_start(args, format);
    int written = vsnprintf(buf + off, remaining, format, args);
    va_end(args);
    if (written <= 0)
        return off;
    return off + ((size_t)written < remaining ? (size_t)written
                                              : remaining - 1);
}

#define SITE_APPEND(off, buf, max, ...) \
    ((off) = site_appendf((char *)(buf), (max), (off), __VA_ARGS__))

/* Global site nav — the one bar that unifies every route family. `active`
 * is one of "explorer", "names", "store", "blog", "metaverse", "yardsale",
 * "zcode", "directory" (the link gets class='active'), or NULL to highlight
 * nothing. The link set is generated: g_zcl_site_nav_app is expanded from
 * net/site_routes.def (the single site-route inventory) in
 * core/modules/net/src/site_routes.c — add a row there, never a link here.
 * SITE_GLOBAL_NAV below stays the literal twin for one-shot snprintf
 * format strings; test_site_routes pins the twin contract byte-exactly. */
static inline size_t site_emit_global_nav(char *buf, size_t max,
                                          const char *active)
{
    size_t off = 0;
    SITE_APPEND(off, buf, max,
        "<header class='site-top'>"
        "<a class='brand' href='/'>"
        "<span class='glyph' aria-hidden='true'>Z</span>"
        "<span>Z23</span></a>"
        "<nav aria-label='Site'>");
    for (size_t i = 0; i < g_zcl_site_nav_app_count; i++) {
        bool act = active && strcmp(active, g_zcl_site_nav_app[i].id) == 0;
        SITE_APPEND(off, buf, max, "<a href='%s'%s>%s</a>",
                    g_zcl_site_nav_app[i].href, act ? " class='active'" : "",
                    g_zcl_site_nav_app[i].label);
    }
    SITE_APPEND(off, buf, max, "</nav></header>");
    return off;
}

/* Literal twin of site_emit_global_nav(active=NULL) for one-shot snprintf
 * format strings (legacy explorer error pages). A compile-time string
 * cannot be generated from the def (macro expansion cannot order rows
 * other than def order), so the twin relationship is pinned byte-exactly
 * by the test_site_routes group instead. */
#define SITE_GLOBAL_NAV \
    "<header class='site-top'>" \
    "<a class='brand' href='/'>" \
    "<span class='glyph' aria-hidden='true'>Z</span>" \
    "<span>Z23</span></a>" \
    "<nav aria-label='Site'>" \
    "<a href='/explorer'>Explorer</a>" \
    "<a href='/names'>Names</a>" \
    "<a href='/store'>Store</a>" \
    "<a href='/blog'>Blog</a>" \
    "<a href='/metaverse'>Metaverse</a>" \
    "<a href='/yardsale'>Yardsale</a>" \
    "<a href='/zcode'>Zcode</a>" \
    "<a href='/directory'>Directory</a>" \
    "</nav></header>"

/* Document open: doctype through <body>. When `css` is non-NULL it is
 * inlined in a <style> block (single-round-trip pages over the onion);
 * when NULL the page links the shared external stylesheet the explorer
 * serves at /explorer/style.css. `body_class` may be NULL or "measure"
 * (narrow reading column for prose/app pages). Emits a skip link targeting
 * #content — mark the main content container with id='content'. */
static inline size_t site_emit_head(char *buf, size_t max, const char *title,
                                    const char *css, const char *body_class)
{
    size_t off = 0;
    SITE_APPEND(off, buf, max,
        "<!DOCTYPE html><html lang='en'><head><meta charset='utf-8'>"
        "<meta name='viewport' content='width=device-width,initial-scale=1'>"
        "<title>%s</title>",
        (title && title[0]) ? title : "Z23");
    if (css)
        SITE_APPEND(off, buf, max, "<style>%s</style>", css);
    else
        SITE_APPEND(off, buf, max,
            "<link rel='stylesheet' href='/explorer/style.css'>");
    SITE_APPEND(off, buf, max, "</head><body");
    if (body_class && body_class[0])
        SITE_APPEND(off, buf, max, " class='%s'", body_class);
    SITE_APPEND(off, buf, max,
        "><a class='skip' href='#content'>Skip to content</a>");
    return off;
}

/* Document close: site footer + </body></html>. */
static inline size_t site_emit_footer(char *buf, size_t max, const char *text)
{
    size_t off = 0;
    SITE_APPEND(off, buf, max, "<footer>%s</footer></body></html>",
        (text && text[0]) ? text
                          : "Z23 &mdash; one binary, one onion, one stack");
    return off;
}

#endif /* ZCL_VIEWS_SITE_LAYOUT_H */
