#!/usr/bin/env bash
# Copyright 2026 Rhett Creighton - Apache License 2.0
#
# Lint gate — Equihash parameters are height-selected, and the repository says
# so (HARD).
#
# THE BUG THIS PREVENTS. Nine files across docs, the explorer, the miner and
# the replay verifier stated "ZClassic is Equihash 200,9" in the flat present
# tense. That was true at launch and has been wrong on mainnet since the
# Bubbles upgrade at height 585318: consensus selects (N,K) by height out of
# EquihashUpgradeInfo, and mainnet has been 192,7 — a 400-byte solution, not
# 1344 — for every block since. A reader who believed the flat claim would
# size a solution buffer, a miner, or a verifier against parameters the chain
# stopped using years ago.
#
# Two halves, because there are two ways for this to go wrong:
#
#   1. DRIFT AWAY FROM THE CODE. docs/EQUIHASH_PARAMS.md is generated by
#      tools/equihash_params_fact.c, which LINKS the real chainparams and
#      upgrade tables and prints what consensus would answer. The gate
#      regenerates into a temp file and diffs. A consensus table change with a
#      stale page fails here.
#
#   2. DRIFT BACK INTO PROSE. A flat "Equihash 200,9" claim about what the
#      chain IS — no height, no epoch, no "launch"/"pre-Bubbles" qualifier —
#      fails wherever it appears. Historical statements, benchmark fixtures
#      and the pre-Bubbles row are all legitimate and all carry a qualifier,
#      so the qualifier is exactly what this scans for.
#
# --selftest plants both failures in a temp tree and proves the gate trips.
# There is no baseline and no override: the correct sentence is never longer
# than one clause.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
cd "$ROOT"

DOC="docs/EQUIHASH_PARAMS.md"
SELFTEST=0
[ "${1:-}" = --selftest ] && SELFTEST=1

# The defect is not the number, it is the CLAIM SHAPE: a line that presents
# 200,9 as what the chain, mainnet, or consensus IS. A benchmark row, a baked
# witness, a solution-size constant and the pre-Bubbles branch of a validator
# all name 200,9 legitimately and are not claims about the current chain.
#
# A qualifier may sit on the line itself or in the two lines above it, because
# a comment usually establishes "at launch" or "pre-Bubbles" before the number
# appears. Anything narrower produces false positives on correct prose, and a
# gate that cries wolf gets suppressed instead of obeyed.
#
# The scan walks the working tree, so it also walks whatever untracked scratch
# happens to be sitting in it. build/ and vendor/ were already skipped;
# .claude/worktrees/ and test-tmp/ (.gitignore:66 and :52) are skipped for the
# same reason plus a sharper one — a nested worktree checked out at a commit
# from before the 192,7 correction still carries the old flat prose, so leaving
# it in scope makes this gate unpassable until the developer deletes work in
# progress. Only .claude/worktrees/ is excluded, never the tracked
# .claude/skills/, which stays in scope.
CLAIM='ZClassic is|ZClassic uses|[Mm]ainnet|proof-of-work|PoW|Consensus validation|Header chain|the chain is|network is'
QUALIFIER='[Pp]re-Bubbles|[Bb]efore|[Bb]elow|launch|[Oo]riginal|height|epoch|Sprout|legacy|historic|fixture|witness|baked|benchmark|until|selected|[Uu]pgrade|192'

scan_prose()
{
    local root="$1" hits
    hits="$(
        cd "$root" &&
        if [ "$(git rev-parse --show-toplevel 2>/dev/null || true)" = "$(pwd -P)" ]; then
            git grep -n -E 'Equihash[ -]?\(?200[,/ ]?9\)?' -- \
                '*.md' '*.c' '*.h' '*.def' '*.in' 2>/dev/null |
                sed 's#^#./#'
        else
            grep -rn --include='*.md' --include='*.c' --include='*.h' \
                --include='*.def' --include='*.in' -E \
                'Equihash[ -]?\(?200[,/ ]?9\)?' . 2>/dev/null
        fi |
        grep -v '^\./build/' | grep -v '^\./vendor/' |
        grep -v '^\./\.claude/worktrees/' | grep -v '^\./test-tmp/' |
        grep -v "^\./$DOC:" |
        grep -v '^\./tools/lint/check_equihash_params.sh:' |
        grep -v '^\./tools/equihash_params_fact.c:' |
        awk -v claim="$CLAIM" -v qual="$QUALIFIER" -F: '
        {
            file = $1; lineno = $2
            text = $0
            sub(/^[^:]*:[^:]*:/, "", text)
            if (text !~ claim) next
            if (text ~ qual) next
            # two lines of lookbehind in the file itself
            ctx = ""
            for (back = 1; back <= 2; back++) {
                cmd = "sed -n " (lineno - back) "p " file " 2>/dev/null"
                line = ""
                cmd | getline line
                close(cmd)
                ctx = ctx " " line
            }
            if (ctx ~ qual) next
            print "  " file ":" lineno ":" text
        }'
    )"
    [ -z "$hits" ] && return 0
    printf '%s\n' "$hits"
    return 1
}
if [ "$SELFTEST" = 1 ]; then
    work="$(mktemp -d "${TMPDIR:-/tmp}/zcl-eqparams-selftest.XXXXXX")"
    trap 'rm -rf -- "$work"' EXIT
    mkdir -p "$work/docs"
    printf 'ZClassic is Equihash 200,9 and always will be.\n' \
        > "$work/docs/PLANTED.md"
    if scan_prose "$work" >/dev/null 2>&1; then
        echo "check_equihash_params: SELFTEST FAIL — a planted flat 200,9 claim was not detected" >&2
        exit 2
    fi
    printf 'Mainnet is 192,7 from the Bubbles height; 200,9 applies before it.\n' \
        > "$work/docs/PLANTED.md"
    if ! scan_prose "$work" >/dev/null 2>&1; then
        echo "check_equihash_params: SELFTEST FAIL — a correctly qualified sentence was reported" >&2
        exit 2
    fi
    echo "[check_equihash_params] SELFTEST PASS (flat claim detected, qualified claim allowed)"
    exit 0
fi

status=0

# ── 1. the generated page still matches the consensus tables ─────────────
TOOL="build/bin/equihash-params-fact"
if [ ! -x "$TOOL" ]; then
    echo "check_equihash_params: FAIL — could not build $TOOL" >&2
    echo "  run: make tools/equihash-params-fact" >&2
    exit 1
fi
fresh="$(mktemp)"
trap 'rm -f -- "$fresh"' EXIT
"$TOOL" "$fresh"
if [ ! -f "$DOC" ]; then
    echo "check_equihash_params: FAIL — $DOC is missing; run: make equihash-facts" >&2
    status=1
elif ! diff -u "$DOC" "$fresh" >/dev/null; then
    echo "check_equihash_params: FAIL — $DOC no longer matches the consensus tables:" >&2
    diff -u "$DOC" "$fresh" | head -40 >&2
    echo "  regenerate it: make equihash-facts" >&2
    status=1
fi

# ── 2. no flat present-tense 200,9 claim anywhere else ───────────────────
if ! scan_prose "$ROOT"; then
    cat >&2 <<'MSG'

check_equihash_params: the line(s) above state Equihash 200,9 as what the
chain IS. Mainnet has been height-selected 192,7 since the Bubbles activation
height; 200,9 describes only the blocks below it.

  Say which blocks you mean — "before Bubbles", "at launch", "pre-Bubbles",
  or name the height — or point at docs/EQUIHASH_PARAMS.md, which is
  generated from the consensus tables and cannot drift.
MSG
    status=1
fi

if [ "$status" -eq 0 ]; then
    echo "check_equihash_params: OK — $DOC matches consensus, no flat 200,9 claim"
fi
exit "$status"
