#!/usr/bin/env bash
# Gate: every cookbook recipe still works, and the document still matches
# the registry (HARD).
#
# config/cookbook.def is the one place the answer to "how do I do X in this
# checkout" is written down. Writing an answer down buys the staleness
# problem: the command gets renamed, the file moves, and the recipe keeps
# reading as true. This gate is the price.
#
#   RUN rows   the command is actually executed and the expected token must
#              appear in its output. Not "the binary exists" — the answer is
#              produced.
#   ASK rows   for a command its own menu calls background latency. Running
#              it inside a lint gate would make the gate as slow as the
#              command, so what is checked is that the command still exists
#              and still reports itself ready. That is weaker than running
#              it, and it is stated here rather than hidden.
#   READ rows  the cited file must be tracked and must still contain the
#              symbol the recipe points at.
#
# It also regenerates docs/COOKBOOK.md from the registry and requires the
# committed file to match byte for byte, so the prose cannot drift from the
# rows. `--fix` rewrites it.
#
# NO FREE-FORM COMMANDS. A gate that runs whatever a string says is a gate
# that runs whatever anyone puts in a .def. The tool set is closed (Z23_DEV),
# arguments are split without a shell, and any argument carrying a character
# outside [A-Za-z0-9_./= -] is refused before anything is executed.
#
# Per repo law it FAILS LOUD on an empty scan set: a registry that stopped
# parsing must never read as clean.
#
# Exit: 0 clean, 1 a stale recipe or a drifted document, 2 hollow scan.
set -euo pipefail
cd "$(dirname "$0")/../.." || exit 2

GATE="check_cookbook"
DEF="${ZCL_COOKBOOK_DEF:-config/cookbook.def}"
DOC="${ZCL_COOKBOOK_DOC:-docs/COOKBOOK.md}"
BIN_DIR="${ZCL_LINT_BIN_DIR:-build/bin}"
ROW_FLOOR="${ZCL_COOKBOOK_ROW_FLOOR:-10}"
RUN_TIMEOUT="${ZCL_COOKBOOK_TIMEOUT:-120}"

FIX=0
SELFTEST=0
for arg in "$@"; do
    case "$arg" in
        --fix)      FIX=1 ;;
        --selftest) SELFTEST=1 ;;
        *) echo "$GATE: unknown argument '$arg'" >&2; exit 2 ;;
    esac
done

fail=0
note() { printf '%s\n' "$*"; }
bad()  { printf 'FAIL: %s\n' "$*"; fail=1; }

# ── parse ────────────────────────────────────────────────────────────────
# One record per line: KIND<TAB>field<TAB>field...
# SECTION rows carry their title; recipe rows carry their quoted fields in
# order, with the unquoted tool token appended for RUN rows.
parse_rows() {
    awk '
    /^(SECTION|RECIPE_RUN|RECIPE_ASK|RECIPE_READ)\(/ {
        collecting = 1; buf = ""; kind = $0
        sub(/\(.*$/, "", kind)
    }
    collecting { buf = buf " " $0 }
    collecting && /\)[[:space:]]*$/ {
        collecting = 0
        n = 0; rest = buf
        while (match(rest, /"([^"\\]|\\.)*"/)) {
            parts[++n] = substr(rest, RSTART + 1, RLENGTH - 2)
            rest = substr(rest, RSTART + RLENGTH)
        }
        tool = ""
        if (buf ~ /,[[:space:]]*Z23_DEV[[:space:]]*,/) tool = "Z23_DEV"
        printf "%s", kind
        for (i = 1; i <= n; i++) printf "\t%s", parts[i]
        if (tool != "") printf "\t%s", tool
        printf "\n"
    }
    ' "$1"
}

# ── argument safety ──────────────────────────────────────────────────────
args_are_safe() {
    case "$1" in
        *[!A-Za-z0-9_./=\ -]*) return 1 ;;
        "") return 1 ;;
    esac
    return 0
}

# ── generate the document ────────────────────────────────────────────────
generate_doc() {
    local out="$1"
    {
        printf '# Z23 cookbook\n\n'
        printf '<!-- GENERATED FROM config/cookbook.def BY tools/lint/check_cookbook.sh --fix.\n'
        printf '     DO NOT EDIT THIS FILE. Edit the registry and regenerate. -->\n\n'
        printf 'One question, one answer. This is the lookup table, not the workflow:\n'
        printf '`docs/DEVELOPING.md` is the ORDER you do things in, and you read it once.\n'
        printf 'Come back here every time you forget the exact incantation.\n\n'
        printf 'Every recipe below is checked by `make check-cookbook`. A RUN recipe has\n'
        printf 'its command executed and its expected token required in the output. An ASK\n'
        printf 'recipe is one whose command is too slow to run in a lint gate, so only its\n'
        printf 'existence and readiness are checked. A READ recipe cites code that must\n'
        printf 'still be tracked and must still contain the symbol named.\n'
        while IFS=$'\t' read -r kind f1 f2 f3 f4 f5; do
            case "$kind" in
            SECTION)
                printf '\n## %s\n' "$f1" ;;
            RECIPE_RUN)
                printf '\n### %s\n\n' "$f2"
                printf '    z23 %s\n\n' "$f3"
                printf 'Look for `%s` in the output. (`%s`, RUN)\n' "$f4" "$f1" ;;
            RECIPE_ASK)
                printf '\n### %s\n\n' "$f2"
                printf '    z23 %s\n\n' "$(printf '%s' "$f3" | tr '.' ' ')"
                printf 'Slower than the rest, so the gate checks only that it is `%s`. (`%s`, ASK)\n' \
                       "$f4" "$f1" ;;
            RECIPE_READ)
                printf '\n### %s\n\n' "$f2"
                printf 'Worked example: `%s`, look for `%s`. (`%s`, READ)\n' "$f3" "$f4" "$f1" ;;
            esac
        done < <(parse_rows "$DEF")
    } > "$out"
}

# ── selftest: the matcher must demonstrate it still fires ────────────────
if [ "$SELFTEST" = "1" ]; then
    tmp="$(mktemp -d)"
    trap 'rm -rf "$tmp"' EXIT
    cat > "$tmp/good.def" <<'EOF'
SECTION("A heading")
RECIPE_READ("a-row", "A question?", "Makefile", "all")
EOF
    got="$(parse_rows "$tmp/good.def" | tr '\t' '|')"
    want=$'SECTION|A heading\nRECIPE_READ|a-row|A question?|Makefile|all'
    if [ "$got" != "$want" ]; then
        echo "FAIL: $GATE selftest — parser output changed"
        echo "  got:  $got"
        echo "  want: $want"
        exit 2
    fi
    args_are_safe "code have retrieval" || { echo "FAIL: selftest — safe args refused"; exit 2; }
    if args_are_safe 'code have; rm -rf /'; then
        echo "FAIL: $GATE selftest — a shell metacharacter was accepted"
        exit 2
    fi
    if args_are_safe ""; then
        echo "FAIL: $GATE selftest — empty arguments were accepted"
        exit 2
    fi
    echo "$GATE: selftest OK"
    exit 0
fi

[ -f "$DEF" ] || { echo "FAIL: $GATE — registry '$DEF' is missing"; exit 2; }

ROWS="$(parse_rows "$DEF" | grep -c . || true)"
if [ "$ROWS" -lt "$ROW_FLOOR" ]; then
    echo "FAIL: $GATE — parsed only $ROWS row(s) from $DEF, floor is $ROW_FLOOR."
    echo "  A registry that stopped parsing must not read as clean."
    exit 2
fi

Z23="$BIN_DIR/z23-dev"
runnable=1
if [ ! -x "$Z23" ]; then
    runnable=0
fi

seen_ids=""
runs=0; asks=0; reads=0
while IFS=$'\t' read -r kind f1 f2 f3 f4 f5; do
    case "$kind" in
    SECTION)
        [ -n "$f1" ] || bad "an empty SECTION title"
        continue ;;
    esac

    case "$f1" in
        *[!a-z0-9-]*|"") bad "recipe id '$f1' is not kebab-case" ;;
    esac
    case " $seen_ids " in
        *" $f1 "*) bad "duplicate recipe id '$f1'" ;;
        *) seen_ids="$seen_ids $f1" ;;
    esac
    [ -n "$f2" ] || bad "recipe '$f1' has no question"

    case "$kind" in
    RECIPE_RUN)
        runs=$((runs + 1))
        [ "$f5" = "Z23_DEV" ] || bad "recipe '$f1' names an unknown tool"
        if ! args_are_safe "$f3"; then
            bad "recipe '$f1' has unsafe or empty arguments: '$f3'"
            continue
        fi
        if [ "$runnable" = "0" ]; then
            bad "recipe '$f1' cannot be checked: '$Z23' is not built"
            continue
        fi
        read -r -a argv <<< "$f3"
        out="$(timeout "$RUN_TIMEOUT" "$Z23" "${argv[@]}" 2>&1 || true)"
        case "$out" in
            *"$f4"*) ;;
            *) bad "recipe '$f1': 'z23 $f3' no longer prints '$f4'" ;;
        esac ;;
    RECIPE_ASK)
        asks=$((asks + 1))
        if ! args_are_safe "$f3"; then
            bad "recipe '$f1' names an unsafe command path: '$f3'"
            continue
        fi
        if [ "$runnable" = "0" ]; then
            bad "recipe '$f1' cannot be checked: '$Z23' is not built"
            continue
        fi
        out="$(timeout "$RUN_TIMEOUT" "$Z23" discover describe "$f3" 2>&1 || true)"
        case "$out" in
            *"$f4"*) ;;
            *) bad "recipe '$f1': command '$f3' is no longer '$f4'" ;;
        esac ;;
    RECIPE_READ)
        reads=$((reads + 1))
        if ! git ls-files --error-unmatch -- "$f3" >/dev/null 2>&1; then
            bad "recipe '$f1' cites '$f3', which is not a tracked file"
            continue
        fi
        if ! grep -qF -- "$f4" "$f3"; then
            bad "recipe '$f1' cites '$f3' for '$f4', which is no longer in it"
        fi ;;
    *)
        bad "unknown row kind '$kind'" ;;
    esac
done < <(parse_rows "$DEF")

# ── the document must match the registry ─────────────────────────────────
gen="$(mktemp)"
trap 'rm -f "$gen"' EXIT
generate_doc "$gen"
if [ "$FIX" = "1" ]; then
    if [ ! -f "$DOC" ] || ! cmp -s "$gen" "$DOC"; then
        cp "$gen" "$DOC"
        note "fixed: $DOC regenerated from $DEF"
    fi
elif [ ! -f "$DOC" ]; then
    bad "$DOC does not exist; run tools/lint/check_cookbook.sh --fix"
elif ! cmp -s "$gen" "$DOC"; then
    bad "$DOC has drifted from $DEF; run tools/lint/check_cookbook.sh --fix"
fi

if [ "$fail" != "0" ]; then
    echo "$GATE: FAILED"
    exit 1
fi
note "$GATE: clean — $runs run, $asks ask, $reads read recipe(s) from $DEF; $DOC matches"
exit 0
