#!/usr/bin/env bash
# Copyright 2026 Rhett Creighton - Apache License 2.0
#
# Lint gate — the hot-swap consensus pin is present, current, and CONSUMED.
#
# engine/modules/hotswap/include/hotswap/core_seal_root.h mirrors the ROOT line of
# core/MANIFEST.sha3 so that a Tier-2 hot-swap module and the resident it mounts
# into can compare which sealed consensus core each was compiled against. The
# mirror is generated by `make core-seal`; if a seal re-cut lands without it,
# every module keeps claiming the OLD root and the pin silently stops meaning
# anything. That is the failure mode this gate exists for.
#
# Three legs, because a correct value that nothing reads is not a pin:
#
#   1. CURRENT  — the mirror matches core/MANIFEST.sha3's ROOT byte for byte
#                 (delegated to the generator's own --check, so there is no
#                 second copy of the format to drift).
#   2. EXPORTED — hotswap_module.h includes the mirror and its module emitter
#                 emits the pin symbol, so every built .so carries one.
#   3. ENFORCED — hotswap_activate.c compares that symbol against
#                 ZCL_CORE_SEAL_ROOT on BOTH dlsym paths: the resident mount and
#                 the offline verifier. A pin enforced on only one of them means
#                 `make hotswap-verify` is greener than a real mount, which is
#                 the false-pass direction.
#
# Every leg is always observable — no build, no node, no datadir — so this gate
# has no skip path.
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT_DIR"

MIRROR="engine/modules/hotswap/include/hotswap/core_seal_root.h"
MODULE_H="engine/modules/hotswap/include/hotswap/hotswap_module.h"
ACTIVATE_C="engine/modules/hotswap/src/hotswap_activate.c"
GEN="tools/scripts/gen_core_seal_root.sh"

fail=0
note() { printf '  %s\n' "$1"; }
bad() { printf 'core_seal_root_mirror: FAIL — %s\n' "$1" >&2; fail=1; }

for f in "$MIRROR" "$MODULE_H" "$ACTIVATE_C" "$GEN"; do
    [ -r "$f" ] || { bad "$f is missing or unreadable"; }
done
[ "$fail" -eq 0 ] || exit 1

# ── leg 1: current ────────────────────────────────────────────────────────
if out="$(bash "$GEN" --check 2>&1)"; then
    note "current  : ${out#core_seal_root: }"
else
    printf '%s\n' "$out" >&2
    bad "the mirror does not match core/MANIFEST.sha3 (run 'make core-seal')"
fi

# ── leg 2: exported ───────────────────────────────────────────────────────
if grep -q '^#include "hotswap/core_seal_root.h"' "$MODULE_H"; then
    note "exported : $MODULE_H includes the mirror"
else
    bad "$MODULE_H does not include \"hotswap/core_seal_root.h\" — modules would compile without a pin"
fi

if grep -q 'zcl_hotswap_module_core_seal_root\[\] = ZCL_CORE_SEAL_ROOT;' "$MODULE_H"; then
    note "exported : the module emitter stamps the pin symbol"
else
    bad "$MODULE_H's ZCL_HOTSWAP_MODULE_LEAVES does not emit zcl_hotswap_module_core_seal_root"
fi

# ── leg 3: enforced on BOTH dlsym paths ───────────────────────────────────
enforced="$(grep -c 'module_consensus_pin_ok(' "$ACTIVATE_C" || true)"
# One definition + one call per dlsym path (resident mount, offline verifier).
if [ "${enforced:-0}" -ge 3 ]; then
    note "enforced : $ACTIVATE_C checks the pin on $((enforced - 1)) dlsym path(s)"
else
    bad "$ACTIVATE_C has ${enforced:-0} module_consensus_pin_ok reference(s); expected a definition plus a call on BOTH dlsym paths"
fi

# POSIX ERE, not GNU BRE alternation `\|` (which Apple's grep reads as a
# literal backslash-pipe): that read counted 1 dlsym site instead of 2 and
# failed the gate as if a pin check were missing.
sites="$(grep -Ec 'dlsym\(handle,($|[[:space:]]ZCL_HOTSWAP_MODULE_SYMBOL\))' "$ACTIVATE_C" || true)"
if [ "${sites:-0}" -ne $((enforced - 1)) ]; then
    bad "$ACTIVATE_C resolves ${sites:-0} zcl_hotswap_module symbol(s) but pins $((enforced - 1)); every dlsym path must carry the check"
fi

if [ "$fail" -ne 0 ]; then
    echo "core_seal_root_mirror: the hot-swap consensus pin is broken." >&2
    echo "  A module built against a different sealed consensus core carries its own" >&2
    echo "  stale copy of the inline consensus arithmetic. The pin is what refuses it." >&2
    exit 1
fi
echo "core_seal_root_mirror: OK — pin current, exported by the module emitter, enforced on every dlsym path"
