/* Copyright 2026 Rhett Creighton - Apache License 2.0
 *
 * The adapter registry: exactly one row per property kind, in
 * METAVERSE_KIND_TABLE order, dispatched centrally.
 *
 * A kind with no reader yet is a row carrying `unavailable_reason`, never a
 * missing row — a kind that silently vanished from the catalog is
 * indistinguishable from a kind that owns nothing.
 *
 * ── WHY THERE IS NO HAND-WRITTEN LIST HERE ────────────────────────────────
 * Both tables below are GENERATED by walking METAVERSE_KIND_TABLE, so "one
 * row per kind, in order, no duplicates, no omissions" is not a rule anyone
 * has to keep — it is the shape of the expansion. Each kind supplies its own
 * one-line declaration, MV_ADAPTER_<KIND>, which must be exactly one of
 * MV_WIRED(fn) or MV_UNAVAILABLE("reason"):
 *
 *   - a kind added to the vocabulary with no declaration does not compile
 *     (MV_ADAPTER_<NEW> expands to an undeclared identifier),
 *   - a declaration that is neither form trips the per-kind _Static_assert,
 *   - and the row-count assertions catch anything that survived both.
 *
 * The `unavailable_reason` strings are the honest current state of each
 * unwired kind. They name what is missing, not "TODO" — a caller reading the
 * catalog learns why a kind cannot be projected and where the read API would
 * have to come from. */

#include "metaverse_priv.h"

#include "metaverse/property_adapter.h"

#include <stddef.h>

/* ── One declaration per kind. This is the only hand-written list. ───────── */

#define MV_ADAPTER_CONTENT       MV_WIRED(metaverse_adapter_content)
#define MV_ADAPTER_ZCODE_PACKAGE MV_WIRED(metaverse_adapter_zcode_package)

#define MV_ADAPTER_ZNAM_NAME     MV_WIRED(metaverse_adapter_znam)
#define MV_ADAPTER_ZSLP_ASSET    MV_WIRED(metaverse_adapter_zslp)
/* ── MV_MVP_SCOPE decision (docs/METAVERSE_MVP.md, criterion MM3) ──────────
 * The metaverse MVP catalog surface covers the four kinds a datadir alone
 * can prove: content, zcode_package, znam_name, zslp_asset. The four kinds
 * below are explicitly OUT of MVP scope — not unimplemented: their
 * authorities are runtime diagnostics or node.db tables this read path may
 * not open, so no honest datadir-only projection exists for them today.
 * Wiring one means defining its read authority first, and the scope
 * partition is pinned by t_mvp_scope_decision() in
 * lib/test/src/test_metaverse_catalog.c so a silent re-classification fails
 * the test suite rather than drifting. */
#define MV_ADAPTER_HOSTED_SERVICE                                            \
    MV_UNAVAILABLE("hosted services are enumerated by the live diagnostics " \
                   "registry, which requires a running node; no "            \
                   "datadir-only read exists")
#define MV_ADAPTER_ENDPOINT_ONION                                            \
    MV_UNAVAILABLE("onion endpoints are runtime state of the embedded Tor "  \
                   "service; no datadir-only read exists")
#define MV_ADAPTER_STOREFRONT_PRODUCT                                        \
    MV_UNAVAILABLE("storefront products live in db_store_product (node.db)," \
                   " which this read path may not open")
#define MV_ADAPTER_CONTRACT_SWAP                                             \
    MV_UNAVAILABLE("swap contracts live in db_swap_contract (node.db), "     \
                   "which this read path may not open")
/* Content-addressed, and still unreadable from a datadir — the two are not in
 * tension. A character is verified by RECOMPUTING it from the birth seed the
 * holder presents (metaverse/character_sheet.h), which needs no store at all;
 * what does not exist yet is anywhere on disk that ENUMERATES the seeds this
 * operator holds. Until a seed store exists, "list every character here" has
 * no honest datadir-only answer, so the row states that instead of returning
 * an empty list that would read as "this node owns no characters". */
#define MV_ADAPTER_CHARACTER_SHEET                                           \
    MV_UNAVAILABLE("a character is verified by recomputing it from the "     \
                   "birth seed presented with it; no datadir path "          \
                   "enumerates the seeds this node holds, so the catalog "   \
                   "cannot list them")

/* ── Proof that every kind declared exactly one of the two forms ─────────── */

#define MV_WIRED(fn_) 1
#define MV_UNAVAILABLE(why_) 2
#define MV_ADAPTER_FORM_ASSERT(id_, name_, authority_, settle_, wire_)       \
    _Static_assert((MV_ADAPTER_##id_) == 1 || (MV_ADAPTER_##id_) == 2,       \
                   "property kind " name_ " must declare exactly one "       \
                   "adapter row: MV_WIRED(fn) or MV_UNAVAILABLE(reason)");
METAVERSE_KIND_TABLE(MV_ADAPTER_FORM_ASSERT)
#undef MV_ADAPTER_FORM_ASSERT
#undef MV_WIRED
#undef MV_UNAVAILABLE

/* ── Expansion 1: the wired rows' providers, NULL where unavailable ─────── */

#define MV_WIRED(fn_) (fn_)
#define MV_UNAVAILABLE(why_) NULL
#define MV_ADAPTER_PROVIDER_ROW(id_, name_, authority_, settle_, wire_)      \
    MV_ADAPTER_##id_,

static const struct metaverse_adapter *(*const k_providers[])(void) = {
    METAVERSE_KIND_TABLE(MV_ADAPTER_PROVIDER_ROW)
};

#undef MV_ADAPTER_PROVIDER_ROW
#undef MV_WIRED
#undef MV_UNAVAILABLE

/* ── Expansion 2: the unavailable rows, from the SAME declarations ──────── */

#define MV_WIRED(fn_) NULL
#define MV_UNAVAILABLE(why_) (why_)
#define MV_ADAPTER_UNAVAILABLE_ROW(id_, name_, authority_, settle_, wire_)   \
    { .kind = METAVERSE_KIND_##id_,                                          \
      .unavailable_reason = MV_ADAPTER_##id_,                                \
      .list = NULL, .show = NULL, .store_ready = NULL },

static const struct metaverse_adapter k_unavailable[] = { /* hotswap-static-ok: leaf registration tables are immutable */
    METAVERSE_KIND_TABLE(MV_ADAPTER_UNAVAILABLE_ROW)
};

#undef MV_ADAPTER_UNAVAILABLE_ROW
#undef MV_WIRED
#undef MV_UNAVAILABLE

/* Row index i describes kind i+1: UNKNOWN owns no row. Both arrays are
 * generated from the same table, so they are the same length by
 * construction; asserting it is what turns a future hand-edit into a compile
 * error rather than an off-by-one lookup. */
_Static_assert(sizeof(k_providers) / sizeof(k_providers[0]) ==
                   (size_t)METAVERSE_KIND_COUNT - 1u,
               "every kind in METAVERSE_KIND_TABLE needs exactly one adapter "
               "row (wired or explicitly unavailable): a kind with no row "
               "would drop out of the catalog silently");
_Static_assert(sizeof(k_unavailable) / sizeof(k_unavailable[0]) ==
                   sizeof(k_providers) / sizeof(k_providers[0]),
               "the provider and unavailable-row tables must stay parallel");

size_t metaverse_adapter_count(void)
{
    /* Every kind except UNKNOWN has a row. */
    return (size_t)METAVERSE_KIND_COUNT - 1u;
}

/* Resolved per call from immutable data: no mutable registry state, so this
 * is reentrant and safe to call from any thread without a lock. */
const struct metaverse_adapter *metaverse_adapter_for(enum metaverse_kind k)
{
    size_t i;

    if (!metaverse_kind_valid(k))
        return NULL;
    i = (size_t)k - 1u;
    if (k_providers[i])
        return k_providers[i]();
    return &k_unavailable[i];
}

const struct metaverse_adapter *metaverse_adapter_at(size_t i)
{
    if (i >= metaverse_adapter_count())
        return NULL;
    /* Row i is kind i+1: UNKNOWN owns no row. */
    return metaverse_adapter_for((enum metaverse_kind)(i + 1u));
}

bool metaverse_adapter_ready(const struct metaverse_adapter *adapter)
{
    return adapter && !adapter->unavailable_reason && adapter->list &&
           adapter->show;
}
