/* Copyright 2026 Rhett Creighton - Apache License 2.0
 *
 * ZCL_CORE_SEAL_TREE + ZCL_CORE_SEAL_SECTION_ROWS — the sealed consensus core's
 * per-SECTION identity, as compile-time strings. AUTO-GENERATED by
 * `make core-seal-sections` (and by `make core-seal`) from the SECTION/TREE
 * lines of core/MANIFEST.sha3. Do not edit by hand.
 *
 * WHY IT IS NOT UNDER core/. Same reason as hotswap/core_seal_root.h: a mirror
 * living inside the sealed set would be part of its own input. It lives beside
 * the consumer, and test_hotswap_module's
 * "compiled section table matches core/MANIFEST.sha3" case proves the two
 * agree — a forgotten regeneration fails the hotswap_module test group.
 *
 * WHAT IT IS FOR. hotswap/core_seal_root.h carries ONE value: the flat ROOT
 * fold over every sealed file. It is a whole-tree pin — every module is
 * invalidated by a change to any of the 70 sealed files. These rows carry the
 * SAME sealed set at directory granularity, in cognition/modules/codeindex's source Merkle
 * dialect (a structurally different fold over the same bytes), so a module can
 * RECORD which sections it actually compiled against and the resident can
 * verify each of them IN ADDITION to ROOT.
 *
 * THIS FILE RELAXES NOTHING. The ROOT equality check is unchanged and still
 * runs first. A module that declares sections must ALSO match every one of
 * them and the TREE; a module that declares a section this resident does not
 * have is refused. The section rows are strictly additional evidence.
 *
 * The N-ary node digest for a directory covers that directory RECURSIVELY, so
 * an ancestor row ("core") subsumes its descendants. A module declares the
 * DEEPEST section containing each sealed file in its compile closure and never
 * its ancestors — an ancestor digest would pin sibling directories the module
 * never saw, which is the opposite of what section granularity is for.
 */

#ifndef ZCL_HOTSWAP_CORE_SEAL_SECTIONS_H
#define ZCL_HOTSWAP_CORE_SEAL_SECTIONS_H

/* Root node digest over the whole sealed set (dirpath ""). */
#define ZCL_CORE_SEAL_TREE \
    "5b138b7ed3e1634f2846f6b46981441e4fb46df193358e14cc917726310c51a5"

/* SECTION lines in core/MANIFEST.sha3 at generation time. */
#define ZCL_CORE_SEAL_SECTION_COUNT 80u

/* X-macro row list. The consumer supplies ZCL_HOTSWAP_SECTION_ROW(path, hex);
 * hotswap/hotswap_module.h defines it as an initializer element. */
#define ZCL_CORE_SEAL_SECTION_ROWS \
    ZCL_HOTSWAP_SECTION_ROW("core", \
        "a9e77cb3ba0489cec5fb728bb55e9bb2e747756a9dcc4e1b71a559d1f9f4c360") \
    ZCL_HOTSWAP_SECTION_ROW("core/chainparams", \
        "8681e4e8469b454c43c9d715d1111a7702a3b9bc8527f8119234a18e030ec183") \
    ZCL_HOTSWAP_SECTION_ROW("core/chainparams/include", \
        "1e5945d164d76144d16dcf3160716e529396441eef1b21a1687c7455aa89e6a8") \
    ZCL_HOTSWAP_SECTION_ROW("core/chainparams/include/chain", \
        "30a039b47f4f9e8eebe5efe28f0a4ba77b2d9f14f383db19b46c024eec2296ed") \
    ZCL_HOTSWAP_SECTION_ROW("core/chainparams/src", \
        "6b2a586c73fc46a7ab3c7092d9d4ae08b16bda273d3e64b86e538894fdb5140c") \
    ZCL_HOTSWAP_SECTION_ROW("core/consensus", \
        "fee86f21ef5f8cec3ea433e07970a8e273fc0898924aa094186334f09df1f017") \
    ZCL_HOTSWAP_SECTION_ROW("core/consensus/include", \
        "9559692f7fa69fb22ef84266cbf87183f16208aa1a9e6ed3ee9178545d0cc295") \
    ZCL_HOTSWAP_SECTION_ROW("core/consensus/include/domain", \
        "6072e26bba85c0a24adbd98da9749c7e6b8ac10872726a2c7272df8cc7322fc0") \
    ZCL_HOTSWAP_SECTION_ROW("core/consensus/include/domain/consensus", \
        "b8a8cb81bbcb38ef4e106701e3df63fb1a4385e27c904f592d8d686dc310879f") \
    ZCL_HOTSWAP_SECTION_ROW("core/consensus/src", \
        "086ae2be2f22ac1858d4db41fa17b1130a078114864773a1a8435298ed50e08a") \
    ZCL_HOTSWAP_SECTION_ROW("core/math", \
        "4a12df854665934805645f7b11b9ce279b93b7568fe58dde37f68d84913813da") \
    ZCL_HOTSWAP_SECTION_ROW("core/math/include", \
        "3d74828940990b6914192791641041d1ad63de1b84d7693d2533f1c9b29a7edd") \
    ZCL_HOTSWAP_SECTION_ROW("core/math/include/core", \
        "13bc29100524578193cb79036f24fe9e1d8538c0f45dcc4dd87956a25f4f2b38") \
    ZCL_HOTSWAP_SECTION_ROW("core/math/src", \
        "bed7851826222b99834c6ee74bb3e7ce6155798a5ef78c798fe2f836bbf30862") \
    ZCL_HOTSWAP_SECTION_ROW("core/modules", \
        "a7d3195cab46e42b5b0c46ee017c51f9ff6db9264c37123fb64a683039a47867") \
    ZCL_HOTSWAP_SECTION_ROW("core/modules/bloom", \
        "d39a267ed7843199fea7ad58a9c6cbc6d0acd538ff04e13d69147a51924c8648") \
    ZCL_HOTSWAP_SECTION_ROW("core/modules/bloom/include", \
        "25f9f764136ebc796a9aaed6dc708deba3347052954808e4efacd66eed7255c6") \
    ZCL_HOTSWAP_SECTION_ROW("core/modules/bloom/include/bloom", \
        "2648501012a71f5658485e08ef8fb567f46f716f1fd96cbfcb93666c234a6686") \
    ZCL_HOTSWAP_SECTION_ROW("core/modules/bloom/src", \
        "34c5eb57f8d1fe1da5eef03661d47796a85ac1eb2689552332d8e959751796b5") \
    ZCL_HOTSWAP_SECTION_ROW("core/modules/chain", \
        "ce6bcab17c008ca71a49a06e4a9c994f66f174eddce86043bdc851ec0151183f") \
    ZCL_HOTSWAP_SECTION_ROW("core/modules/chain/include", \
        "e1a26cc48bd376656def12c32ac685818e4b41d469f016991c7eab67c138657e") \
    ZCL_HOTSWAP_SECTION_ROW("core/modules/chain/include/chain", \
        "abed548f8d4ea98e94f93fe57a7960363b14b5e05500981fa2aaa1fe2d47e60d") \
    ZCL_HOTSWAP_SECTION_ROW("core/modules/chain/src", \
        "df773302b43804f0ad05e4f190a8fa0a404d2a691b09e01fa749bb41e03688f3") \
    ZCL_HOTSWAP_SECTION_ROW("core/modules/coins", \
        "d2318a6464b70cdd6385101f6dce5357d56e8218a006c2756de240a76fb0e7ce") \
    ZCL_HOTSWAP_SECTION_ROW("core/modules/coins/include", \
        "54af65fed882eb12e6e5fc15e47e05848719dca863fc7bc4134c1d9a4c22d994") \
    ZCL_HOTSWAP_SECTION_ROW("core/modules/coins/include/coins", \
        "1eb19c1df39eca30cab7c8266c68f1cfb86dc5f23009f40ce6e2945eed281345") \
    ZCL_HOTSWAP_SECTION_ROW("core/modules/coins/src", \
        "7e5061b9d2b9204e4acaa304bf6660e220fcf2d63dbd6f12d7bba4bbaf6d4a44") \
    ZCL_HOTSWAP_SECTION_ROW("core/modules/core", \
        "9f93a9d826d9998bae5496b332226098a2ed5ff28255d01b62451433c203300d") \
    ZCL_HOTSWAP_SECTION_ROW("core/modules/core/include", \
        "4f0656acb8d6958bb8411ddb13b248dec101a956c7350c21da2f52f99855a23c") \
    ZCL_HOTSWAP_SECTION_ROW("core/modules/core/include/core", \
        "78f0863bca31bf01ed54641dc935515e10aa3f1dc7e2ccbeaa6c6ad379fc7326") \
    ZCL_HOTSWAP_SECTION_ROW("core/modules/core/src", \
        "549a6085d3be922026f17bfe86e1192b090ee8b18c8cccd272c941c9007750ab") \
    ZCL_HOTSWAP_SECTION_ROW("core/modules/crypto", \
        "bbd6fd0b37b8e52df41f8bbc1eef2173d6a7cb452498ece10a4a281232ee6f0c") \
    ZCL_HOTSWAP_SECTION_ROW("core/modules/crypto/include", \
        "6ac3b06baae885ea6e3fce7de901fcb93ad67e80d2a69acb59065d8bfd499620") \
    ZCL_HOTSWAP_SECTION_ROW("core/modules/crypto/include/crypto", \
        "db57412a9857425a13e1db816a2017905171cfdcc34f11f6b07581b108869400") \
    ZCL_HOTSWAP_SECTION_ROW("core/modules/crypto/src", \
        "925e641a5af97e60f0dfcf77122b80f82ce742e96e17475882b8b4211cb364a2") \
    ZCL_HOTSWAP_SECTION_ROW("core/modules/crypto/tests", \
        "dfc69c2fd31658d73e5f5669e33138fcc7338b62f805b8682b0f854df9fbb152") \
    ZCL_HOTSWAP_SECTION_ROW("core/modules/crypto_registry", \
        "3cdf69015a07f14ae8fc4e33b69e5605a4101de6631fa0f75c259e441954e4dc") \
    ZCL_HOTSWAP_SECTION_ROW("core/modules/crypto_registry/include", \
        "6734f7e2ef8ae44435c89c858b708bbe8c398d39c00f2e729aa43515aa910afe") \
    ZCL_HOTSWAP_SECTION_ROW("core/modules/crypto_registry/include/crypto_registry", \
        "cc088b7a59081a0253991be8827b38ac01f90b5afc50039a9a7cc0d488038a87") \
    ZCL_HOTSWAP_SECTION_ROW("core/modules/crypto_registry/src", \
        "36c0bd374a836c87cb7dda1acef20ca21a4695f146417e532855230440da881e") \
    ZCL_HOTSWAP_SECTION_ROW("core/modules/mining", \
        "9bb689fbd1734fae9564c2b5145c303c67818f0933ccfcdcc5f4dbf5740b2415") \
    ZCL_HOTSWAP_SECTION_ROW("core/modules/mining/include", \
        "81e82305e0525b5d77a8532a519538cc4c174150a1faa38fb55b26c18839271d") \
    ZCL_HOTSWAP_SECTION_ROW("core/modules/mining/include/mining", \
        "b83813758d4a6dfa9da4b2e64d463cc78d0a0cc1da07a170cca30fc454996ba3") \
    ZCL_HOTSWAP_SECTION_ROW("core/modules/mining/src", \
        "e02cf7266af035601a3ebfb06b461ba372af218c889beb6576f4a01bc03cee9f") \
    ZCL_HOTSWAP_SECTION_ROW("core/modules/net", \
        "845fa4f8ff367e1be6e6ae2732e0114f3b96e528cca0fb08fb7992dcb750780b") \
    ZCL_HOTSWAP_SECTION_ROW("core/modules/net/include", \
        "fdf2d89627ed0248da2ad0cd2a91e0a6fe4bfc0932eb347a61e60462dd34c04c") \
    ZCL_HOTSWAP_SECTION_ROW("core/modules/net/include/net", \
        "dc9dc59603749674ff8385b633376507cc5f13ac9555385e4e9e1933788eea71") \
    ZCL_HOTSWAP_SECTION_ROW("core/modules/net/src", \
        "378eefa89d407f8a9332d67b46025146400001bfa57f1875af5a1248fb2fa2c2") \
    ZCL_HOTSWAP_SECTION_ROW("core/modules/noise", \
        "a2e09def577166996ffa46fd3694f7c2d7633e3cf2da0bf3a8621cfb283f8c04") \
    ZCL_HOTSWAP_SECTION_ROW("core/modules/noise/include", \
        "3eb0307ed7b4de64260956826200021628b42f9152f57674241485f7c764b29d") \
    ZCL_HOTSWAP_SECTION_ROW("core/modules/noise/include/noise", \
        "bebb3de57b8217f83c9d1bd6f4fa780983dc7210caaf121b5954a685484ac111") \
    ZCL_HOTSWAP_SECTION_ROW("core/modules/noise/src", \
        "6b86727634198f74244e9d7a4dc6d2e65e87bfc609c33f553f97d96e544a31b0") \
    ZCL_HOTSWAP_SECTION_ROW("core/modules/policy", \
        "8ba2d75d61c38591d93b6181ecda817255a0f119927fbd1e39a6fcc8af15c40a") \
    ZCL_HOTSWAP_SECTION_ROW("core/modules/policy/include", \
        "5a6bee138a60997003977f0554a65e50b0d60fd61f784745c7d2803abd70627d") \
    ZCL_HOTSWAP_SECTION_ROW("core/modules/policy/include/policy", \
        "07f78ba6f0e71688f6e8730c9fb8e8000c3d3273f52454595fdeb2ea117be781") \
    ZCL_HOTSWAP_SECTION_ROW("core/modules/policy/src", \
        "be3428562506144a6eaa807fb2a8632e90037b7898ba2545255f13ee3192712d") \
    ZCL_HOTSWAP_SECTION_ROW("core/modules/primitives", \
        "127899b104bab13d0b9249346c1918aec82a5608ef72ac52217727304a31966d") \
    ZCL_HOTSWAP_SECTION_ROW("core/modules/primitives/include", \
        "fb543e2fcd2ab6312213620b54dbec42ea1e25ee9bab19b87432c2b3ebbffeed") \
    ZCL_HOTSWAP_SECTION_ROW("core/modules/primitives/include/primitives", \
        "c2dbe794dcd4eeb295573eccaa8f812fb009d2372986242c042f7ebc94b676c5") \
    ZCL_HOTSWAP_SECTION_ROW("core/modules/primitives/src", \
        "5b123ca06dbb27096c81daf97c370e56c4000e6b767ad70505d576bab20f898f") \
    ZCL_HOTSWAP_SECTION_ROW("core/modules/sapling", \
        "f18c7d0260722836adc7bb3d5cdcd650b77f0dfaa666bc88d2468c860061d8d4") \
    ZCL_HOTSWAP_SECTION_ROW("core/modules/sapling/include", \
        "ee4fd3dd0261452c4f67cc902e96d70e11b671cdf529c40859dc1a65048709e9") \
    ZCL_HOTSWAP_SECTION_ROW("core/modules/sapling/include/sapling", \
        "fe6e6c955874ff75f1617c60521be674db13f0e9e9807a1122b29f0da19499fd") \
    ZCL_HOTSWAP_SECTION_ROW("core/modules/sapling/src", \
        "fc5bb58fb83b2c460681e7b4028947f74e9e627dbc4e7c34b4bdff75227e1f61") \
    ZCL_HOTSWAP_SECTION_ROW("core/modules/script", \
        "92d4b0e983b7b3da398f9078601f052c399d91e0f1c18a9aedaaaa6d861918e8") \
    ZCL_HOTSWAP_SECTION_ROW("core/modules/script/include", \
        "51d958bd263be269dbbc5382a93b9cd60ff7679ec7d09a65a23c44d66891adff") \
    ZCL_HOTSWAP_SECTION_ROW("core/modules/script/include/script", \
        "2ef92d21c5d0719d8858b64ab983008d24e5c7b6e19d8a5516c3356b2e095f17") \
    ZCL_HOTSWAP_SECTION_ROW("core/modules/script/src", \
        "261665a865d5a4c6dd270b6addfbf7ac41f6d6d888713852808c05a4aafc4d9e") \
    ZCL_HOTSWAP_SECTION_ROW("core/modules/sync", \
        "ce49cc17a8a501ffbf4b9bb1f497a38f0bc4cd75e8fc0bf925689dbc933d5672") \
    ZCL_HOTSWAP_SECTION_ROW("core/modules/sync/include", \
        "82735b8e88dae3b84992b7b38b736abe70680a906ffc7b52172d66213a83a5fb") \
    ZCL_HOTSWAP_SECTION_ROW("core/modules/sync/include/sync", \
        "5e5c92db20d1f1ad23c518912cef2de88b25029a0c0e4bbb31978ff864d3b51f") \
    ZCL_HOTSWAP_SECTION_ROW("core/modules/sync/src", \
        "38c840ddf54b51a4cf08e2701bfcb37fedf8212dcc13eabd8a1a6ffbb7c1b03b") \
    ZCL_HOTSWAP_SECTION_ROW("core/modules/validation", \
        "4f1c65c634b27e980958e5184ef465d251a17b2c5a05b3613c22e839593e686d") \
    ZCL_HOTSWAP_SECTION_ROW("core/modules/validation/include", \
        "eb368ee51a3939ee8d433a5175be4157d200aad25b1b29d9da7a0e5e69ae9b6f") \
    ZCL_HOTSWAP_SECTION_ROW("core/modules/validation/include/validation", \
        "71f64b87ab4638c2437de5bc6cec8459e17ba1879aab749a8f7ba01ac1272b74") \
    ZCL_HOTSWAP_SECTION_ROW("core/modules/validation/src", \
        "982a639d27b1e1429589692316ecd86ce45bc651776c3a184a5b461a3963c668") \
    ZCL_HOTSWAP_SECTION_ROW("core/params", \
        "9b023bcd18300a51052f45e69609bb741b2832e3ce6e6a02fd21a12ea94647c0") \
    ZCL_HOTSWAP_SECTION_ROW("core/params/include", \
        "e07dc0f2326862830b48105e02648f8d76dfeee9a859b7c56679c461e2cca7f1") \
    ZCL_HOTSWAP_SECTION_ROW("core/params/include/consensus", \
        "5680a2f2d804163e77f94854ee18838480d785b74b297265f2f8a77db9d02242") \
    ZCL_HOTSWAP_SECTION_ROW("core/params/src", \
        "8fdd673c41b8758e48c6fb225c15d7bbdf79f6816066a1d0c793d4bee2c5f6b1")

#endif /* ZCL_HOTSWAP_CORE_SEAL_SECTIONS_H */
