/* Copyright 2026 Rhett Creighton - Apache License 2.0
 *
 * ZCL_CORE_SEAL_ROOT — the sealed consensus core's identity, as a compile-time
 * string. AUTO-GENERATED by `make core-seal`
 * (tools/scripts/gen_core_seal_root.sh). Do not edit by hand.
 *
 * WHY THIS FILE IS NOT UNDER core/. It mirrors the ROOT line of
 * core/MANIFEST.sha3, and the manifest digests every selected tracked file
 * under core/ except the manifest itself.
 * A mirror living inside the sealed set would be part of its own input: writing
 * it would change the ROOT it had just recorded, forever. So it lives beside
 * the consumer instead, and tools/lint/check_core_seal_root_mirror.sh proves
 * the two agree — a forgotten regeneration fails `make lint`, it does not ship.
 *
 * WHAT IT IS FOR. A Tier-2 hot-swap module is compiled from ONE shape-leaf TU
 * and mounts into a resident node that supplies everything else, so the two
 * halves have to agree about the consensus layer they share. Nothing checked
 * that they did: hotswap_module_admit() verifies abi_version, fields, capacity,
 * the allowlist row, duplicates and the probe leaf — six stages, none of them
 * about consensus. (Tier-1's manifest path does compare a whole-tree build
 * identity, hotswap_loader.c; the real module ABI had no equivalent.)
 *
 * The gap is not theoretical. Sealed headers ship static inline bodies —
 * consensus_last_founders_reward_height() and
 * consensus_subsidy_slow_start_shift() among them — and every module that
 * includes one compiles a PRIVATE COPY of that body into its .so. Re-cut the
 * seal, rebuild the node, and a module built before the change still mounts,
 * still passes all six stages, and still runs its stale copy of the consensus
 * arithmetic. That is the cloned-ledger shape the architecture exists to
 * prevent, reached through a dlopen.
 *
 * Pinning the SEAL ROOT rather than a whole-tree build id is what keeps the
 * fast loop fast: editing a controller does not move this value, so the module
 * just built still mounts. Editing consensus does move it, and then every
 * module compiled against the old core is refused before leaf publication.
 *
 * SCOPE OF THE GUARANTEE. This is a generated, checked-in mirror, and nothing
 * in the BUILD forces it to be current: the hotswap-module-so recipe does not
 * depend on the core-seal target, so between a core/ edit and the next
 * 'make lint' the node and the module stamp the same STALE root and the pin
 * passes without meaning anything. check_core_seal_root_mirror.sh is the only
 * thing that catches that drift. The pin is therefore exactly as strong as
 * lint having run -- which is the intended design, lint being the backstop,
 * but it is the reason a seal re-cut must be followed by 'make core-seal' and
 * not merely by a successful build.
 *
 */

#ifndef ZCL_HOTSWAP_CORE_SEAL_ROOT_H
#define ZCL_HOTSWAP_CORE_SEAL_ROOT_H

/* SHA3-256 ROOT of core/MANIFEST.sha3 at generation time. */
#define ZCL_CORE_SEAL_ROOT \
    "eb2d4c960bff0c1b46f3991aa030d7bc01de00b599edb41a65ea657953a0388d"

#endif /* ZCL_HOTSWAP_CORE_SEAL_ROOT_H */
