/* Copyright 2026 Rhett Creighton - Apache License 2.0
 *
 * equihash_params_fact — emit the height-selected Equihash (N,K) table as a
 * GENERATED document, derived from the consensus code that actually decides
 * it.
 *
 * WHY THIS EXISTS. Documentation and code comments across this repository
 * said "ZClassic is Equihash 200,9" as a flat present-tense fact. That was
 * true at launch and has been wrong on mainnet since the Bubbles upgrade:
 * consensus selects (N,K) BY HEIGHT out of EquihashUpgradeInfo, and a reader
 * who believes the flat claim will size a solution buffer, a miner, or a
 * verifier against the wrong parameters. A hand-written correction would
 * simply drift again at the next upgrade.
 *
 * So this tool links the REAL chainparams and upgrade tables — the same
 * translation units the node validates blocks with — walks every network's
 * upgrade schedule, and prints what consensus would answer at each activation
 * height. `make equihash-facts` writes the document;
 * `make equihash-facts-check` fails when the committed document no longer
 * matches the tables, which is what stops the drift. Nothing here restates a
 * parameter: change the consensus table and the document follows, or the gate
 * names it.
 */

#include "chain/chainparams.h"
#include "chain/chainparamsbase.h"
#include "consensus/params.h"
#include "consensus/upgrades.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

struct network_row {
    enum chain_network id;
    const char *label;
};

static const struct network_row NETWORKS[] = {
    { CHAIN_MAIN, "mainnet" },
    { CHAIN_TESTNET, "testnet" },
    { CHAIN_REGTEST, "regtest" },
};

/* The height at which an epoch begins, or -1 when it never activates. */
static int epoch_start(const struct consensus_params *c, int idx)
{
    if (idx == (int)BASE_SPROUT)
        return 0;
    return c->vUpgrades[idx].nActivationHeight;
}

static void emit_network(FILE *out, const struct network_row *row)
{
    chain_params_select(row->id);
    const struct chain_params *p = chain_params_get();
    const struct consensus_params *c = &p->consensus;

    fprintf(out, "### %s\n\n", row->label);
    fprintf(out, "| From height | Upgrade | Equihash (N,K) | Solution bytes |\n");
    fprintf(out, "|---|---|---|---|\n");

    int last_n = -1, last_k = -1;
    for (int idx = (int)BASE_SPROUT; idx < (int)MAX_NETWORK_UPGRADES; idx++) {
        int height = epoch_start(c, idx);
        if (height < 0)
            continue; /* disabled on this network: it decides nothing */
        unsigned n = chain_params_equihash_n(p, height);
        unsigned k = chain_params_equihash_k(p, height);
        if ((int)n == last_n && (int)k == last_k)
            continue; /* same parameters: not a row a reader needs */
        last_n = (int)n;
        last_k = (int)k;
        /* One solution is 2^K * (N/(K+1) + 1) bits, the size consensus
         * accepts in the header. This is the number people actually reach
         * for the flat claim to get. */
        unsigned long bits = (1uL << k) * ((unsigned long)n / (k + 1u) + 1uL);
        fprintf(out, "| %d | %s | %u,%u | %lu |\n", height,
                NetworkUpgradeInfo[idx].strName, n, k, bits / 8uL);
    }
    fputc('\n', out);
}

int main(int argc, char **argv)
{
    FILE *out = stdout;
    if (argc > 1) {
        out = fopen(argv[1], "w");
        if (!out) {
            fprintf(stderr, "equihash_params_fact: cannot write %s\n", argv[1]);
            return 1;
        }
    }

    fprintf(out,
        "<!-- GENERATED by tools/equihash_params_fact.c — do not edit.\n"
        "     Regenerate with: make docs-equihash-params\n"
        "     The staleness gate is: make check-equihash-params -->\n\n"
        "# Equihash parameters, by height\n\n"
        "ZClassic's proof-of-work parameters are **selected by height**, not\n"
        "fixed for the life of the chain. Consensus reads them from\n"
        "`EquihashUpgradeInfo` (`core/params/src/upgrades.c`) through\n"
        "`chain_params_equihash_n/k` (`core/chainparams/src/chainparams.c`),\n"
        "so the answer depends on which block you are asking about.\n\n"
        "**Current mainnet is 192,7.** The launch parameters, 200,9, apply\n"
        "only below the Bubbles activation height. Saying \"ZClassic is\n"
        "Equihash 200,9\" without that qualifier describes a range of blocks\n"
        "that ended years ago, and sizes a solution buffer wrongly.\n\n"
        "Every number below is printed by linking the same translation units\n"
        "the node validates blocks with. Nothing here is transcribed.\n\n");

    for (size_t i = 0; i < sizeof NETWORKS / sizeof NETWORKS[0]; i++)
        emit_network(out, &NETWORKS[i]);

    fprintf(out,
        "A row appears only where the parameters change, so a network with\n"
        "one row has used the same parameters since genesis.\n");

    if (out != stdout)
        fclose(out);
    return 0;
}
