#!/usr/bin/env bash
# Copyright 2026 Rhett Creighton - Apache License 2.0
# Harvest (height, hash) checkpoint pairs from a running zclassicd.
# Emits two C source fragments for core/modules/chain/src/chainparams.c:
#   /tmp/checkpoints_decl.c  — the array declaration (heights only)
#   /tmp/checkpoints_init.c  — the uint256_set_hex initializers
#
# Trust model: local zclassicd is an advisory reference. Its
# (height,hash) sequence below the explicit 10-block finality floor is
# useful only when it also matches zclassic23 anchors/quorum.
#
# Usage: tools/harvest_checkpoints.sh
set -euo pipefail

RPC_USER="${RPC_USER:-zcluser}"
RPC_PASS="${RPC_PASS:-zclpass}"
RPC_PORT="${RPC_PORT:-8232}"
STEP="${STEP:-50000}"
OUT_DECL="${OUT_DECL:-/tmp/checkpoints_decl.c}"
OUT_INIT="${OUT_INIT:-/tmp/checkpoints_init.c}"
OUT_COUNT="${OUT_COUNT:-/tmp/checkpoints_count.txt}"

json_str() {
    printf '%s' "$1" | grep -oE "\"$2\"[[:space:]]*:[[:space:]]*\"[^\"]*\"" |
        head -1 | sed -E 's/.*:[ ]*"//; s/"$//'
}
json_num() {
    printf '%s' "$1" | grep -oE "\"$2\"[[:space:]]*:[[:space:]]*-?[0-9]+" |
        head -1 | sed -E 's/.*:[ ]*//'
}

rpc() {
    local method="$1" params="${2:-[]}"
    local body resp
    body=$(printf '{"jsonrpc":"1.0","id":"h","method":"%s","params":%s}' \
        "$method" "$params")
    resp=$(curl -sS --max-time 30 \
        --user "${RPC_USER}:${RPC_PASS}" \
        --data-binary "$body" \
        -H 'content-type: text/plain;' \
        "http://127.0.0.1:${RPC_PORT}/")
    local err
    err=$(json_str "$resp" message)
    if [ -n "$err" ]; then
        echo "harvest_checkpoints: RPC $method failed: $err" >&2
        exit 1
    fi
    printf '%s' "$resp"
}

tip=$(json_num "$(rpc getblockcount)" result)
[ -n "$tip" ] || { echo "harvest_checkpoints: no tip" >&2; exit 1; }
finalized=$((tip - 10))

heights="0"
h="$STEP"
while [ "$h" -le "$finalized" ]; do
    heights="$heights $h"
    h=$((h + STEP))
done

hashes=""
for height in $heights; do
    bh=$(json_str "$(rpc getblockhash "[$height]")" result)
    if [ "${#bh}" -ne 64 ]; then
        echo "harvest_checkpoints: bad hash at h=${height}: ${bh}" >&2
        exit 1
    fi
    hashes="$hashes $bh"
done

count=0
for _ in $heights; do
    count=$((count + 1))
done
deepest=0
for height in $heights; do
    deepest=$height
done

{
    printf '/* Harvested from local zclassicd tip=%s, finalized through height %s.\n' \
        "$tip" "$finalized"
    printf ' * Generated by tools/harvest_checkpoints.sh — do not hand-edit. */\n'
    printf 'static struct checkpoint_entry mainnet_checkpoints[] = {\n'
    for height in $heights; do
        printf '    { %s, {{0}} },\n' "$height"
    done
    printf '};\n'
} >"$OUT_DECL"

{
    printf '    /* %s checkpoints, harvested by tools/harvest_checkpoints.sh */\n' \
        "$count"
    i=0
    # Pair heights with hashes in lockstep.
    set -- $hashes
    for height in $heights; do
        bh=$1
        shift
        printf '    uint256_set_hex(&mainnet_checkpoints[%s].hash,\n' "$i"
        printf '        "%s");  /* h=%s */\n' "$bh" "$height"
        i=$((i + 1))
    done
} >"$OUT_INIT"

printf '%s\n' "$count" >"$OUT_COUNT"
printf 'wrote %s, %s, %s: %s entries, deepest at height %s\n' \
    "$OUT_DECL" "$OUT_INIT" "$OUT_COUNT" "$count" "$deepest"
